### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by dlwh**
(trivial drive-by fix)

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by tjingrant** [comment]
@dlwh thanks for your help!

DocCheck is complaining because the documentation for ONNX Dialect located here (https://github.com/onnx/onnx-mlir/blob/master/docs/Dialects/onnx.md) is out-of-date due to this patch. You can use the following sequence of commands to sync the doc:

```bash
cd onnx-mlir/build
# Generates the onnx dialect documentation.
cmake --build . --target onnx-mlir-doc
# Move the generated documentation to the correct place.
mv docs/Dialects/onnx.md ../docs/Dialects/onnx.md
```

Happy to help out if this doesn't work out.

**Review by chentong319 — APPROVED** [review]
LGTM

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by caoimhinuibrian** [comment]
@dlwh can you fix the DCO check failure please?

**Pull request merged**
