### PR TITLE
Update to v2 docker REST API

### PR DESCRIPTION
**Pull request by gongsu832**
To prepare for migrating to ghcr.io, update to v2 docker REST API since ghcr.io only supports v2.

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Review by AlexandreEichenberger — APPROVED** [review]
I cannot vouch for the correctness of the changes, let us know if you have someone with expertise in this area that can look into the details of the changes. Otherwise, if its good, feel free to merge.

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Pull request merged**
