### PR TITLE
Fix cmake find_package(JNI) (llvm-12-release-branch)

### PR DESCRIPTION
**Pull request by gongsu832**
New cmake level also checks for JAVA_AWT_LIBRARY when find_package(JNI)

Signed-off-by: Gong Su <gong_su@hotmail.com>

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
@caoimhinuibrian Do you mind checking this one. A quick scan looks good to me, but you are more familiar with the bots... Tx

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Pull request merged**
