### PR TITLE
[DO NOT COMMIT] Release mode2 with forced release

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Same PR as #672 but forcing release mode using the trick from @tungld in #567

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
lit and backend test run on z, but these ones still fails
```
Running tests...
Test project /workdir/onnx-mlir/build
    Start 1: OMTestConv
    Start 2: OMTestMatMul2D
    Start 3: OMTestGemm
    Start 4: OMTestLoop
    Start 5: OMTestGRU
    Start 6: OMTestLSTM
    Start 7: OMTestRNN
    Start 8: OMTensorTest
1/8 Test #8: OMTensorTest .....................   Passed    0.00 sec
2/8 Test #4: OMTestLoop .......................   Passed    0.00 sec
3/8 Test #3: OMTestGemm .......................***Exception: SegFault  0.12 sec
4/8 Test #2: OMTestMatMul2D ...................***Exception: SegFault  0.12 sec
5/8 Test #1: OMTestConv .......................***Exception: SegFault  0.13 sec
6/8 Test #5: OMTestGRU ........................***Exception: SegFault  0.15 sec
7/8 Test #7: OMTestRNN ........................***Exception: SegFault  0.16 sec
8/8 Test #6: OMTestLSTM .......................***Exception: SegFault  0.18 sec
```

will investigate

**Comment by AlexandreEichenberger** [comment]
The problem happens inside the model, where there is a that has a null tensor pointer. I added some debug printf below. Since I am not too familiar with the part of the code that generates the alloc of the tensors (which I assume are for the output), @caoimhinuibrian would you be able to see what is happening? 

```
Starting program: /home/eichen/Onnxcode/onnx-mlir/build/Release/bin/TestGemm
RapidCheck test case generation.
Using configuration: seed=14653293905756084801

- Gemm implementation correctness
attempt 1 with i 1, j 1, k 1, cRank 1

Shared library ./TestGemm_main_graph.so has been compiled.
hi alex: omTensorSetDataPtr with tensor 0x0, owning 1, allocPtr 0x2aa020b1730, alignPtr 0x2aa020b1780

Program received signal SIGSEGV, Segmentation fault.
0x000003fffdf023cc in omTensorSetDataPtr () from ./TestGemm_main_graph.so
```

and the debug code I added:
```
void omTensorSetDataPtr(
    OMTensor *tensor, int owning, void *allocatedPtr, void *alignedPtr) {
  printf("hi alex: omTensorSetDataPtr with tensor 0x%llx, owning %i, allocPtr "
         "0x%llx, alignPtr 0x%llx\n",
      (long long)((void *)tensor), owning, (long long)allocatedPtr,
      (long long)alignedPtr);
  if (tensor->_owning) { 
    /* If we own the allocated buffer, free it first. */
    printf("  attempt to free ptr 0x%llx\n", (long long) tensor->_allocatedPtr);
    free(tensor->_allocatedPtr);
  } else {
    printf("  no freeing of ptr\n");
  }
  tensor->_owning = owning;
  tensor->_allocatedPtr = allocatedPtr;
  if (alignedPtr)
    tensor->_alignedPtr = alignedPtr;
  else
    tensor->_alignedPtr = allocatedPtr;
}
```

**Comment by tungld** [comment]
@AlexandreEichenberger Let's see how to fix segfault with this commit: https://github.com/onnx/onnx-mlir/pull/567/commits/4cd0bc23fb63bd7dc76f0818b15c535fbc59e822

TestGemm still failed, but not because of segfault:
```
Shared library ./TestGemm_main_graph.so has been compiled.
attempt 2 with i 1, j 1, k 1, cRank 1
Shared library ./TestGemm_main_graph.so has been compiled.
attempt 3 with i 1, j 1, k 1, cRank 1
Shared library ./TestGemm_main_graph.so has been compiled.
a[0,0] = 9.55686e-43 != b[0,0] = 1.38327
Falsifiable after 1 tests

int:
1

int:
1

int:
1

int:
0

int:
0

int:
1

int:
0

int:
0

/home/tungld/dl/onnx-mlir/test/numerical/TestGemm.cpp:204:
RC_ASSERT(isOMGemmTheSameAsNaiveImplFor( I, J, K, aTrans, bTrans, cRank, alpha, beta))

Expands to:
false
Some of your RapidCheck properties had failures. To reproduce these, run with:
RC_PARAMS="reproduce=B8xRl1WbgkWbwxWZtVmb0FGdp9mbgM2byJXZjRnblN3c7Bqko0uNNj4egKJKtbTzIuHoSiS720Mi7Bqko0uNNjYAAEAAAAAAAA"
```

**Comment by tungld** [comment]
The problem with segfault here is quite interesting and it's magic to me. It happens inside `omTensorCreateEmptyDeprecated`, where after multiple calls, the allocation for shape and strides, using malloc, always returns NULL.

If we use something like:
```
int rank = 10;
void buffer = malloc(rank * sizeof(int64_t);
```
Alfter several call, malloc failed and returned NULL.

But all of the following codes work:
```
int64_t rank = 10;
void buffer = malloc(rank * sizeof(int64_t);
```
or
```
int rank = 10;
void buffer = malloc(rank * (int)sizeof(int64_t);
```

```
void buffer = malloc(1024);
```

That's the reason I changed the type of rank to int64_t.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 can you look into the s390x build? It succeeded all the test but the doc-check, where it fails with this
```
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/ONNX-MLIR-Pipeline-Docker-Build@pr_677/.buildbot/jenkins-build-project.py", line 324, in <module>
    main()
  File "/var/lib/jenkins/workspace/ONNX-MLIR-Pipeline-Docker-Build@pr_677/.buildbot/jenkins-build-project.py", line 321, in main
    build_private_project('usr', get_proj_repo_info('usr', '.'))
  File "/var/lib/jenkins/workspace/ONNX-MLIR-Pipeline-Docker-Build@pr_677/.buildbot/jenkins-build-project.py", line 310, in build_private_project
    raise Exception(line['error'])
Exception: failed to get digest sha256:cd9c86c94b79ec34dfaa8d10f931a381a350e7b6d9e55d3cb71c11272e33f0c5: open /opt/docker/image/overlay2/imagedb/content/sha256/cd9c86c94b79ec34dfaa8d10f931a381a350e7b6d9e55d3cb71c11272e33f0c5: no such file or directory
```

Is that a fluke, or something with Jenkins, or something with the onnx-mlir code?

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by caoimhinuibrian** [comment]
@AlexandreEichenberger can we close?

**Comment by AlexandreEichenberger** [comment]
Close as this has not been an issue as far as we know.

**Pull request closed without merging**
