### PR TITLE
Choose the correct version of op

### PR DESCRIPTION
**Pull request by chentong319**
There is an error in previous code that support multiple versions of an op. The error is exposed for yolo model after multiple version of Squeeze and Unsqueezed was added.
There are two versions, 13 and 11 for Squeeze. The yolo model have version 12. We should choose 11. We need the new version only 13 and higher. 
It's a small fix and the document is updated.

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Comment by NathanielMcVicar** [comment]
Is this fix required before v13 unsqueeze?

**Comment by chentong319** [comment]
> Is this fix required before v13 unsqueeze?

no, unless your model's op_set is 12.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
