### PR TITLE
Extend ONNX function translation to handle optional parameters

### PR DESCRIPTION
**Pull request by gramalingam**
ONNX functions permit optional parameters (just like ONNX ops). Extend the translation of ONNX function to MLIR function to handle missing optional parameters. Add a test-case to test it.

### CODE REVIEW

**Comment by chentong319** [comment]
At line 392 of FrontendTransformer.cpp, the comment says that there are two ways to leave optional input/output: 1) not provide, 2) give empty string. This patch handles case#2, while only case#1 is handled for ordinary onnx operation. 
Q1. Should this patch handle case#1 for function?
Q2. Should we add handling case#2 for ordinary onnx operation(perhaps by another patch)?

**Comment by gramalingam** [comment]
@chentong319 : this patch handles both kinds of omitted optional inputs. Here, we are mapping an ONNX call to a MLIR function and a call to that MLIR function. The solution adopted here is that the MLIR function has inputs that correspond only to the inputs that are actually present.

**Comment by gramalingam** [comment]
Regarding Q2: isn't it being handled for the empty-string case by pushing a NoneType value? There is the question of how trailing missing optional inputs are handled ... I assume that this is handled by the specification of the corresponding ONNX-MLIR dialect instruction ... if that MLIR instruction also allows the trailing optional inputs to be omitted, things should be fine. But if that MLIR instruction does not, then a patch may be required.

**Comment by gramalingam** [comment]
Hi, any further comments or questions about this PR? Thanks!

**Review by chentong319 — APPROVED** [review]
LGTM

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by gramalingam** [comment]
Great! I think it is ready to be merged, thanks!

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
