### PR TITLE
Softmax op dynamic shape addition for stablehlo

### PR DESCRIPTION
**Pull request by Abhishek-TyRnT**
Added support for dynamic shapes in Softmax Op for StableHLO Dialect

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — COMMENTED** [review]
LGTM, let me update to the latest version and I can then approve it.

**Comment by AlexandreEichenberger** [comment]
@Abhishek-TyRnT do you want me to merge it?

**Comment by Abhishek-TyRnT** [comment]
@AlexandreEichenberger  Yes, please go ahead and merge it

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
