### PR TITLE
Use local buffer for reduction loops in MatMul, Gemm, Conv, and Pooling ops

### PR DESCRIPTION
**Pull request by tungld**
This patch is to improve performance by using a local memory buffer for reduction loops.

The following reduction loop,
```mlir
%output = alloc() : memref<10x10xf32>
krnl.iterate {
  krnl.store %cst0, %output
  krnl.iterate {
     %a = krnl.load %input
     %b = krnl.load %output
     %b += %a
     krnl.store %b, %output
  }
}
```

will be replaced by:

```mlir
%output = alloc() : memref<10x10xf32>
krnl.iterate {
  %sum = alloca() : memref<f32>
  krnl.store %cst0, %sum
  krnl.iterate {
     %a = krnl.load %input
     %b = krnl.load %sum
     %b += %a
     krnl.store %b, %sum
  }
  %s = krnl.load %sum
  krnl.store %s, %output
}
```

Another advantage is, by extracting `krnl.store` outside of the reduction loop, the outer loop can be potentially fused with the next loops that load from the same memref.

### CODE REVIEW

**Comment by chentong319** [comment]
Which krnl.store do you mean by "extracting krnl.store outside of the reduction loop"? The new code is closer to the semantic. The memory reference of reduction should not cause data dependence for the outer loop.

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by tungld** [comment]
> Which krnl.store do you mean by "extracting krnl.store outside of the reduction loop"?

This one `krnl.store %b, %output` becomes `krnl.store %s, %output` outside of the reduction loop. This helps fuse the following loops:

```mlir
%output = alloc() : memref<10x10xf32>
krnl.iterate {
  %sum = alloca() : memref<f32>
  krnl.store %cst0, %sum
  krnl.iterate {
     %a = krnl.load %input
     %b = krnl.load %sum
     %b += %a
     krnl.store %b, %sum
  }
  %s = krnl.load %sum
  krnl.store %s, %output
}

krnl.iterate {
   %c = krnl.load %output
}
```
into 
```mlir
%output = alloc() : memref<10x10xf32>
krnl.iterate {
  %sum = alloca() : memref<f32>
  krnl.store %cst0, %sum
  krnl.iterate {
     %a = krnl.load %input
     %b = krnl.load %sum
     %b += %a
     krnl.store %b, %sum
  }
  %s = krnl.load %sum
  krnl.store %s, %output
   %c = krnl.load %output
}
```
and the pair (`krnl.store %s, %output`, `%a = krnl.load %output`) can be further eliminated.

**Comment by tungld** [comment]
@chentong319 this patch is ready now. Thanks!

**Pull request merged**
