### PR TITLE
Update the instrumentation tool

### PR DESCRIPTION
**Pull request by imaihal**
This PR updates the instrumentation tools
- Created dialect-independent pass for instrumentation (`InstrumentPass`) (https://github.com/onnx/onnx-mlir/issues/1790)
  - Removed zhigh-specific instrumentation pass (`InstrumentZHighPass`) 
- Updated command-line options (https://github.com/onnx/onnx-mlir/issues/1790)
  - Newly added `--instrument-stage=<stage name>` to set stage to be instrumented. Following stages are provided.
    - `before-onnx-to-krnl` : Profile for onnx ops (before lowering to krnl)
    - `nnpa-before-onnx-to-zhigh` : [NNPA] Profile for onnx ops
    - `nnpa-before-onnx-to-krnl` : [NNPA] Profile for onnx and zhigh ops
    - `nnpa-before-krnl-to-llvm` : [NNPA] Profile for zlow ops 
  - Changed `--instrument-onnx-ops` to `--instrument-ops`
- Display instrumented `<dialect name>.<ops name>` in profile output at runtime (https://github.com/onnx/onnx-mlir/issues/1790)

Example output (part of yolov3)
  - --maccel=NNPA --instrument-stage=nnpa-before-onnx-to-krnl --instrument-ops=onnx.,zhigh. --InstrumentBeforeOp --InstrumentAfterOp --InstrumentReportTime 
```
#1082) before    zhigh.StickifiedConstant Time elapsed: 0.000000 accumulated: 1666678513.998812
#1083) after     zhigh.StickifiedConstant Time elapsed: 0.000001 accumulated: 1666678513.998813
#1084) before    zhigh.StickifiedConstant Time elapsed: 0.000000 accumulated: 1666678513.998813
#1085) after     zhigh.StickifiedConstant Time elapsed: 0.000001 accumulated: 1666678513.998814
#1086) before    zhigh.Conv2D Time elapsed: 0.000000 accumulated: 1666678513.998814
#1087) after     zhigh.Conv2D Time elapsed: 0.000094 accumulated: 1666678513.998908
#1088) before    zhigh.Unstick Time elapsed: 0.000000 accumulated: 1666678513.998908
#1089) after     zhigh.Unstick Time elapsed: 0.000081 accumulated: 1666678513.998989
#1090) before     onnx.Transpose Time elapsed: 0.000001 accumulated: 1666678513.998990 (Transpose__472)
#1091) after      onnx.Transpose Time elapsed: 0.000022 accumulated: 1666678513.999012 (Transpose__472)
#1092) before     onnx.Constant Time elapsed: 0.000000 accumulated: 1666678513.999012
#1093) after      onnx.Constant Time elapsed: 0.000001 accumulated: 1666678513.999013
#1094) before     onnx.Ceil Time elapsed: 0.000003 accumulated: 1666678513.999016 (TFNodes/yolo_evaluation_layer_1/arange_1__246_ceil)
```
  - --maccel=NNPA --instrument-stage=nnpa-before-onnx-to-zhigh --instrument-ops=onnx. --InstrumentBeforeOp --InstrumentAfterOp --InstrumentReportTime 

```
#605) after      onnx.Constant Time elapsed: 0.000001 accumulated: 1666672996.216718
#606) before     onnx.Conv Time elapsed: 0.000000 accumulated: 1666672996.216718
#607) after      onnx.Conv Time elapsed: 0.001473 accumulated: 1666672996.218191
#608) before     onnx.LeakyRelu Time elapsed: 0.000001 accumulated: 1666672996.218192 (leaky_re_lu_58)
#609) after      onnx.LeakyRelu Time elapsed: 0.000000 accumulated: 1666672996.218192 (leaky_re_lu_58)
#610) before     onnx.Conv Time elapsed: 0.000001 accumulated: 1666672996.218193 (conv2d_59)
#611) after      onnx.Conv Time elapsed: 0.000337 accumulated: 1666672996.218530 (conv2d_59)
#612) before     onnx.Transpose Time elapsed: 0.000001 accumulated: 1666672996.218531 (Transpose__472)
#613) after      onnx.Transpose Time elapsed: 0.000022 accumulated: 1666672996.218553 (Transpose__472)
#614) before     onnx.Constant Time elapsed: 0.000001 accumulated: 1666672996.218554
#615) after      onnx.Constant Time elapsed: 0.000000 accumulated: 1666672996.218554
#616) before     onnx.Ceil Time elapsed: 0.000001 accumulated: 1666672996.218555 (TFNodes/yolo_evaluation_layer_1/arange_1__246_ceil)
#617) after      onnx.Ceil Time elapsed: 0.000001 accumulated: 1666672996.218556 (TFNodes/yolo_evaluation_layer_1/arange_1__246_ceil)

```
  - --instrument-stage=before-onnx-to-krnl --instrument-ops=onnx. --InstrumentBeforeOp --InstrumentAfterOp --InstrumentReportTime
```
#840) before     onnx.Add Time elapsed: 0.000001 accumulated: 1666672427.600953
#841) after      onnx.Add Time elapsed: 0.000009 accumulated: 1666672427.600962
#842) before     onnx.Constant Time elapsed: 0.000001 accumulated: 1666672427.600963
#843) after      onnx.Constant Time elapsed: 0.000001 accumulated: 1666672427.600964
#844) before     onnx.Reshape Time elapsed: 0.000000 accumulated: 1666672427.600964
#845) after      onnx.Reshape Time elapsed: 0.000001 accumulated: 1666672427.600965
#846) before     onnx.Transpose Time elapsed: 0.000000 accumulated: 1666672427.600965 (Transpose__472)
#847) after      onnx.Transpose Time elapsed: 0.000022 accumulated: 1666672427.600987 (Transpose__472)
#848) before     onnx.Constant Time elapsed: 0.000001 accumulated: 1666672427.600988
#849) after      onnx.Constant Time elapsed: 0.000000 accumulated: 1666672427.600988
#850) before     onnx.Constant Time elapsed: 0.000001 accumulated: 1666672427.600989
#851) after      onnx.Constant Time elapsed: 0.000000 accumulated: 1666672427.600989
#852) before     onnx.Ceil Time elapsed: 0.000001 accumulated: 1666672427.600990 (TFNodes/yolo_evaluation_layer_1/arange_1__246_ceil)
```

### CODE REVIEW

**Comment by chentong319** [comment]
I was thinking in another way: use the string match to specify which op should be instrumented.
For every Op, we can get a string 'dialect_name.op_name', such as "onnx.Conv", "ZHigh.Conv", or "ZHigh.stick". In the command   line option, we can control the instrumentation by 
1. which stage of instrumentation should be enabled
2. which op should be instrument
For example of NNPA, there are two stages. The option could be Instrument="[stage position ops]", where stage will be a string used in the constructor of the instrumentation pass. position could be one of "before", "after" or "both". The ops should be a list of string in form of onnx.*, ZHigh.*, *.Conv and etc. We can use string match utility to check against the 'dialect_name.op_name' for each op. In this way, it is simple to change and flexible in specification.
How do you think?

**Comment by imaihal** [comment]
@chentong319 Thanks for your comments!

That's should be more flexible. How can we set/select the `stage`? Do we need to add specific string in each pass such as `onnx-to-zhigh` and show them to users in help?

**Comment by chentong319** [comment]
> @chentong319 Thanks for your comments!
> 
> That's should be more flexible. How can we set/select the `stage`? Do we need to add specific string in each pass such as `onnx-to-zhigh` and show them to users in help?

Yes, you are right in both: We add a string to the instrumentation constructor and add this string in the instrumentation option help.

**Comment by tungld** [comment]
> --instrument-dialects=onnx,zhigh --nstrument-ops=ALL --InstrumentBeforeOp --InstrumentAfterOp --InstrumentReportTime

A general comment: could we make these options local to the pass? e.g., 
```
--instrument="dialects=onnx,zhigh ops=ALL  BeforOp=true AfterOp=true ReportTime=true"
```

**Comment by imaihal** [comment]
@tungld Thanks for your comments!

Considering @chentong319's comments, the option might be `--instrument=[after-onnx-to-onnx both onnx.*][after-onnx-to-zhigh both zhigh.*]` or `--instrument=[stage=after-onnx-to-onnx place=both ops=onnx.*][stage=after-onnx-to-zhigh place=both ops=zhigh.*]`.

**Comment by chentong319** [comment]
I did not think about how to parse the option with llvm utility. The base line is that the option can be just a string and parsed by instrumentation pass. 
As for the character '[' and ']', I just used them to illustrate the delimiters needed here. They depend on how the option is processed and can be just those characters if the string is parsed by ourselves, or certain format required by the llvm option utility.

**Comment by imaihal** [comment]
I thought the options need to be parsed manually as current instrumentation options do, but I think we need to consider the format.

> One important question: how many instrumentation pass can be enabled when a program is compiled? 
When I wrote previous comment, I thought multiple instrumentation passes in one compilation are required, but single pass might be enough because we can get another profiling results by compiling and run again using another instrumentation pass.

**Comment by chentong319** [comment]
> When I wrote previous comment, I thought multiple instrumentation passes in one compilation are required, but single pass might be enough because we can get another profiling results by compiling and run again using another instrumentation pass.
Sure, let's assume only one instrumentation pass will be enabled at one compile. Then we can add one enum option, called instrumentStage. The code in CompilerPasses.cpp will like:
```
if (instrumentStage == myStage)
   pm.addNestedPass<func::FuncOp>(onnx_mlir::createInstrumentONNXPass(
      instrumentONNXOps, instrumentControlBits.getBits()))
```
We need to change the instrumentation pass to handle the string of instrumentOps, as we discussed previously.
We may clean the code by move the instrumentation pass away from ONNX in future. No urgent to do that.

**Comment by imaihal** [comment]
>  We may clean the code by move the instrumentation pass away from ONNX in future. No urgent to do that.

Ah... I am already updating what you suggested except compiler option change(not pushed yet, though). May I do bit more in this PR?

**Comment by chentong319** [comment]
I reviewed the current changes. It is good to pass string of op name to the library.
For this PR, I think that we just support one instrumentation pass enabled. The changes are
1. Match the regular expression with the op name. This is anyhow needed
2. Add a condition check when an instrumentation pass is added, like
```
if (instrumentStage == myStage)
   pm.addNestedPass<func::FuncOp>(onnx_mlir::createInstrumentONNXPass(
      instrumentONNXOps, instrumentControlBits.getBits()))
```
We did not pass instrumentStage option into InstrumentONNXPass because it is not needed for onnx-mlir-opt. It is a control for onnx-mlir passes.
If you have extra energy, you can use limited range option for instrumentStage. Refer to https://llvm.org/docs/CommandLine.html#selecting-an-alternative-from-a-set-of-possibilities.

**Comment by chentong319** [comment]
I just realized that you already have the changes, but in a new file name.

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by imaihal** [comment]
@chentong319 Thanks for your review and merge. 

I forgot to update docs. So, I will create another PR to update it. Also, I will update the options in the PR. Thanks!

**Pull request merged**
