### PR TITLE
[NFC] Fix build warnings

### PR DESCRIPTION
**Pull request by kevcadieux**
This change fixes 2 build errors that may appear when treating warnings as errors:

1. Fix signed/unsigned mismatch in `ShapeHelper.cpp` by using a `size_t` induction variable to match the return type of `shape.size()`.
2. Fix unused `logMessage` function warning in `HeapReporter.cpp` by only defining it for the APPLE platform, the only platform under which it is called.

Signed-off-by: Kevin Cadieux <kevca@microsoft.com>

### CODE REVIEW

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by kevcadieux** [comment]
I don't seem to be able to add a reviewer to my PR. Possible candidates: 
@sorenlassen : for change in `HeapReporter.cpp`
@AlexandreEichenberger : for change in `ShapeHelper.cpp`

**Review by sorenlassen — APPROVED** [review]
thanks for the fixes

I had to look up [what NFC means](https://docs.civicrm.org/dev/en/latest/tools/git/#nfc) :)

**Comment by kevcadieux** [comment]
@sorenlassen : thanks for the approval!
@AlexandreEichenberger : thanks for adding me to Collaborators!

**Comment by kevcadieux** [comment]
@sstamenova Thanks for starting the tests!

**Pull request merged**
