### PR TITLE
Update LLVM/MHLO for Week of 10/31/2022

### PR DESCRIPTION
**Pull request by chenchongsong**
Green LLVM commit: 74fb770de9399d7258a8eda974c93610cfde698e
Green MHLO commit: 2341f70343a5361d4611557c2af9d24b01aa427e

The commits listed above are the latest Green commits.
We wish to apply these two commits to all frontends internally in ByteDance (e.g. onnx, torch, tensorflow)

Changelog:
- Change `NoSideEffect` trait to `Pure`
- Add workaround for missing mhlo dependency (StablehloAssemblyFormat & StablehloTypeInference)
- Use RankedTensor instead of Vector for the attributes of mhlo::ReduceWindowOp

PR for mhlo to fix dependencies: https://github.com/tensorflow/tensorflow/pull/58477

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by chenchongsong** [comment]
@gongsu832 @tungld
Seems that the Jenkins job was aborted. May I have the Jenkins jobs run again?
There is another issue related to "GitHub Action MacOS amd64 / build". I found `import onnx` error for all recent PRs. Not sure what causes that.

**Comment by gongsu832** [comment]
The jobs are still running, just the status hasn't been updated yet.

**Comment by tungld** [comment]
@jenkins-droid test this please

**Review by sstamenova — APPROVED** [review]
LGTM

**Comment by chenchongsong** [comment]
@tungld @gongsu832 Could you help to merge this PR? Thanks so much~

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Pull request merged**
