### PR TITLE
support map and seq in tablegen

### PR DESCRIPTION
**Pull request by chentong319**
Previously, only direct tensor structure is supported. ONNX also has seq of tensor and map of tensor. This patch is to detect them in for in gen_onnx_mlir. However, the two data structures have not been supported yet. Placeholder for them are added:

- For seq of tensor, tensor of tensor is used.
- For map of tensor, TupleOf tensor is used. It seem to me that the Tablegen can not support to specify exact number member in the tuple.

TupleOf tensor works for maps, but tensor of tensor can only pass compilation but will give warning for verify or error for parser, if operation with seq is used. 

Future work:
It seems dialect type need to be defined for seq.
The functionality of importing from protobuf for these data structure will be added to Builder.
 The output type inference will also be added.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
I don't see a "WIP"... is it ready for review?

**Comment by chentong319** [comment]
> I don't see a "WIP"... is it ready for review?

Yes, it is ready for review.

**Comment by tjingrant** [comment]
Will we be able to create IR that accepts a tensor/sequence of tensor?

**Comment by tjingrant** [comment]
Can we see some IR examples to understand concretely how this patch manifest at the IR level? It feels to me that everything is up-in-the-air and I have no concrete grasp of what's going on.

**Comment by chentong319** [comment]
It turned out that using tensor of tensor for seq or tuple of tensor for map does not work of the  parser of IR. It only works with builder. My experiment with Builder got this result (I arbitrarily built some operation with FrontendDialectTransformer.cpp):
`onnx-mlir --EmitONNXBasic xxx.onnx` 

The resulted xxx.onnx.mlir is
`
module {
  func @main_graph(%arg0: tensor<1x3x28x28xf32>) -> tensor<1xf32> {
    %cst = constant unit
    %0 = "onnx.Constant"() {value = dense<0.000000e+00> : tensor<1xf32>} : () -> tensor<1xf32>
    %1 = "onnx.Constant"() {value = dense<2.000000e+00> : tensor<1xf32>} : () -> tuple<tensor<1xf32>, tensor<1xf32>>
    %2 = "onnx.Add"(%0, %1) : (tensor<1xf32>, tuple<tensor<1xf32>, tensor<1xf32>>) -> tensor<1xf32>
    return %2 : tensor<1xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 1 : i32, numOutputs = 1 : i32} : () -> ()
}
`
However, onnx-mlir-opt can not take this as input. The error message said the tupleof or tensor can not take tensor as member, which is consistent with the document.

A example of seq with "real" operation is:
`
func @main_graph(%arg0: tuple<tensor<10xi64>, tensor<10xf32>>) -> tensor<*xf32> {
  %0 = "mlonnx.CastMap"(%arg0) {cast_to = "TO_FLOAT", map_form = "DENSE", max_map = 1} : (tuple<tensor<10xi64>, tensor<10xf32>>) -> tensor<*xf32>
  return %0 : tensor<*xf32>
}
`
A result of the test is that I fixed the error that MLONNX dialect is not registered.

I changed the purpose of this pull to just identify seq and map and has something marked in table gen. If you think the patch is not mature enough, I am fine with just close it.

**Pull request merged**
