### PR TITLE
Fix libompruntime.a install bug

### PR DESCRIPTION
**Pull request by gongsu832**

### CODE REVIEW

**Comment by chentong319** [comment]
Can you modify docs/BuildOnLinux.md to include the command to build llvm-project with OpenMP enabled? Kind of add your command in Runtime/omp/CMakeList.txt to the document.

**Comment by gongsu832** [comment]
> Can you modify docs/BuildOnLinux.md to include the command to build llvm-project with OpenMP enabled? Kind of add your command in Runtime/omp/CMakeList.txt to the document.

OpenMP support is also related to the `-parallel` option. And there is a question about how to set the number of threads. I'm not very familiar with OpenMP stuff so I think @AlexandreEichenberger is probably at a better position to update the related documents.

**Comment by chentong319** [comment]
> OpenMP support is also related to the `-parallel` option. And there is a question about how to set the number of threads. I'm not very familiar with OpenMP stuff so I think @AlexandreEichenberger is probably at a better position to update the related documents.

`--parallel` is the flag to compile a model. What I asked for is how to build llvm-project for amp.  Is this command correct?

```
cmake -G Ninja ../llvm \
   -DLLVM_ENABLE_PROJECTS="mlir;clang;openmp" \
   -DLLVM_TARGETS_TO_BUILD="host" \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_ENABLE_ASSERTIONS=ON \
   -DLLVM_ENABLE_RTTI=ON \
   -DLIBOMP_ENABLE_SHARED=OFF \
   -DLLVM_ENABLE_LIBEDIT=OFF
```

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, trust @gongsu832 that this change is needed

**Comment by gongsu832** [comment]
> > OpenMP support is also related to the `-parallel` option. And there is a question about how to set the number of threads. I'm not very familiar with OpenMP stuff so I think @AlexandreEichenberger is probably at a better position to update the related documents.
> 
> `--parallel` is the flag to compile a model. What I asked for is how to build llvm-project for amp. Is this command correct?
> 
> ```
> cmake -G Ninja ../llvm \
>    -DLLVM_ENABLE_PROJECTS="mlir;clang;openmp" \
>    -DLLVM_TARGETS_TO_BUILD="host" \
>    -DCMAKE_BUILD_TYPE=Release \
>    -DLLVM_ENABLE_ASSERTIONS=ON \
>    -DLLVM_ENABLE_RTTI=ON \
>    -DLIBOMP_ENABLE_SHARED=OFF \
>    -DLLVM_ENABLE_LIBEDIT=OFF
> ```

Yes. My point was that all OpenMP related documentation should be updated at once, not in a piecemeal fashion.

**Pull request merged**
