### PR TITLE
Avoid assertion failure of some rewriter pattern constraints

### PR DESCRIPTION
**Pull request by llehtahw**
See https://github.com/llvm/llvm-project/blob/64186e9b351a000123f253557f4f607c33405413/mlir/include/mlir/IR/BuiltinTypeInterfaces.td#L137

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
Thanks for the fix, code looks good and will approve after a clean run. Please look into the DCO, which must be signed for code to get in.

See our workflow step 7 doc.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by llehtahw** [comment]
@AlexandreEichenberger What should I do next 👀 
Seems @jenkins-droid did not want to test this 😆

**Review by tungld — APPROVED** [review]
LGTM. Thanks for the patch!

**Comment by AlexandreEichenberger** [comment]
Not sure what happened, merged the PR now. Thanks for the fix

**Pull request merged**
