### PR TITLE
Enable some dynamic backend tests

### PR DESCRIPTION
**Pull request by tungld**
Enable dynamic backend tests for some operations.

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Review by chentong319 — COMMENTED** [review]
For unsqueezed, can the second input, `axis`, be dynamic? I guess all the test cases have a constant for axis. For us, better to specify that only the first input to be dynamic in `dynamic_input_dict` for unsqueeze tests.

**Comment by AlexandreEichenberger** [comment]
@tungld The error on macOS is not the same as the one we use to have and ignore; its in the lit tests, for krnl_permute. Please look into it, keeping in mind that it might be simply a problem of operation order (which might be the case as it works on the other platforms but not that one).

**Comment by AlexandreEichenberger** [comment]
@tungld Just a reminder to look at the failure for MacOS, as the previous issue is fixed for that test, and this error is different. Tx

**Comment by tungld** [comment]
> For unsqueezed, can the second input, axis, be dynamic? 

@chentong319 In onnx-mlir, unsqueeze's axes is an attribute, not an input. It's different from unsqueeze in the latest onnnx version: https://github.com/onnx/onnx-mlir/blob/master/src/Dialect/ONNX/ONNXOps.td.inc#L5675

@AlexandreEichenberger I cannot reproduce the problem on my MacOs. Just tried to trigger the test again to see whether it still happens or not.

**Comment by tungld** [comment]
Enable dynamic backend test for LSTM/GRU/ RNN also.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
