### PR TITLE
fix namespace leak

### PR DESCRIPTION
**Pull request by bxing-groq**
Signed-off-by: bxing <bxing@groq.com>

### CODE REVIEW

**Comment by bxing-groq** [comment]
@AlexandreEichenberger - here :)

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@bxing-groq please fix clang-format. I copy them here if you cannot see it by clicking `Detail` on the right-hand side of  `GitHub Action Clang Format` line.

```
--- ./src/Support/KrnlSupport.hpp	(original)
+++ ./src/Support/KrnlSupport.hpp	(reformatted)
@@ -41,8 +41,8 @@
 // Emit a constant of a specific type.
 // Use this function for small values only to avoid unexpected loss in type
 // casting.
-mlir::Value emitConstantOp(
-    mlir::OpBuilder &rewriter, mlir::Location loc, mlir::Type type, double value);
+mlir::Value emitConstantOp(mlir::OpBuilder &rewriter, mlir::Location loc,
+    mlir::Type type, double value);
 
 //===----------------------------------------------------------------------===//
 // Perform checks or get statistics about Krnl-level operations.
@@ -6[9](https://github.com/onnx/onnx-mlir/runs/5766966762?check_suite_focus=true#step:4:9),7 +69,8 @@
     mlir::KrnlGetRefOp *firstGetRef, mlir::KrnlGetRefOp *secondGetRef);
 
 /// Check if two GetRefs participate in the same operation.
-bool usedBySameOp(mlir::KrnlGetRefOp *firstGetRef, mlir::KrnlGetRefOp *secondGetRef);
+bool usedBySameOp(
+    mlir::KrnlGetRefOp *firstGetRef, mlir::KrnlGetRefOp *secondGetRef);
 
 /// Get the number of GetRef ops associated with this AllocOp.
 int64_t getAllocGetRefNum(mlir::memref::AllocOp *allocOp);
@@ -79,7 +80,8 @@
 
 /// This function returns true if `beforeOp` is visited before `op` in a
 /// traversal of the provided block.
-bool opBeforeOp(mlir::Block *block, mlir::Operation *beforeOp, mlir::Operation *afterOp);
+bool opBeforeOp(
+    mlir::Block *block, mlir::Operation *beforeOp, mlir::Operation *afterOp);
 
 /// Check Alloc operation result is used by a krnl.getref.
 bool checkOpResultIsUsedByGetRef(mlir::memref::AllocOp *allocOp);
@@ -[10](https://github.com/onnx/onnx-mlir/runs/5766966762?check_suite_focus=true#step:4:10)0,8 +102,9 @@
     mlir::PatternRewriter &rewriter, mlir::Location loc, mlir::Value val);
 
 /// Get the size of a dynamic MemRef in bytes.
-mlir::Value getDynamicMemRefSizeInBytes(mlir::MemRefType type, mlir::Location loc,
-    mlir::PatternRewriter &rewriter, mlir::memref::AllocOp allocOp);
+mlir::Value getDynamicMemRefSizeInBytes(mlir::MemRefType type,
+    mlir::Location loc, mlir::PatternRewriter &rewriter,
+    mlir::memref::AllocOp allocOp);
 
 /// Get order number of dynamic index.
 int64_t getAllocArgIndex(mlir::memref::AllocOp allocOp, int64_t index);
--- ./src/Conversion/KrnlToAffine/ConvertKrnlToAffine.hpp	(original)
+++ ./src/Conversion/KrnlToAffine/ConvertKrnlToAffine.hpp	(reformatted)
@@ -28,[13](https://github.com/onnx/onnx-mlir/runs/5766966762?check_suite_focus=true#step:4:13) +28,[15](https://github.com/onnx/onnx-mlir/runs/5766966762?check_suite_focus=true#step:4:15) @@
 using UnrollAndJamMap = std::map<mlir::Operation *, UnrollAndJamList *>;
 
 void populateKrnlToAffineConversion(mlir::LLVMTypeConverter &typeConverter,
-    mlir::RewritePatternSet &patterns,mlir:: MLIRContext *ctx);
-
-void populateLoweringKrnlCopyFromBufferOpPattern(mlir::TypeConverter &typeConverter,
     mlir::RewritePatternSet &patterns, mlir::MLIRContext *ctx);
 
-void populateLoweringKrnlCopyToBufferOpPattern(mlir::TypeConverter &typeConverter,
-    mlir::RewritePatternSet &patterns, mlir::MLIRContext *ctx);
+void populateLoweringKrnlCopyFromBufferOpPattern(
+    mlir::TypeConverter &typeConverter, mlir::RewritePatternSet &patterns,
+    mlir::MLIRContext *ctx);
+
+void populateLoweringKrnlCopyToBufferOpPattern(
+    mlir::TypeConverter &typeConverter, mlir::RewritePatternSet &patterns,
+    mlir::MLIRContext *ctx);
 
 void populateLoweringKrnlLoadOpPattern(mlir::TypeConverter &typeConverter,
     mlir::RewritePatternSet &patterns, mlir::MLIRContext *ctx);
--- ./src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.hpp	(original)
+++ ./src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.hpp	(reformatted)
@@ -[75](https://github.com/onnx/onnx-mlir/runs/5766966762?check_suite_focus=true#step:4:75),9 +75,8 @@
     mlir::LLVMTypeConverter &typeConverter, mlir::RewritePatternSet &patterns,
     mlir::MLIRContext *ctx);
 
-void determineOwnershipForOutputOMTensors(
-    mlir::ModuleOp &module, llvm::SmallVectorImpl<bool> &outputOMTensorOwnerships);
-
+void determineOwnershipForOutputOMTensors(mlir::ModuleOp &module,
+    llvm::SmallVectorImpl<bool> &outputOMTensorOwnerships);
 
 void recordEntryPointSignatures(mlir::ModuleOp &module,
     llvm::SmallVectorImpl<std::string> &entryPointNames,
```

**Comment by bxing-groq** [comment]
@whitneywhtsang Cool, thanks for that! Do you guys have a specific clang-format binary and config file?

**Comment by bxing-groq** [comment]
New PR: https://github.com/onnx/onnx-mlir/pull/1301

**Pull request closed without merging**
