### PR TITLE
simplified elements access in IndexExprBuilder::getValFromArray()

### LINKED ISSUE #2346: Datatype not correctly parsed for onnx-hybrid-transform and shape-inference pass
This error was found here: https://github.com/onnx/onnx-mlir/issues/2344

And when I was further debugging I was able to obtain the following stack trace:
```

root@7bc1ee526dda:~/onnx-mlir/build# onnx-mlir-opt --maccel=NNPA fraud_cnn_model.onnx.mlir --shape-inference -v
ElementsAttr does not provide iteration facilities for type `mlir::Attribute`, see attribute: dense_resource<__elided__> : tensor<4xi64>
invalid `T` for ElementsAttr::getValues
UNREACHABLE executed at /workdir/llvm-project/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h:308!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: onnx-mlir-opt --maccel=NNPA fraud_cnn_model.onnx.mlir --shape-inference -v
 #0 0x0000004004e303b0 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4e303b0)
 #1 0x0000004004e2dc84 SignalHandler(int) Signals.cpp:0:0
 #2 0x00000040092f3520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x0000004009347a7c __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #4 0x0000004009347a7c __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #5 0x0000004009347a7c pthread_kill ./nptl/pthread_kill.c:89:10
 #6 0x00000040092f3476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #7 0x00000040092d97f3 abort ./stdlib/abort.c:81:7
 #8 0x0000004004d7409e (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4d7409e)
 #9 0x0000004000a19be0 _ZNK4mlir12ElementsAttr11value_beginINS_9AttributeEEENSt9enable_ifIXoosrSt7is_sameIS2_T_E5valuentsrSt10is_base_ofIS2_S5_E5valueENS_6detail20ElementsAttrIteratorIS5_EEE4typeEv /workdir/llvm-project/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h:304:31
#10 0x0000004000a183cf _ZNK4mlir12ElementsAttr9getValuesINS_9AttributeEEENSt9enable_ifIXoosrSt7is_sameIS2_T_E5valuentsrSt10is_base_ofIS2_S5_E5valueENS_6detail17ElementsAttrRangeINS9_20ElementsAttrIteratorIS5_EEEEE4typeEv /workdir/llvm-project/build/tools/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h.inc:182:64
#11 0x0000004000a1c70f mlir::detail::ElementsAttrRange<llvm::mapped_iterator<mlir::detail::ElementsAttrIterator<mlir::Attribute>, mlir::IntegerAttr (*)(mlir::Attribute), decltype(declval<mlir::IntegerAttr (*)(mlir::Attribute)>()(declval<mlir::detail::ElementsAttrIterator<mlir::Attribute>>().mlir::detail::ElementsAttrIterator<mlir::Attribute>::operator*() const()))>> mlir::ElementsAttr::getValues<mlir::IntegerAttr, void>() const /workdir/llvm-project/build/tools/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h.inc:203:53
#12 0x0000004001c85f9d long (anonymous namespace)::getScalarValue<long>(mlir::ElementsAttr&, mlir::Type, unsigned long) /workdir/onnx-mlir/src/Dialect/Mlir/IndexExprBuilder.cpp:47:10
#13 0x0000004001c84b29 onnx_mlir::IndexExprBuilder::getValFromArray(mlir::Value, unsigned long, bool, bool) /workdir/onnx-mlir/src/Dialect/Mlir/IndexExprBuilder.cpp:181:45
#14 0x0000004001c84f7f onnx_mlir::IndexExprBuilder::getIntFromArrayAsSymbol(mlir::Value, unsigned long) /workdir/onnx-mlir/src/Dialect/Mlir/IndexExprBuilder.cpp:218:1
#15 0x0000004000ba5722 onnx_mlir::ONNXNonSpecificOpShapeHelper<mlir::ONNXReshapeOp>::computeShape() /workdir/onnx-mlir/src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp:59:29
#16 0x0000004000a21be1 onnx_mlir::ONNXOpShapeHelper::computeShapeAndUpdateType(mlir::Type, mlir::Attribute) /workdir/onnx-mlir/src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp:183:13
#17 0x0000004000ba60b8 mlir::ONNXReshapeOp::inferShapes(std::function<void (mlir::Region&)>) /workdir/onnx-mlir/src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp:127:47
#18 0x00000040006587ce mlir::detail::ShapeInferenceOpInterfaceInterfaceTraits::Model<mlir::ONNXReshapeOp>::inferShapes(mlir::detail::ShapeInferenceOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, std::function<void (mlir::Region&)>) /workdir/onnx-mlir/build/src/Interface/ShapeInferenceOpInterface.hpp.inc:59:67
#19 0x0000004001afb785 mlir::ShapeInferenceOpInterface::inferShapes(std::function<void (mlir::Region&)>) /workdir/onnx-mlir/build/src/Interface/ShapeInferenceOpInterface.cpp.inc:11:25
#20 0x0000004001af7f62 onnx_mlir::(anonymous namespace)::inferShapes(mlir::ShapeInferenceOpInterface, mlir::PatternRewriter&)::'lambda'()::operator()() const /workdir/onnx-mlir/src/Transform/ONNX/ShapeInference.cpp:73:51
#21 0x0000004001af8680 mlir::LogicalResult onnx_mlir::(anonymous namespace)::tryUpdateRootInPlace<onnx_mlir::(anonymous namespace)::inferShapes(mlir::ShapeInferenceOpInterface, mlir::PatternRewriter&)::'lambda'()>(mlir::Operation*, mlir::PatternRewriter&, onnx_mlir::(anonymous namespace)::inferShapes(mlir::ShapeInferenceOpInterface, mlir::PatternRewriter&)::'lambda'()&&) /workdir/onnx-mlir/src/Transform/ONNX/ShapeInference.cpp:57:13
#22 0x0000004001af814d onnx_mlir::(anonymous namespace)::inferShapes(mlir::ShapeInferenceOpInterface, mlir::PatternRewriter&) /workdir/onnx-mlir/src/Transform/ONNX/ShapeInference.cpp:82:1
#23 0x0000004001af8249 onnx_mlir::(anonymous namespace)::InferShapesPattern::matchAndRewrite(mlir::ShapeInferenceOpInterface, mlir::PatternRewriter&) const /workdir/onnx-mlir/src/Transform/ONNX/ShapeInference.cpp:112:23
#24 0x0000004001afb5f4 mlir::detail::OpOrInterfaceRewritePatternBase<mlir::ShapeInferenceOpInterface>::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const /workdir/llvm-project/mlir/include/mlir/IR/PatternMatch.h:331:3
#25 0x00000040029e59a8 mlir::PatternApplicator::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&, llvm::function_ref<bool (mlir::Pattern const&)>, llvm::function_ref<void (mlir::Pattern const&)>, llvm::function_ref<mlir::LogicalResult (mlir::Pattern const&)>) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x29e59a8)
#26 0x00000040029bf5ff (anonymous namespace)::GreedyPatternRewriteDriver::processWorklist() GreedyPatternRewriteDriver.cpp:0:0
#27 0x00000040029c42e4 mlir::applyPatternsAndFoldGreedily(mlir::Region&, mlir::FrozenRewritePatternSet const&, mlir::GreedyRewriteConfig) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x29c42e4)
#28 0x00000040010384b6 onnx_mlir::(anonymous namespace)::ShapeInferencePass::runOnOperation() /workdir/onnx-mlir/src/Transform/ONNX/ShapeInferencePass.cpp:77:41
#29 0x0000004004a8b589 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8b589)
#30 0x0000004004a8ba71 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8ba71)
#31 0x0000004004a8c446 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::'lambda'(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&)::operator()(mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool)::OpPMInfo&) const Pass.cpp:0:0
#32 0x0000004004a8ac15 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8ac15)
#33 0x0000004004a8b315 mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8b315)
#34 0x0000004004a8ba71 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8ba71)
#35 0x0000004004a8c2d4 mlir::PassManager::run(mlir::Operation*) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4a8c2d4)
#36 0x00000040011c3439 performActions(llvm::raw_ostream&, std::shared_ptr<llvm::SourceMgr> const&, mlir::MLIRContext*, mlir::MlirOptMainConfig const&) MlirOptMain.cpp:0:0
#37 0x00000040011c459c processBuffer(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::MlirOptMainConfig const&, mlir::DialectRegistry&, llvm::ThreadPool*) MlirOptMain.cpp:0:0
#38 0x00000040011c46fd mlir::LogicalResult llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>::callback_fn<mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&)::'lambda'(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>(long, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&) MlirOptMain.cpp:0:0
#39 0x0000004004d0a3b4 mlir::splitAndProcessBuffer(std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::function_ref<mlir::LogicalResult (std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, llvm::raw_ostream&)>, llvm::raw_ostream&, bool, bool) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x4d0a3b4)
#40 0x00000040011be1b4 mlir::MlirOptMain(llvm::raw_ostream&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, mlir::DialectRegistry&, mlir::MlirOptMainConfig const&) (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x11be1b4)
#41 0x0000004000401752 main /workdir/onnx-mlir/src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp:216:13
#42 0x00000040092dad90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#43 0x00000040092dae40 call_init ./csu/../csu/libc-start.c:128:20
#44 0x00000040092dae40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#45 0x00000040003ff625 _start (/workdir/onnx-mlir/build/Debug/bin/onnx-mlir-opt+0x3ff625)
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

### PR DESCRIPTION
**Pull request by sorenlassen**
changed IndexExprBuilder::getValFromArray(array, i, _, isFloat) to require array element type matches isFloat, and changed getScalarValue() to getFloatValue()/getIntValue() with support for DenseUI8ResourceElementsAttr (from ZHigh)

the lit tests surfaced an error in Range shape inference where we were incorrectly cast start/limit/delta to int64 before calculating the max(ceil((limit-start)/delta),0) dimension

fixes #2346

### CODE REVIEW

**Comment by sorenlassen** [comment]
@AlexandreEichenberger I made this change because @hamptonm1 encountered a crash in getScalarValue - I couldn't reproduce the crash but I think it will helpful to simplify the elementsAttr access in this way and then it will be easier to troubleshoot if we can reproduce the crash

**Comment by sorenlassen** [comment]
the commit https://github.com/onnx/onnx-mlir/pull/2347/commits/5615fcd482ce0db7d3b70e82300be80b806ae0bd
is intended as a fix or workaround for issue #2346

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for the worthy update

**Comment by sorenlassen** [comment]
@tungld in this PR I added getFloatValue()/getIntValue() in IndexExprBuilder.cpp to support DenseUI8ResourceElementsAttr (from ZHigh) but do you recommend that I don't do that? I see in issue #2346 you wrote "DenseResourceElementsAttr is used for encoded data for NNPA, it would be really wrong if it is passed to Reshape directly without any decoding"

**Comment by tungld** [comment]
> @tungld in this PR I added getFloatValue()/getIntValue() in IndexExprBuilder.cpp to support DenseUI8ResourceElementsAttr (from ZHigh) but do you recommend that I don't do that?

I think it's still worth supporting that because DenseResourceElementsAttr is an MLIR attribute and other dialects (perhaps in the future) will use it for normal/unencrypted data.

**Comment by hamptonm1** [comment]
@AlexandreEichenberger @sorenlassen We should have waited to merge this... I did not test on my end to confirm if this even resolves the issue at hand.

**Comment by sorenlassen** [comment]
> We should have waited to merge this... I did not test on my end to confirm if this even resolves the issue at hand.

I merged the PR because it should be an improvement in all cases but the way I linked them to the issues meant that they automatically closed issue #2346, which was a step too far until we confirmed that they fixed them, sorry about that - I have reopened it

**Pull request merged**
