### PR TITLE
Fix J9 crash

### PR DESCRIPTION
**Pull request by gongsu832**
- move jniapi into stack to avoid J9 crash, which apparently cannot share pointer returned by FindClass across threads
- make jnilog thread safe also

Signed-off-by: Gong Su <gong_su@hotmail.com>

### CODE REVIEW

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
@gongsu832 Is it ready to land? If so, I will update the to the latest and squash it this weekend

**Comment by gongsu832** [comment]
@AlexandreEichenberger Yes it's ready to be merged.

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Pull request merged**
