### PR TITLE
Remove Usage of Deprecated FunctionPass

### PR DESCRIPTION
**Pull request by manbearian**
Replace usage of FunctionPass with OperationPass<FuncOp> within ONNX-MLIR.

This change is motivated by the deprecation of FunctionPass as described here: https://llvm.discourse.group/t/functionpass-deprecated-in-favor-of-operationpass-funcop/5808

### CODE REVIEW

**Comment by etiotto** [comment]
@manbearian thanks for the contribution!  The changes look straightforward to me. I see there are some errors on the continuous integration bots, for example on Mac:
```
/Users/runner/work/onnx-mlir/onnx-mlir/src/Transform/EnableMemoryPool.cpp:197:21: error: use of undeclared identifier 'getFunction'
    auto function = getFunction();
```
could you take a look pls?

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Review by etiotto — APPROVED** [review]
LGTM

**Pull request merged**
