### PR TITLE
Krnl new pattern (all loops lb/ub defined at once)

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Change code pattern generation for Gemm/Matmul to follow the pattern suggested in issue #688

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@sstamenova The Window CI fails. Its probably an ordering thing, not sure. Is there a way to have a terminal in a Window machine with the right environment to test directly what is going on? I don't have a window machine that is recent. Thanks

**Comment by sstamenova** [comment]
> @sstamenova The Window CI fails. Its probably an ordering thing, not sure. Is there a way to have a terminal in a Window machine with the right environment to test directly what is going on? I don't have a window machine that is recent. Thanks

There's no way to connect to the machine, unfortunately. Since the failure is in the lit tests, I'm surprised it is only on Windows. Did the line endings change? Or maybe some characters that are not recognized on Windows?

**Comment by tungld** [comment]
Maybe the failure on Windows was because lit tests cannot split a lit test file correctly by recognizing `// -----`.

Correct way to use `// -----` is that it must be surrounded by empty lines.

I saw that some functions around `test_matmul2` did not have an empty line after `// -----`. @AlexandreEichenberger Could you add empty lines and try again?

**Comment by AlexandreEichenberger** [comment]
@tungld sadly that was not it.

**Comment by sstamenova** [comment]
> @tungld sadly that was not it.

I'll try locally and see if I can reproduce it. I already have a build so it should be fairly quick.

**Comment by sstamenova** [comment]
@AlexandreEichenberger I pulled your branch locally and the test failed in release (same as the pipeline). I noticed it had a crash stack, so I reran it in debug and it passed. Debug builds on Windows do some extra initialization, so this can make sense - especially since the error is an AV (C0000005). I was able to get the stack trace from a RelWithDebInfo build:

[fail.txt](https://github.com/onnx/onnx-mlir/files/7529747/fail.txt)

**Comment by AlexandreEichenberger** [comment]
@sstamenova So, just to double check: you are saying that onnx-mlir-opt crashed on the matmul1 example. So its not that the pattern generated not quite match, it is that onnx-mlir-opt crashed on that input and in release mode. 

Thanks for running the example, much appreciated

**Comment by sstamenova** [comment]
> @sstamenova So, just to double check: you are saying that onnx-mlir-opt crashed on the matmul1 example. So its not that the pattern generated not quite match, it is that onnx-mlir-opt crashed on that input and in release mode.
> 
> `AV (C0000005)` corresponds to a segfault?
> 
> Thanks for running the example, much appreciated.

Yes, onnx-mlir-opt crashed with the attached callstack (which is why the pattern didn't match). It crashes in release and relwithdebinfo but not debug. C0000005 is an access violation.

**Comment by AlexandreEichenberger** [comment]
@sstamenova I would have had a very hard time finding the issue without your error log. Big thanks. I was using a `ValueRange` when I should have used a SmallVector. Looks like it works now

**Comment by AlexandreEichenberger** [comment]
@tungld thanks also for your suggestions, much appreciated

**Review by tungld — APPROVED** [review]
LGTM.

**Pull request merged**
