### PR TITLE
Upgrade ONNX to v1.12.0

### PR DESCRIPTION
**Pull request by hamptonm1**
Here are the steps taken to upgrade ONNX version

1. Create my own branch
2. cd `third_party/onnx` and checkout commit `f7ee1ac`
3. set CMAKE_ARGS=-DONNX_USE_LITE_PROTO=ON
4. pip uninstall onnx (remove version 1.11.0)
5. pip install . (install version 1.12.0)
6. Update `gen_onnx_mlir.py` file with the correct version number.

### CODE REVIEW

**Comment by hamptonm1** [comment]
@chentong319 Please let me know if this looks good. I know you said after the PR is merged I should do this step:

`submodule update --init --recursive`

**Comment by hamptonm1** [comment]
FYI- @cjvolzka

**Comment by chentong319** [comment]
The build failed. I checked one output and found the first error is about 'gnuregex.h'. Did you successfully build the compiler locally? Try `make check-onnx-lit` and `make check-onnx-backend` before creating the PR.

**Comment by chentong319** [comment]
> @chentong319 Please let me know if this looks good. I know you said after the PR is merged I should do this step:
> 
> `submodule update --init --recursive`

This is needed for everyone after this PR is merge into main.

**Review by philass — COMMENTED** [review]
Hey @hamptonm1,

There is a bit more involved with getting this to work

You need to regenerate `onnx-mlir/src/Dialect/ONNX/ONNXOps.td.inc` by running `onnx-mlir/utils/gen_onnx_mlir.py --dry-run-onnx-ops`

You also need to regenerate  the `OpBuildTable.inc`.

**Comment by philass** [comment]
The op definitions are scraped from ONNX. So by upgrading the ONNX version you are changing and adding new ops to the `onnx-mlir` dialect. Thats why its important to generate these generated files.

**Comment by hamptonm1** [comment]
Thanks @philass for the feedback! Okay will follow those steps. I appreciate it :)

**Comment by hamptonm1** [comment]
> Hey @hamptonm1,
> 
> There is a bit more involved with getting this to work
> 
> You need to regenerate `onnx-mlir/src/Dialect/ONNX/ONNXOps.td.inc` by running `onnx-mlir/utils/gen_onnx_mlir.py --dry-run-onnx-ops`
> 
> You also need to regenerate the `OpBuildTable.inc`.

@philass Based on your feedback I did the following to regenerate `ONNXOps.td.in` and `OpBuildTable.inc`(I checked the version just as an added precaution). Let me know if I am missing anything else. Thanks! :

```
onnx-mlir/utils/gen_onnx_mlir.py --dry-run-onnx-ops
onnx-mlir/utils/gen_onnx_mlir.py --dry-run-op-build-table
onnx-mlir/utils/gen_onnx_mlir.py --check-operation-version
```

**Comment by chentong319** [comment]
Since the version_dict reman the same, the `ONNXOps.td.in` and `OpBuildTable.inc` is expected to be the same if you run `make OMONNXOpsIncTranslation`.  You can find the instruction in slide#12 of the document.

**Comment by hamptonm1** [comment]
> Since the version_dict reman the same, the `ONNXOps.td.in` and `OpBuildTable.inc` is expected to be the same if you run `make OMONNXOpsIncTranslation`. You can find the instruction in slide#12 of the document.

Okay... `onnx-mlir/utils/gen_onnx_mlir.py --dry-run-onnx-ops` did not give me any changes but I can talk with you about this offline.

**Review by chentong319 — APPROVED** [review]
Congratulations!
LGTM!

**Pull request merged**
