### PR TITLE
Add asserts for snprintf, sprintf, and vsnprintf

### PR DESCRIPTION
**Pull request by mikeessen**
Update code to add assert statements for  snprintf, sprintf, and vsnprintf

### CODE REVIEW

**Comment by mikeessen** [comment]
> You don't want to put a required statement inside `assert` because `assert` is a macro and the statement disappears in Release mode when `NDEBUG` is defined.

@gongsu832 Thanks for catching!

**Comment by AlexandreEichenberger** [comment]
@gongsu832 @mikeessen 

That leads to another question: are there assert that we want under the Release mode? E.g. if a `malloc` returns no data, don't we want to have the compiler stops? Same for here, if there was a malicious strings, would we want to know about it and abort?

**Comment by AlexandreEichenberger** [comment]
I did not find "assert that we would like to keep in the release mode". However some advocate to build release with asserts using ` -DLLVM_ENABLE_ASSERTIONS=true`.

**Review by AlexandreEichenberger — COMMENTED** [review]
LGTM

**Review by AlexandreEichenberger — APPROVED** [review]

**Pull request merged**
