### PR TITLE
Make initializedTensors a class member

### PR DESCRIPTION
**Pull request by gramalingam**
Change global variable "initializedTensors" into a  member variable of FrontendGenImpl.

The current implementation does not allow a user to translate multiple ONNX models into MLIR one after another (because the initializers of earlier translations are carried over to subsequent translations). So, cannot use a test-suite with multiple translations, one after another. This is a minimal fix to enable that.

### CODE REVIEW

**Comment by gramalingam** [comment]
Any feedback on this PR? It is a one-line change and should be easy to review, appreciate your help, thanks!

**Review by doru1004 — APPROVED** [review]
LGTM

**Comment by gramalingam** [comment]
Is this okay to merge now?

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
