### PR TITLE
Add support for dynamic Gather op (plus slight IndexExpr improvements)

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Added support for dynamic Gather, updated lit tests and enabled the dynamic backend tests.

I also simplified the implementation of IndexExprImpl by adding a Type instead of the numerous bits (affine, symbol, dim).

### CODE REVIEW

**Review by chentong319 — COMMENTED** [review]
If I remember correctly, your PR always contains lots of old commits and a large number of files changed. Is it really unavoidable?

**Comment by tjingrant** [comment]
@chentong319 my guess is that Alex does a lot of `git merge [some other branch]` during development, if you instead do `git merge [some other branch] --squash`, then there won't be tons of irrelevant commits.

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by AlexandreEichenberger** [comment]
I think there are problems with some work unrelated to this one. On Mac, here is the error that I can find:

```
2020-11-17T23:12:26.6468430Z opt -O3 -o /Users/runner/work/onnx-mlir/onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.bc /Users/runner/work/onnx-mlir/onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.unoptimized.bc
2020-11-17T23:12:26.6477690Z Command execution failed.
2020-11-17T23:12:26.6499000Z UNREACHABLE executed at /Users/runner/work/onnx-mlir/onnx-mlir/src/MainUtils.cpp:157!
2020-11-17T23:12:26.6511670Z /bin/sh: line 1:  6190 Abort trap: 6           ../../../../bin/onnx-mlir /Users/runner/work/onnx-mlir/onnx-mlir/build/test/unit/Runtime/DocExampleTest/add.onnx
2020-11-17T23:12:26.6521000Z make[2]: *** [test/unit/Runtime/DocExampleTest/add.so] Error 134
2020-11-17T23:12:26.6561840Z make[1]: *** [test/unit/Runtime/DocExampleTest/CMakeFiles/OMCopyAndRename.dir/all] Error 2
2020-11-17T23:12:26.6574380Z make: *** [all] Error 2
```

**Comment by AlexandreEichenberger** [comment]
on circleci, I get a failure in something that I did, but it runs on my machine just fine. Maybe I can try to reinstall everything from scratch?

```
******************** TEST 'Open Neural Network Frontend :: onnx/onnx_lowering_with_canonicalize.mlir' FAILED ********************
Script:
--
: 'RUN: at line 1';   /home/circleci/project/onnx-mlir/build/bin/onnx-mlir-opt --shape-inference --convert-onnx-to-krnl --canonicalize /home/circleci/project/onnx-mlir/test/mlir/onnx/onnx_lowering_with_canonicalize.mlir -split-input-file | /home/circleci/project/llvm-project/build/bin/FileCheck /home/circleci/project/onnx-mlir/test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
--
Exit Code: 1

Command Output (stderr):
--
/home/circleci/project/onnx-mlir/test/mlir/onnx/onnx_lowering_with_canonicalize.mlir:553:10: error: CHECK: expected string not found in input
//CHECK: [[CST_3_:%.+]] = constant 3 : index
         ^
<stdin>:461:2: note: scanning from here
 %0 = alloc() : memref<2x2x2xf32>
 ^
```

**Comment by doru1004** [comment]
If it's a lit test fail you should check to see where the change comes from, perhaps the test needs to be updated.

**Comment by doru1004** [comment]
You should update to latest master and fix the conflict. Perhaps that will solve the issues you are seeing.

**Comment by AlexandreEichenberger** [comment]
> @chentong319 my guess is that Alex does a lot of `git merge [some other branch]` during development, if you instead do `git merge [some other branch] --squash`, then there won't be tons of irrelevant commits.

So what command to you use when master changes and you want to merge the master changes? I do this:

```
git checkout master
git fetch --all
git merge upstream/master
git push origin master
git checkout XXX (my branch)
git merge master
```

you are suggesting I do a `git merge upstream/master --squash`

**Comment by AlexandreEichenberger** [comment]
Reworked the lit tests to use CHECK-DAG, using the modified script in #410

**Pull request merged**
