### PR TITLE
remove old non-pattern-based shape inference

### PR DESCRIPTION
**Pull request by sorenlassen**
The comments and logic removed in ShapeInferencePass.cpp are quite old and don't make 100% sense anymore.

Unless anybody protests within the next month I intend to merge this PR around June 18. By then hopefully we will have surfaced any issues with the new pattern based shape inference which became the default in PR #2240 which was merged today.

### CODE REVIEW

**Comment by hamptonm1** [comment]
> I am hesitating in remove the old code.

I agree, I think we should keep it until we resolve the onnx model failures.

**Comment by sorenlassen** [comment]
> > I am hesitating in remove the old code.
> 
> I agree, I think we should keep it until we resolve the onnx model failures.

OK to go ahead and remove the old code now? The comments and logic removed in ShapeInferencePass.cpp are quite old and don't make 100% sense anymore.

**Comment by AlexandreEichenberger** [comment]
@chentong319 please let us know if this is ok by you. 
If there is no consequences, I am in favor of removing unused passes

**Review by chentong319 — APPROVED** [review]
LGTM!

**Pull request merged**
