### PR TITLE
Update progress in SharingWork.md

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
updated the info and relocated it in an issue, as its much easier to edit.

@tungld @chentong319 @doru1004 @tjingrant 

Please update the "additional functionality" column (last one) as I think many are not accurate. I believe we don't support broadcast, but many are labeled as "M" (indicating Multicast is implemented). If that is the case, great. If it is not the case, then label it as "noM," meaning it needs multicast but it is not yet implemented.

Thanks

### CODE REVIEW

**Comment by tungld** [comment]
It is correct that we fully support bidirectional/unidirectional broadcasting as described in ONNX.

**Comment by AlexandreEichenberger** [comment]
@tung How about matmul and mul? Currently listed as unsupported?

**Comment by tungld** [comment]
They support broadcasting also. BTW, I would like to move ReduceL1, ReduceL2, ReduceLogSum, ReduceLogSumExp, and ReduceSumSquare to the supported operation table since they were implemented but I have no permission to edit the issue’s content.

**Comment by tungld** [comment]
In general, all binary elementwise ops will support bidirectional broadcasting because they use the same lowering template.

**Comment by AlexandreEichenberger** [comment]
oh, if you cannot edit, then I should put it back to a GitHub md... or is there a way to make anyone edit a specific issue entry

**Comment by AlexandreEichenberger** [comment]
ok, migrated the data back to the SharedWork.md to allow editing by anyone

**Pull request merged**
