### PR TITLE
Minor fixes - spelling, whitespace, warnings

### PR DESCRIPTION
**Pull request by sstamenova**
Several minor fixes: spelling mistakes and whitespace in a couple of different places.
Adding a default policy for CMP0077 to address a cmake warning with options and variables
Removing LLVM_BUILD_EXAMPLES from the scripts and instructions as it is not needed

Signed-off-by: Stella Stamenova <stilis@microsoft.com>

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@gongsu832 : Can you have a look at this one so it can be commited?

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by caoimhinuibrian** [comment]
@sstamenova you need to fix the conflicts here

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Pull request merged**
