### PR TITLE
Test DenseNet121.

### PR DESCRIPTION
**Pull request by tjingrant**

### CODE REVIEW

**Comment by tjingrant** [comment]
Posting my investigation here for record:

```
Temporary directory has been created at /var/folders/1n/n6cdfhkd1hndnfq93trnf0vm0000gn/T/tmprux3nydw
Verifying value of conv1_1
Verifying value of conv1/bn_1
Verifying value of OC2_DUMMY_0
Verifying value of conv1/bn_internal_1
Verifying value of OC2_DUMMY_1
Verifying value of conv1/bn_2
Verifying value of conv1/bn_3
Verifying value of pool1_1
Verifying value of conv2_1/x1/bn_1
Traceback (most recent call last):
  File "debug.py", line 112, in <module>
    main(**vars(args))
  File "debug.py", line 105, in main
    np.testing.assert_array_almost_equal(ref_outs[i], outs[i], decimal=5)
  File "/Users/tjin/opt/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1044, in assert_array_almost_equal
    precision=decimal)
  File "/Users/tjin/opt/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal to 5 decimals

Mismatched elements: 197564 / 200704 (98.4%)
Max absolute difference: 5.424176
Max relative difference: 59014.164
 x: array([[[[-0.3835 , -0.44144, -0.42341, ..., -0.42097, -0.42097,
          -0.5168 ],
         [-0.47822, -0.44666, -0.39166, ..., -0.13088, -0.33474,...
 y: array([[[[-0.3835 , -0.44144, -0.42341, ..., -0.42097, -0.42097,
          -0.5168 ],
         [-0.47822, -0.44666, -0.39166, ..., -0.13088, -0.33474,...
```

**Comment by tungld** [comment]
@tjingrant could you please check DenseNet again? I think it would work now.

**Comment by tjingrant** [comment]
@tungld Thanks! Do you know what was the reason this model test failed before?

**Comment by tungld** [comment]
@tjingrant I don't know the reason. Just happened to test it recently and found it worked.

**Comment by tjingrant** [comment]
@AlexandreEichenberger this patch is ready, please help review!

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
