### PR TITLE
Remove squeeze/unsqueeze pairs

### PR DESCRIPTION
**Pull request by tungld**
This patch adds DDR rules for removing squeeze/unsqueeze pairs.

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM.

When I think of the squeeze or unsqueezed operation, I believe we do lower them to copy operations. But when it comes to it, aside from possibly needing a different buffer because the live range of the squeezed vs original buffer may be different, a squeeze operation is really a no-op as the data in the unsqueezed or squeezed location are exactly at the same offset. Does this PR eliminate these operations as well?

**Comment by AlexandreEichenberger** [comment]
@tung, will squash this PR shortly, it would be great for you to add a response to my above question, thanks.

**Comment by tungld** [comment]
@AlexandreEichenberger 

> Does this PR eliminate these operations as well?

No, this PR only deals with the situation where we squeeze and then untsqueeze with the same axes. It means the input and output have the same shape.

To avoid data copy (e.g. in squeeze, untsqueeze, reshape), I plan to use `memref_reshape`(https://mlir.llvm.org/docs/Dialects/Standard/#stdmemref_reshape-memrefreshapeop) which finally becomes no-op I believe. What do you think?

**Comment by AlexandreEichenberger** [comment]
Yes, I think that would work, esp if the input parameter to squeeze is "dead" (meaning has no other uses)

**Pull request merged**
