### PR TITLE
Use LLVM_LIT_OUTPUT_DIR to find the path to lit

### PR DESCRIPTION
**Pull request by sstamenova**
Setting LLVM_DEFAULT_EXTERNAL_LIT only works on Linux as written, so on Windows LLVM_EXTERNAL_LIT has to be specified. Rather than trying to setup the correct path ourselves, let LLVM handle it by setting LLVM_LIT_OUTPUT_DIR instead.

This addresses part of https://github.com/onnx/onnx-mlir/issues/247

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
test this please

**Comment by sstamenova** [comment]
> test this please

We've tested this change on both Linux and Windows. Or do you mean something else?

**Comment by caoimhinuibrian** [comment]
sorry @sstamenova ... I was trying to get Jenkins to run, not commenting on your diligence in testing!

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Pull request merged**
