### PR TITLE
Handle custom ops without op_dialect_version_map entry

### PR DESCRIPTION
**Pull request by gramalingam**
A small fix to the recent addition of op_dialect_version_map to name ops with multiple versions. Custom ops may not have an entry in this map, and can be handled as before (without any renaming).

### CODE REVIEW

**Comment by chentong319** [comment]
@jenkins-droid test

**Comment by gramalingam** [comment]
Hi @chentong319 : any feedback on this? I assume that the CI failures are unrelated to this PR (as far as I can see)?

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Review by chentong319 — APPROVED** [review]
LGTM!

**Pull request merged**
