### PR TITLE
Update LLVM and stablehlo to latest green commit

### PR DESCRIPTION
**Pull request by hamptonm1**
I upgraded LLVM to commit: b2cdf3cc4c08729d0ff582d55e40793a20bbcdcc
I also upgrade stablehlo to commit: cb42882825af722cc108e0051f760ec670321ce7
https://github.com/openxla/stablehlo/pull/1890/files

The reason why I upgraded stablehlo is because there are recent updates with LLVM that stablehlo also pulled in, so we need both updates in order to avoid errors. 

**LLVM Update:**
In `TypeSupport.h` a new parameter was added about 3 weeks ago to include the `attribute names` in AbstractType -> https://github.com/llvm/llvm-project/commit/3dbac2c007c114a720300d2a4d79abe9ca1351e7

**stablehlo Update**
In stablehlo we needed to replace `mlir::DenseIntElementsAttr` with `mlir::DenseI64ArrayAttr`, except for in the case of `ConstantOp`, `mlir::DenseI64ArrayAttr` is not supported yet so instead I used  `mlir::DenseElementsAttr` to bypass errors -> https://github.com/openxla/stablehlo/pull/1887/files

### CODE REVIEW

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@ashay Hello!! I can use your expertise here :)
I am so close to building this PR successfully but I get this error only on Linux nodes when running the CI:


```
[ 65%] Linking CXX shared library ../../../../Release/lib/libStablehloPasses.so
CMakeFiles/obj.StablehloPasses.dir/StablehloInstrumentWithProbe.cpp.o: In function `std::unique_ptr<mlir::Dialect, std::default_delete<mlir::Dialect> > llvm::function_ref<std::unique_ptr<mlir::Dialect, std::default_delete<mlir::Dialect> > ()>::callback_fn<mlir::MLIRContext::getOrLoadDialect<mlir::stablehlo::interpreter::InterpreterDialect>()::{lambda()#1}>(long)':
StablehloInstrumentWithProbe.cpp:(.text._ZN4llvm12function_refIFSt10unique_ptrIN4mlir7DialectESt14default_deleteIS3_EEvEE11callback_fnIZNS2_11MLIRContext16getOrLoadDialectINS2_9stablehlo11interpreter18InterpreterDialectEEEPT_vEUlvE_EES6_l[_ZN4llvm12function_refIFSt10unique_ptrIN4mlir7DialectESt14default_deleteIS3_EEvEE11callback_fnIZNS2_11MLIRContext16getOrLoadDialectINS2_9stablehlo11interpreter18InterpreterDialectEEEPT_vEUlvE_EES6_l]+0x28): undefined reference to `mlir::stablehlo::interpreter::InterpreterDialect::InterpreterDialect(mlir::MLIRContext*)'
CMakeFiles/obj.StablehloPasses.dir/StablehloInstrumentWithProbe.cpp.o: In function `mlir::stablehlo::interpreter::ProbeOp mlir::OpBuilder::create<mlir::stablehlo::interpreter::ProbeOp, mlir::Value&, mlir::StringAttr>(mlir::Location, mlir::Value&, mlir::StringAttr&&)':
StablehloInstrumentWithProbe.cpp:(.text._ZN4mlir9OpBuilder6createINS_9stablehlo11interpreter7ProbeOpEJRNS_5ValueENS_10StringAttrEEEET_NS_8LocationEDpOT0_[_ZN4mlir9OpBuilder6createINS_9stablehlo11interpreter7ProbeOpEJRNS_5ValueENS_10StringAttrEEEET_NS_8LocationEDpOT0_]+0x80): undefined reference to `mlir::stablehlo::interpreter::ProbeOp::build(mlir::OpBuilder&, mlir::OperationState&, mlir::Value, mlir::StringAttr)'
StablehloInstrumentWithProbe.cpp:(.text._ZN4mlir9OpBuilder6createINS_9stablehlo11interpreter7ProbeOpEJRNS_5ValueENS_10StringAttrEEEET_NS_8LocationEDpOT0_[_ZN4mlir9OpBuilder6createINS_9stablehlo11interpreter7ProbeOpEJRNS_5ValueENS_10StringAttrEEEET_NS_8LocationEDpOT0_]+0xb0): undefined reference to `mlir::detail::TypeIDResolver<mlir::stablehlo::interpreter::ProbeOp, void>::id'
[ 65%] Building CXX object src/Accelerators/NNPA/Dialect/ZHigh/CMakeFiles/OMZHighOps.dir/ZHighOps/StickForGRU/StickForGRU.cpp.o
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/stablehlo/stablehlo/transforms/CMakeFiles/StablehloPasses.dir/build.make:152: Release/lib/libStablehloPasses.so.18git] Error 1
make[1]: *** [CMakeFiles/Makefile2:8396: third_party/stablehlo/stablehlo/transforms/CMakeFiles/StablehloPasses.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

Have you seen this before? Maybe I made a slight mistake with my edits. Let me know your thoughts please. Thanks again!

**Comment by ashay** [comment]
Hey @hamptonm1, this looks like a problem in the (upstream) Stablehlo build.  The `StablehloInstrumentWithProbePass::probeValue()` in StablehloInstrumentWithProbe.cpp, there's a reference to `interpreter::ProbeOp`, which is defined (through TableGen) in InterpreterOps.td.  Going by stablehlo/reference/CMakeLists.txt, the `interpreter::ProbeOp` symbol gets defined in the InterpreterOps library target, but this target is not added to the dependencies of the StablehloPasses passes, and so your build fails with an undefined reference error.

I'll submit a patch to Stablehlo (I hope that's the only issue), but you could try the change locally and see if that gets your build to pass.

**Comment by hamptonm1** [comment]
> Hey @hamptonm1, this looks like a problem in the (upstream) Stablehlo build. The `StablehloInstrumentWithProbePass::probeValue()` in StablehloInstrumentWithProbe.cpp, there's a reference to `interpreter::ProbeOp`, which is defined (through TableGen) in InterpreterOps.td. Going by stablehlo/reference/CMakeLists.txt, the `interpreter::ProbeOp` symbol gets defined in the InterpreterOps library target, but this target is not added to the dependencies of the StablehloPasses passes, and so your build fails with an undefined reference error.
> 
> I'll submit a patch to Stablehlo (I hope that's the only issue), but you could try the change locally and see if that gets your build to pass.

Ahhh thank you!!!

**Comment by ashay** [comment]
> Can you keep me posted with the upstream fix please?

Sorry for the delay.  I had to rebuild LLVM and StableHLO to make sure that my patch didn't cause any other problems.  Here's the PR to fix the problem: https://github.com/openxla/stablehlo/pull/1894.

**Comment by hamptonm1** [comment]
> > Can you keep me posted with the upstream fix please?
> 
> Sorry for the delay. I had to rebuild LLVM and StableHLO to make sure that my patch didn't cause any other problems. Here's the PR to fix the problem: [openxla/stablehlo#1894](https://github.com/openxla/stablehlo/pull/1894).

No worries! Thanks for the quick fix of adding the target! Once that is merged in, I will switch the commit I am using for stablehlo.

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@ashay Okay so now I get this error with your latest upstream fix: 

```

+ /var/lib/jenkins/workspace/ONNX-MLIR-Pipeline-Docker-Build@pr_2662/.buildbot/jenkins-verify-user-image.py
[2023-12-20 13:48:40][073] INFO: docker run --rm -u 111:117 -v /var/lib/jenkins/workspace/ONNX-MLIR-Pipeline-Docker-Build@pr_2662/mnist:/workdir/mnist onnxmlirczar/onnx-mlir:2662 --EmitLib /workdir/mnist/mnist.onnx
onnx-mlir: error while loading shared libraries: libInterpreterOps.so.18git: cannot open shared object file: No such file or directory
```

**Comment by ashay** [comment]
I see.  Can you try adding InterpreterOps to `STABLEHLO_LIBS` in src/Conversion/ONNXToStableHlo/CMakeLists.txt?

**Comment by hamptonm1** [comment]
> I see. Can you try adding InterpreterOps to `STABLEHLO_LIBS` in src/Conversion/ONNXToStableHlo/CMakeLists.txt?

Okay let me try now

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@ashay It finally passed! I had to add all targets mentioned in `stablehlo/reference/CMakeLists.txt` for this to work. Thanks for your help along the way! Please feel free to review when you have a free minute :)

**Comment by hamptonm1** [comment]
@Connor-XY I was able to get this to build successfully, please review given you have expertise in Stablehlo. Thanks!

**Review by ashay — APPROVED** [review]
Phew!  Glad it passed, but I'm sorry for the hassle of discovering and adding the required library targets to the install list one by one.  Your changes look good to me, but I'll defer to others in case they have any specific suggestions.

I'm not sure why the CI requires these files to be installed individually.  Maybe [this (stale) patch](https://github.com/openxla/stablehlo/pull/1831#pullrequestreview-1738555969) might allow us to specify the main library and let CMake figure out the dependencies, but I am not certain.  I'll try and get that patch merged soon so that we could lessen the chances of the kind of trial-and-error that you had to go through.

In any case, nice work, and thanks for seeing the problem through!

**Comment by Connor-XY** [comment]
Could we remove EXCLUDE_FROM_ALL so that we don't need to manually install the required libraries? https://github.com/onnx/onnx-mlir/blob/2b287731f6826e7fa38be3c4d22bc8f4db4145a4/CMakeLists.txt#L174

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks @hamptonm1 for a job well done.

**Comment by hamptonm1** [comment]
> Could we remove EXCLUDE_FROM_ALL so that we don't need to manually install the required libraries?
> 
> https://github.com/onnx/onnx-mlir/blob/2b287731f6826e7fa38be3c4d22bc8f4db4145a4/CMakeLists.txt#L174

@ashay Was there a reason why we have the `EXCLUDE_FROM_ALL` ? I just want to make sure before changing the value to false to include all libraries as @Connor-XY suggested.

**Comment by ashay** [comment]
> Was there a reason why we have the `EXCLUDE_FROM_ALL` ?

Sorry, I have no idea.  I simply updated the line from the previous MHLO-based build to point to StableHLO, so I don't think I am the original author of that line.

**Comment by hamptonm1** [comment]
> > Was there a reason why we have the `EXCLUDE_FROM_ALL` ?
> 
> Sorry, I have no idea. I simply updated the line from the previous MHLO-based build to point to StableHLO, so I don't think I am the original author of that line.

@Connor-XY I can test this out before updating and wait until the stakeholders come back from vacation before asking if we should remove this `EXCLUDE` or not. Thanks.

**Pull request merged**
