### PR TITLE
Update LLVM to 700997aef8c1

### PR DESCRIPTION
**Pull request by etiotto**
Updating LLVM to SHA `700997aef8c1` causes a number of build issues due to the following MLIR interface changes:
- https://reviews.llvm.org/D115728
- https://reviews.llvm.org/D113229
- https://reviews.llvm.org/D113881
- https://reviews.llvm.org/D116648
- https://reviews.llvm.org/D113956
- https://reviews.llvm.org/D114698

This patch modifies `onnx-mlir` to use LLVM  `700997aef8c1`.

Signed-off-by: Ettore Tiotto <etiotto@ca.ibm.com>

### CODE REVIEW

**Comment by etiotto** [comment]
The patch fixes the build issues. However a number of LIT test fails:
```
Failed Tests (16):
  Open Neural Network Frontend :: conversion/krnl_to_affine/matmul.mlir
  Open Neural Network Frontend :: krnl/krnl_category_mapper.mlir
  Open Neural Network Frontend :: krnl/reshape.mlir
  Open Neural Network Frontend :: onnx/onnx_bundle_memory_pool.mlir
  Open Neural Network Frontend :: onnx/onnx_location.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_category_mapper.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_depth_to_space_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_gru_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_lstm_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_nonmaxsuppression_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_range_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_rnn_op.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_space_to_depth.mlir
  Open Neural Network Frontend :: onnx/onnx_lowering_with_canonicalize.mlir
  Open Neural Network Frontend :: onnx/onnx_math_functions_lowering.mlir


Testing Time: 2.06s
  Unsupported:  3
  Passed     : 41
  Failed     : 16
```
 
 Looking at one of the failure:
 ```
 % /Users/etiotto@ca.ibm.com/Source/tmp/onnx/onnx-mlir/build/Debug/bin/onnx-mlir-opt --shape-inference --convert-onnx-to-krnl --convert-krnl-to-affine --convert-krnl-to-llvm /Users/etiotto@ca.ibm.com/Source/tmp/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir -split-input-file
module  {
}

within split at /Users/etiotto@ca.ibm.com/Source/tmp/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :4:8: error: failed to materialize conversion for result #0 of operation 'onnx.Reshape' that remained live after conversion
  %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<*xf32>
       ^
within split at /Users/etiotto@ca.ibm.com/Source/tmp/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :4:8: note: see current operation: %67 = "onnx.Reshape"(<<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<?x?x?x?xf32>
within split at /Users/etiotto@ca.ibm.com/Source/tmp/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :5:3: note: see existing live user here: return %42 : tensor<?x?x?x?xf32>
  "std.return"(%0) : (tensor<*xf32>) -> ()
  ^
  ```

**Comment by sstamenova** [comment]
We just merged to a newer llvm in our private repo and we have some of these issues resolved. Let me know if you'd like me to push some of the changes. We did use a slightly different commit though - 00e6869

**Comment by etiotto** [comment]
@sstamenova 

> We just merged to a newer llvm in our private repo and we have some of these issues resolved. Let me know if you'd like me to push some of the changes. We did use a slightly different commit though - 00e6869

@sstamenova have you guys found the LIT test issue I described at https://github.com/onnx/onnx-mlir/pull/1081#issuecomment-1006940244 ?  And if so do you have a fix ?

**Comment by sstamenova** [comment]
> > We just merged to a newer llvm in our private repo and we have some of these issues resolved. Let me know if you'd like me to push some of the changes. We did use a slightly different commit though - 00e6869
> 
> @sstamenova have you guys found the LIT test issue I described at [#1081 (comment)](https://github.com/onnx/onnx-mlir/pull/1081#issuecomment-1006940244) ? And if so do you have a fix ?

All of the lit tests are passing in our branch, but we haven't merged with latest onnx-mlir since before the holidays. So it could be that we updated differently or that something changed in upstream onnx-mlir that we haven't merged yet. Let me publish a branch to compare.

**Comment by sstamenova** [comment]
@etiotto : I think we need to merge main onnx-mlir into our branch before our changes can be useful here. Our last merge was before some significant changes, so unfortunately even though we have all the tests passing, we are too far behind. We'll work on a merge but it will take a couple of days.

**Comment by tungld** [comment]
@etiotto found this PR in LLVM https://github.com/llvm/llvm-project/commit/4070f305f9a0c488d7177754d77c0b367e8695bf. Not sure 100% it is related but something about "materialize conversion".

**Comment by etiotto** [comment]
@sstamenova thanks. I am also attempting to locate the LLVM commit that exposed the issue I found. @tungld thanks for the hint, I will determine whether that commit is the culprit.

**Comment by etiotto** [comment]
The last LLVM commit that works is `01b55f163a40 [NFC] Tidy up DialectConversion.cpp`, the next commit `015192c63415 [mlir:DialectConversion] Restructure how argument/target materializations get invoked` exposes the problem.

**Comment by etiotto** [comment]
https://reviews.llvm.org/D111620 changes the type conversion infrastructure in MLIR quite significantly and exposes several issues in our lit tests. Here is an example, consider the following test: 
```
func @test_reshape(%arg0 : tensor<?x10xf32>, %arg1 : tensor<4xi64>) -> tensor<*xf32> {
  %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<*xf32>
  "std.return"(%0) : (tensor<*xf32>) -> ()
```
During onnx to krnl dialect conversion `onnx.Reshape` is eventually replaced by a `memref.reinterpret_cast`:
```
Legalizing operation : 'onnx.Reshape'(0xf0b8d2b1a60) {
  %0 = "onnx.Reshape"(<<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<?x?x?x?xf32>

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'onnx.Reshape -> ()' {
    ** Insert  : 'arith.constant'(0xf0b8d290280)
   . . .
    ** Insert  : 'memref.reinterpret_cast'(0xf0b8d2137e0)
    ** Replace : 'onnx.Reshape'(0xf0b8d2b1a60)
```
Each operation inserted is then legalized, when it comes to `memref.reinterpret_cast` we have:
```
    Legalizing operation : 'memref.reinterpret_cast'(0xf0b8d2137e0) {
      %66 = "memref.reinterpret_cast"(%arg0, %50, %54, %58, %62, %65, %64, %62) {operand_segment_sizes = dense<[1, 0, 4, 3]> : vector<4xi32>, static_offsets = [0], static_sizes = [-1, -1, -1, -1], static_strides = [-9223372036854775808, -9223372036854775808, -9223372036854775808, 1]} : (memref<?x10xf32>, index, index, index, index, index, index, index) -> memref<?x?x?x?xf32>

    } -> SUCCESS : operation marked legal by the target
```
Note here that the result type of `memref.reinterpret_cast` is a memref. That result will feed the `std.return` operation. 
However that operation is not legalized because is already considered legal, no matter what is the type of its input (note that the std.return input type is a tensor):
```
//===-------------------------------------------===//
Legalizing operation : 'std.return'(0xf0b8d2da5e0) {
  "std.return"(%67) : (tensor<?x?x?x?xf32>) -> ()

} -> SUCCESS : operation marked legal by the target
//===-------------------------------------------===//
```
Because the result produced by `memref.reinterpret_cast` is a memref and the result consumed by `std.return` is a tensor we have a type mismatch, which is now detected with the following error message:
```
within split at /home/etiotto/Source/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :4:8: error: failed to materialize conversion for result #0 of operation 'onnx.Reshape' that remained live after conversion
  %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<*xf32>
       ^
within split at /home/etiotto/Source/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :4:8: note: see current operation: %67 = "onnx.Reshape"(<<UNKNOWN SSA VALUE>>, <<UNKNOWN SSA VALUE>>) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<?x?x?x?xf32>
within split at /home/etiotto/Source/onnx/onnx-mlir/test/mlir/krnl/reshape.mlir:3 offset :5:3: note: see existing live user here: return %42 : tensor<?x?x?x?xf32>
  "std.return"(%0) : (tensor<*xf32>) -> ()
```
The error msg is MLIR way to say that, after lowering `onnx.Reshape` its result feeds an operation (is live) that requires an input with a different type. 

The way to fix this problem is to consider `std.return` legal only if its input is not a tensor. So by adding this code (in FrontendToKrnlLoweringPass::runOnOperation()):
```
  target.addDynamicallyLegalOp<mlir::ReturnOp>([&](Operation *op) {
+    return llvm::none_of(op->getOperandTypes(),
+                         [](Type type) { return type.isa<TensorType>(); });
+  });
```

Recompiling and rerunning the test now produces: 
```
    //===-------------------------------------------===//
    Legalizing operation : 'memref.reinterpret_cast'(0xfff1edb37e0) {
      %66 = "memref.reinterpret_cast"(%arg0, %50, %54, %58, %62, %65, %64, %62) {operand_segment_sizes = dense<[1, 0, 4, 3]> : vector<4xi32>, static_offsets = [0], static_sizes = [-1, -1, -1, -1], static_strides =
 [-9223372036854775808, -9223372036854775808, -9223372036854775808, 1]} : (memref<?x10xf32>, index, index, index, index, index, index, index) -> memref<?x?x?x?xf32>

    } -> SUCCESS : operation marked legal by the target
    //===-------------------------------------------===//
  } -> SUCCESS : pattern applied successfully
} -> SUCCESS
//===-------------------------------------------===//

//===-------------------------------------------===//
Legalizing operation : 'std.return'(0xfff1ee7d200) {
  "std.return"(%67) : (tensor<?x?x?x?xf32>) -> ()

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'std.return -> ()' {

    //===-------------------------------------------===//
    Legalizing operation : 'std.return'(0xfff1ee7d200) {
      "std.return"(%66) : (memref<?x?x?x?xf32>) -> ()

    } -> SUCCESS : operation marked legal by the target
    //===-------------------------------------------===//
  } -> SUCCESS : pattern applied successfully
} -> SUCCESS
```
We now can 'see' that `std.return` is consider illegal and its legalization causes it to change its input and use the memref result produced by `memref.reinterpret_cast`.

**Comment by etiotto** [comment]
These 2 failures:
 ```
   Open Neural Network Frontend :: onnx/onnx_lowering_depth_to_space_op.mlir
   Open Neural Network Frontend :: onnx/onnx_lowering_space_to_depth.mlir
  ```
are caused by the generation of a `memfer.dimOp` where the input value has tensor type. That operation expects the input to have a MemRefType or an UnrankedMemRefType (see https://mlir.llvm.org/docs/Dialects/MemRef/#memrefdim-mlirmemrefdimop).  

The problem stems from the code in `[ONNXSpaceToDepthOpLowering|ONNXDepthToSpaceOpLowering]::matchAndRewrite` which incorrectly obtains the operator input directly from the operator itself rather than from the appropriate operator adaptor.

**Comment by etiotto** [comment]
The final lit test failure (`Open Neural Network Frontend :: onnx/onnx_lowering.mlir`) can be attributed to the following input:

```
  func private @t2(%arg0: tensor<i64>, %arg1: tensor<i1>, %arg2: tensor<1xi64>) -> tensor<1xi64> {
    %0 = "onnx.Loop"(%arg0, %arg1, %arg2) ( {
    ^bb0(%arg3: tensor<i64>, %arg4: tensor<i1>, %arg5: tensor<1xi64>):  // no predecessors
      %1 = "onnx.Identity"(%arg4) : (tensor<i1>) -> tensor<i1>
      %2 = "onnx.Identity"(%arg5) : (tensor<1xi64>) -> tensor<1xi64>
      onnx.Return %1, %2 : tensor<i1>, tensor<1xi64>
    }) : (tensor<i64>, tensor<i1>, tensor<1xi64>) -> tensor<1xi64>
    return %0 : tensor<1xi64>
  }
```

**Comment by etiotto** [comment]
This PR was closed unintentionally and cannot be reopen, so I will create a new one.

**Pull request closed without merging**
