### PR TITLE
Allow rank-3 onnx.ml.CategoryMapper

### PR DESCRIPTION
**Pull request by negiyas**
Since the Bidaf model in the model zoo (https://github.com/onnx/models/tree/main/text/machine_comprehension/bidirectional_attention_flow) uses CategoryMapper op with rank-3 input, and onnx-mlir can support the rank-3 CategoryMapper op naturally.
 
This PR includes simple removal of the input rank check part, and its lit tests.

### CODE REVIEW

**Comment by negiyas** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
LGTM. I believe you enable not only rank-3 but arbitrary rank. Can we make the numerical test TestCategoryMapper cover rank-3? And it seems TestCategoryMapper is not called by Jenkins CI:
```
Test project /workdir/onnx-mlir/build/test/numerical
      Start  1: TestConv
      Start  2: TestMatMul2D
      Start  3: TestMatMulBroadcast
      Start  4: TestGemm
      Start  5: TestLSTM
      Start  6: TestRNN
      Start  7: TestGRU
      Start  8: TestLoop
      Start  9: TestScan
      Start 10: TestElementwise
```

Could you enable TestCategoryMapper also? I am sorry for many requests. Thanks!

**Comment by negiyas** [comment]
> LGTM. I believe you enable not only rank-3 but arbitrary rank. Can we make the numerical test TestCategoryMapper cover rank-3? And it seems TestCategoryMapper is not called by Jenkins CI:

The latest TestCategoryMapper  (at test/backend-cpp/TestCategoryMapper.cpp)  in the main branch causes errors. (I am not sure why the test run with the previous onnx-mlir before... The situation might be different to the current one.)
According to my understanding, the situation to use string-type inputs should be the same to the bidaf model case reported in Issuehttps://github.com/onnx/onnx-mlir/issues/2164 .

If you agree with the following proposal, I will modify the numerical test for testing two connected onnx.CategoryMapper ops.
The first op gets integer inputs and generates string outputs, and the second op gets string inputs and generates integer outputs. Accordingly we need not to use string-type inputs and outputs for the model.

I am happy to hear your comments.

**Comment by negiyas** [comment]
> Looks good to me, and as an additional way, you can use a constant string as an input for CategoryMapper.

I have realized that TestCategoryMapper (at test/backend-cpp/TestCategoryMapper.cpp) is a very good test case to enable string input data, so that I am enabling string input data in this PR if the modification is enough small. (Otherwise I will create another PR for string input enablement.)

Since the impact to enable string input data, is larger, It may take time a little bit longer time.

**Comment by negiyas** [comment]
> Looks good to me, and as an additional way, you can use a constant string as an input for CategoryMapper.

I fixed an issue in src/Dialect/ONNX/ONNXOps/OpHelper.cpp to enable string type in the mlirTypeToOnnxType function.
and supported rank2 and rank3 inputs tests in test/backend-cpp/TestCategoryMapper.cpp .

I will enable ./build/Debug/bin/TestCategoryMapper to the Jenkins test.

**Comment by negiyas** [comment]
I confirmed that /build/Debug/bin/TestCategoryMapper run in the Jenkins test.
I suppose(hope) that this PR is ready to be merged, if it passes all tests.

**Review by tungld — APPROVED** [review]
LGTM. Please do check the errors on Windows. Thanks!

**Pull request merged**
