### PR TITLE
Support dynamic shapes for `onnx.Matmul` in `stablehlo` conversion

### PR DESCRIPTION
**Pull request by srcarroll**

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@Connor-XY could you help take a look at this patch, if you don't mind? thanks.

**Review by Connor-XY — APPROVED** [review]
LGTM! Thanks for adding support for dynamic shapes for `onnx.Mul`.

**Comment by srcarroll** [comment]
Thanks for the review! This is my first time contributing to this project so I don't think I have rights to merge.  Unless it just gets merged automatically after approval?

**Comment by tungld** [comment]
@Connor-XY thanks for reviewing the patch!

@srcarroll congrats on the first contribution. Looking forwarding to your next patches! Thanks!

**Review by tungld — APPROVED** [review]
LGTM.

**Pull request merged**
