### PR TITLE
[DOC] Fix broken links to onnx.ai

### PR DESCRIPTION
**Pull request by najann**
no code changes, only minor corrections of the MNIST example ReadMe

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
This look like worthwhile, any reason it was closed?

**Comment by najann** [comment]
I hoped I could add changes to the ReadMe without having to rebuild the whole project but the automatic checks indicated something different. Currently, I don't have the time to follow the whole build-setup locally for these minor changes. That's why I closed it again. Maybe someone who's building the project anyway could copy my changes ? ;)

**Comment by AlexandreEichenberger** [comment]
Not sure I understand, we runs our CIs and you don't have to run it locally. You can ask us to run them as you initially don't have the permission.

I will reopen it and push it through #1667

**Comment by AlexandreEichenberger** [comment]
Thanks for finding the broken links, much appreciated

**Pull request closed without merging**
