### PR TITLE
Allow unregistered dialects when lowering to Krnl

### PR DESCRIPTION
**Pull request by doru1004**
This patch enables dialects which are not ONNX to flow through when lowering ONNX to Krnl.

### CODE REVIEW

**Comment by tjingrant** [comment]
@doru1004 according to you this patch is no longer necessary? Do we still want to merge it?

**Comment by AlexandreEichenberger** [comment]
@doru1004 is this patch still needed? more changes coming along?

**Comment by AlexandreEichenberger** [comment]
@doru1004 ping

**Comment by doru1004** [comment]
Not needed anymore I'll close it.

**Pull request closed without merging**
