### PR TITLE
Output better error messages for file opening errors instead of fatal errors by assertion.

### PR DESCRIPTION
**Pull request by negiyas**
This PR generates better error messages for the following cases.

**invalid input file name case (file name should be ending with onnx or mlir)**
```
/home/negishi/src/dlc.git/onnx-mlir/build/Debug/bin/onnx-mlir afoafo.afo
Invaid input file'afoafo.afo': Either ONNX model or MLIR file needs to be provided.
/home/negishi/src/dlc.git/onnx-mlir/build/Debug/bin/onnx-mlir-opt afoafo.afo
cannot open input file 'afoafo.afo': No such file or directory
```
**invalid input file case (cannot open the specified file)**
```
/home/negishi/src/dlc.git/onnx-mlir/build/Debug/bin/onnx-mlir afoafo.onnx
Onnx Model Parsing Failed on afoafo.onnx
/home/negishi/src/dlc.git/onnx-mlir/build/Debug/bin/onnx-mlir-opt afoafo.onnx
cannot open input file 'afoafo.onnx': No such file or directory```

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for setting up the infrastructure for better error messages.

**Comment by AlexandreEichenberger** [comment]
@negiyas Please squash and merge when the PR is complete, or let me know if it is and I can do it as well. Thanks for contributing to onnx-mlir

**Comment by tungld** [comment]
@negiyas please fix DCO. Thanks!

**Comment by negiyas** [comment]
done. Thank you!

**Pull request merged**
