### PR TITLE
allow pass manager options

### PR DESCRIPTION
**Pull request by caoimhinuibrian**
Signed-off-by: Kevin O'Brien <caomhin@us.ibm.com>

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
For debugging, its useful to be able to see the IR after each pass. This PR enables taht.

**Comment by tjingrant** [comment]
Hi Kevin, the `onnx-mlilr` executable was conceptualized to be a simple user-facing frontend, that's why it contains a short help message description (https://github.com/onnx/onnx-mlir#using-onnx-mlir). I suspect this patch may obfuscate that concise help message.

OTOH, I feel like the proper thing to do may be to register our usual compiler pass pipelines in `onnx-mlir-opt`, which is supposed to be an `onnx-mlir` debugger, although I understand that as we amass more compiler passes, it is increasingly impossible to type out all the passes executed by our main compiler frontend as command-line options, therefore the need to register them as pass pipelines mentioned earlier. 

OTOH again, if you still think this is the right thing to do, maybe we should think instead about merging `onnx-mlir` and `onnx-mlir-opt` into one, given this patch will make two utilities overlap more in functionalities.

**Comment by chentong319** [comment]
I assume that this change is to enable all the pass related flags defined in mlir for onnx-mlir.  The flags include IR printing, timing, statistic and crash reproducer. They are the debug flags provided by MLIR.  I tried to use them once and the flags did not work. I will be glad to have these flags enabled. 
As for Tian's concern about the interface, I think we will not, and should not, put these flags in our command line document. We just add a link to MLIR and say onnx-mlir accepts them.  It is part of MLIR functionalities.

**Comment by caoimhinuibrian** [comment]
@tjingrant The way I see it, onnx-mlir-opt is usefule for running one or two passes, maybe starting from an intermediate stage in the compile process. This is certainly a good tool to have, and I don't think we should eliminate it. The other use-case is running the complete compile (or running from ONNX input up to some desired point), this is what onnx-mlir does. When running like this and trying to find a problem in the series of transformations, it is useful (actually necessary) to be able to print out the IR after all or some subset of passes so that one can inspect it to find erroneous transformations.

I don't know how to eliminate the extra output from the --help flag, which I agree is problematic.

Somewhat tangentially, I think this is what @CHUNERnubi is asking for in issue #506 .

**Comment by caoimhinuibrian** [comment]
@tjingrant Maybe another solution would be to have onnx-mlir write out a pipeline description file which onnx-mlir-opt could then read in.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, @caoimhinuibrian I let you decide if it is still your preferred way to solve this.

**Pull request merged**
