### PR TITLE
Fix Warning from External Header

### PR DESCRIPTION
**Pull request by manbearian**
Disable warnings around inclusion of ONNX header.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by manbearian** [comment]
Looks like network issue:
> ERROR: Exception: java.io.IOException: Could not perform submodule update
Finished: FAILURE

@sstamenova would you mind restarting the failed test?

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, @etiotto is it ok with you too?

**Review by etiotto — APPROVED** [review]
LGTM

**Pull request merged**
