### PR TITLE
[cmake] Support generating onnx-mlir with mlir

### PR DESCRIPTION
**Pull request by NathanielMcVicar**
Changes required to support use cases where onnx-mlir and llvm-project/mlir are generated together.

### CODE REVIEW

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Review by sstamenova — APPROVED** [review]

**Comment by NathanielMcVicar** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Pull request merged**
