### PR TITLE
Set the pattern-shape-inference to false

### PR DESCRIPTION
**Pull request by hamptonm1**
@cjvolzka and @negiyas ran into the following issues when trying to compile models that worked well before:

```
podman run --workdir=/workdir --rm -it -v .:/workdir:z -u 1024:1024 --userns=keep-id onnxmlirczar/onnx-mlir:latest -o ccf_220_lstm_keras_static_Z.NNPA.onnx-mlir --O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA ccf_220_lstm_keras_static_Z.onnx --onnx-op-stats TXT

onnx-mlir: /workdir/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From&) [with To = mlir::ShapedType; From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```
```
$ ./build/Debug/bin/onnx-mlir -mcpu=z14 --EmitONNXIR  bidaf-9-nocategorymaper-onnxbasic.mlir
onnx-mlir: /home1/negishi/src/dlc.git/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From&) [with To = mlir::RankedTensorType; From = mlir::Type]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
./compile-bidaf9.sh: line 76: 642957 Aborted                 (core dumped) /home1/negishi/src/dlc.git/onnx-mlir.main/build/Debug/bin/onnx-mlir -mcpu=z14 --EmitONNXIR bidaf-9-nocategorymaper-onnxbasic.mlir
```

After debugging, I realized the problem is not from `LLVM` because no code changes have been made to line 566 in Casting.h. So I knew it was a change that was made recently within `onnx-mlir`. @tungld pointed me to this PR https://github.com/onnx/onnx-mlir/pull/2240/files and when I reverted the update, I was able to compile the onnx models and I no longer see this `Casting` error.

### CODE REVIEW

**Comment by hamptonm1** [comment]
@cjvolzka and @negiyas Can you test that this PR resolves the issue?

**Comment by hamptonm1** [comment]
I also changed the commit to use the LLVM green commit for consistence and to avoid any potential issues until the next upgrade.

**Comment by hamptonm1** [comment]
Note: The plan was to also change the LLVM commit to use the green commit but I get an error that the commit is "out of date" which makes sense given a new one will be utilized for Monday.

**Comment by negiyas** [comment]
> @cjvolzka and @negiyas Can you test that this PR resolves the issue?
@hamptonm1 I have confirmed that my issue has been solved by the "--pattern-shape-inference=false" option. Thanks.

**Comment by sorenlassen** [comment]
can I access `ccf_220_lstm_keras_static_Z.onnx` so I can study this failure?

**Comment by hamptonm1** [comment]
> can I access `ccf_220_lstm_keras_static_Z.onnx` or `bidaf-9-nocategorymaper-onnxbasic` so I can study this failure?

Sure left me send it to you :)

**Comment by hamptonm1** [comment]
> @cjvolzka and @negiyas Can you test that this PR resolves the issue?
> @hamptonm1 I have confirmed that my issue has been solved by the "--pattern-shape-inference=false" option. Thanks.

Thank you @negiyas !

**Review by sorenlassen — APPROVED** [review]
we don't want pattern-based shape inference to break anything, so I support that we roll back this change from PR #2240

but I'm eager to replace the old, strange shape inference so any help troubleshooting why pattern-based shape inference fails in these cases would be appreciated

**Comment by hamptonm1** [comment]
> we don't want pattern-based shape inference to break anything, so I support that we roll back this change from PR #2240
> 
> but I'm eager to replace the old, strange shape inference so any help troubleshooting why pattern-based shape inference fails in these cases would be appreciated

I agree!

**Comment by tungld** [comment]
> can I access ccf_220_lstm_keras_static_Z.onnx or bidaf-9-nocategorymaper-onnxbasic so I can study this failure?

Perhaps, you can use this public one: https://github.com/IBM/ai-on-z-fraud-detection/tree/main/onnx%20models
But not 100% sure it can reproduce the issue.

**Comment by hamptonm1** [comment]
> > can I access ccf_220_lstm_keras_static_Z.onnx or bidaf-9-nocategorymaper-onnxbasic so I can study this failure?
> 
> Perhaps, you can use this public one: https://github.com/IBM/ai-on-z-fraud-detection/tree/main/onnx%20models But not 100% sure it can reproduce the issue.

@tungld I sent @sorenlassen the models via slack already.

**Pull request merged**
