### PR TITLE
[MHLO] Lowers PadOp (constant mode) & GatherElements Op to MHLO

### PR DESCRIPTION
**Pull request by chenchongsong**
This pull request lowers the following ops to MHLO:

1. Pad op with mode as 'constant'
2. GatherElements op

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
FYI, on Windows, they treat many warnings as errors. This might be a simple fix... from the error logs
```
D:\a\1\onnx-mlir\third_party\mlir-hlo\stablehlo\stablehlo\dialect\Base.cpp(392): warning C4927: illegal conversion; more than one user-defined conversion has been implicitly applied
D:\a\1\onnx-mlir\third_party\mlir-hlo\stablehlo\stablehlo\dialect\Base.cpp(392): note: while calling the constructor 'mlir::FailureOr<mlir::ShapedType>::FailureOr(T &&)'
        with
        [
            T=mlir::ShapedType
        ]
```

**Comment by AlexandreEichenberger** [comment]
@chenchongsong I believe the error should be an easy one to fix.

**Comment by AlexandreEichenberger** [comment]
Should this PR be closed because functionality has been taken over by #2602?

**Comment by Connor-XY** [comment]
> Should this PR be closed because functionality has been taken over by #2602?

@AlexandreEichenberger Yes, please close this if possible. Chongsong is away and may not be able to close it promptly.

**Pull request closed without merging**
