### PR TITLE
Make MHLO Optional

### PR DESCRIPTION
**Pull request by sstamenova**
After this change, MHLO can be excluded by setting `ONNX_MLIR_ENABLE_MHLO` to `OFF`. The default remains set to `ON`, so MHLO will continue to be included.

Signed-off-by: Stella Stamenova <stilis@microsoft.com>

### CODE REVIEW

**Comment by sstamenova** [comment]
@Connor-XY @yaochengji I made this change since it makes sense to make it optional sooner rather than later. The change in #1611 was not complete to make it optional, so I had to add several more things to what you had started with, but it should be fairly easy to merge.

**Comment by gongsu832** [comment]
@sstamenova You are directly pushing branches into the onnx-mlir repo. This is discouraged as it pollutes the onnx-mlir repo. You should fork your own repo and submit PRs from the fork. Thanks.

**Comment by sstamenova** [comment]
> @sstamenova You are directly pushing branches into the onnx-mlir repo. This is discouraged as it pollutes the onnx-mlir repo. You should fork your own repo and submit PRs from the fork. Thanks.

@gongsu832 I'll leave this branch because I want to complete this PR but I removed the other two. I assumed this was fine since there are quite a few branches already, but I'll make sure not to do that in the future.

**Comment by gongsu832** [comment]
That's fine. Thanks.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
