### PR TITLE
Switch from docker.io to ghcr.io

### PR DESCRIPTION
**Pull request by gongsu832**
Switch from docker.io to ghcr.io due to company policy change.

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by AlexandreEichenberger** [comment]
@gongsu832 Thanks for doing this and updating the doc accordingly.

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by onnxmlir** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Comment by gongsu832** [comment]
@jenkins-droid publish this please

**Review by hamptonm1 — APPROVED** [review]
LGTM!

**Pull request merged**
