### PR TITLE
Fix JNI wrapper warning on long vs int64_t

### PR DESCRIPTION
**Pull request by gongsu832**
Signed-off-by: Gong Su <gong_su@hotmail.com>

### CODE REVIEW

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for the quick turn around

**Comment by gongsu832** [comment]
@chentong319 Build is failing on Windows:
```
D:\a\1\onnx-mlir\src\Runtime\OMInstrument.inc(39,10): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory (compiling source file D:\a\1\onnx-mlir\src\Runtime\OMInstrument.c) [D:\a\1\onnx-mlir\build\src\Runtime\cruntime.vcxproj]
```
I think this is due to https://github.com/onnx/onnx-mlir/pull/750 being merged before passing CI on Windows.

**Comment by AlexandreEichenberger** [comment]
>I think this is due to #750 being merged before passing CI on Windows. 

Correct, I opened an issue on this: #774 @chentong319 is aware and working on a fix. So we can commit this one

**Pull request merged**
