### PR TITLE
Relax the type requirement for special builder

### PR DESCRIPTION
**Pull request by chentong319**
This is a simple change,
The previous special builder added in ONNXOps.td.inc has a static type cast, which will cause error if the operands are not the expected type. This type cast is not necessary: the function, getBroadcastedType, which uses the type, checks the type dynamically. And the builder has the code to handle shape unknown case.
Therefore, I removed the static type cast so that the builder can be used to rewrite operations with unknown shape. 
By the way, I am not in favor of that we mix the builder with shape inference and the getBroadcastedType is not needed. I think that ShapeInference pass has to been invoked after rewriting.

### CODE REVIEW

**Comment by tjingrant** [comment]
@tungld could you also take a look to see if this typecast is okay to drop?

**Comment by chentong319** [comment]
The GetBroadcastedType serve as TypeInference when the shape is unknown. It should be kept until we have a way to call our type inference inside builder. Working on a trait function (like GetBroadcastedType) for type inference.

**Comment by tungld** [comment]
It is reasonable to remove the type case since `getBroadcastedType` can handle unranked tensor. It seems such builders are used in cases of constant propagation. @AlexandreEichenberger may have a better answer for this.

For general rewriting, that builder just returns an unknown shape and let ShapeInference do its job looks easy to manage. Meanwhile, calling type inference inside builder looks good if we do folding in a single pass where we have no chance to call shape inference, e.g. constant folding. It's great if we could unify the two approaches.

**Comment by chentong319** [comment]
@tungld Thanks for pointing out the case of constant folding, which is an interesting topic on how to combine passes in MLIR.

**Comment by AlexandreEichenberger** [comment]
For constant folding, I needed operations that folded to have as precise a type as possible, as often we need to apply multiple substitution until we have the right situation to fold two constant tensors together.

In addition, folding or not, arranging the associativity of ops cognizant of broadcast rules can be advantageous... ie keep smallest dimension as long as possible as this result in less computations.

Since there are lit tests with the folding, I assume that Tong's patch had no negative impact on it.

**Comment by chentong319** [comment]
This patch will not change anything if the input is a ranked tensor. The change is to remove the requirement that the input has to be a ranked tensor.

**Pull request merged**
