### PR TITLE
build: update LLVM tag to ec89cb9a

### PR DESCRIPTION
**Pull request by ashay**
Also updates MHLO submodule to commit cd47c8c4.

### CODE REVIEW

**Comment by sorenlassen** [comment]
@jenkins-droid test this please

**Comment by ashay** [comment]
Soren, thanks for merging the main branch and starting the builds!

**Review by sorenlassen — APPROVED** [review]
LGTM

**Comment by ashay** [comment]
@sorenlassen Could you merge the PR please?  I don't have commit access.

**Comment by sorenlassen** [comment]
@jenkins-droid test this please

**Comment by sorenlassen** [comment]
> @sorenlassen Could you merge the PR please? I don't have commit access.

yes, will do

**Pull request merged**
