### PR TITLE
Generate Opset 17 ops

### PR DESCRIPTION
**Pull request by philass**
Signed-off-by: Philip Lassen <plassen@groq.com>

### CODE REVIEW

**Comment by sorenlassen** [comment]
LGTM, please just update SupportedONNXOps-cpu.md

**Review by AlexandreEichenberger — APPROVED** [review]

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by hamptonm1** [comment]
> LGTM, please just update SupportedONNXOps-cpu.md

@mikeessen Was going to update ` SupportedONNXOps-cpu.md` (not sure if @philass started this already) :)

**Comment by mikeessen** [comment]
> > LGTM, please just update SupportedONNXOps-cpu.md
> 
> @mikeessen Was going to update ` SupportedONNXOps-cpu.md` (not sure if @philass started this already) :)

@philass  I will update SupportedONNXOps-cpu.md in a separate PR after you merge this PR.

**Comment by chentong319** [comment]
@philass Could you resolve the conflict so that the PR can be merged?

**Comment by philass** [comment]
@mikeessen  sorry for not responding sooner. Thanks for doing that.

@chentong319 I've resolved the conflicts.

**Pull request merged**
