### PR TITLE
Fix a bug in NonMaxSuppression

### PR DESCRIPTION
**Pull request by tungld**
This patch is to fix the issue #1035 where the position of getting the largest box index was wrong.

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@gongsu832 could you please help with Jenkins Linux ppc64le? I see it failed with 

```requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8080/jenkinp/computer/Built-In%20Node/api/json?depth=2```

I tried to restart the Jenkins test several times, but it still failed.

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by gongsu832** [comment]
Latest Jenkins update to move away from using the master word broke the python-jenkins package. I have to rallback for now until python-jenkins is updated. ppc64le build should work now.

**Comment by tungld** [comment]
> Latest Jenkins update to move away from using the master word broke the python-jenkins package. I have to rallback for now until python-jenkins is updated. ppc64le build should work now.

Thank you so much for a quick fix!

**Review by etiotto — APPROVED** [review]
LGTM.

**Pull request merged**
