### PR TITLE
Cleanup various flags in CMakeLists.txt

### PR DESCRIPTION
**Pull request by sstamenova**
HandleLLVMOptions allows us to cleanup several of the flags that are being set explicitly in onnx-mlir. In addition, this change sets the policy for CMP0116 to match llvm-project.

This change depends on #718

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by sstamenova** [comment]
> @jenkins-droid test this please

@caoimhinuibrian : I expect the builds for this change and the runtime change to fail until the HandleLLVMOptions PR is merged.

**Comment by caoimhinuibrian** [comment]
> > @jenkins-droid test this please
> 
> @caoimhinuibrian : I expect the builds for this change and the runtime change to fail until the HandleLLVMOptions PR is merged.

@sstamenova ok, cool

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Pull request merged**
