### PR TITLE
Use DimAnalysis when lowering ONNXReshape to krnl

### PR DESCRIPTION
**Pull request by tungld**
This patch is to use DimAnalysis when lowering ONNXReshape. In particular, DimAnalysis is used to detect "identity" reshape, so that we can remove reshape.

### CODE REVIEW

**Review by AlexandreEichenberger — COMMENTED** [review]
Smart. 

Quick question about where to have this optimization. If we had this as a onnx-to-onnx optimization, wouldn't we have better shape inference, because this to-be-removed reshape would not cloud the shape inference analysis?

**Comment by tungld** [comment]
> If we had this as a onnx-to-onnx optimization, wouldn't we have better shape inference, because this to-be-removed reshape would not cloud the shape inference analysis?

Absolutely, I intended to do so, and we might need to have a separate onnx-to-onnx pass that utilizes DimAnalysis. Currently, onnx-to-onnx is done via canonicalization of each op, but I haven't found a way to use DimAnalaysis in canonicalization pattern. Anyway, using DimAnalysis in onnx-to-krnl is orthogonal to using it in onnx-to-onnx, so I make a change in onnx-to-krnl first.

**Review by AlexandreEichenberger — APPROVED** [review]
Sure, I buy this. Maybe open an issue for the onnx-to-onnx pass, with a note that if the case solved here if caught earlier, maybe the code here can then be omitted.

**Comment by tungld** [comment]
> Maybe open an issue for the onnx-to-onnx pass, with a note that if the case solved here if caught earlier, maybe the code here can then be omitted.

Yes, created an issue #2437

**Pull request merged**
