### PR TITLE
[WIP] Make krnl.getref compatiable with affine ops

### PR DESCRIPTION
**Pull request by tungld**
Currently, if we enabled `affine-loop-fusion` pass, we would get an error saying 
```bash
/home/tungld/dl/llvm-project/mlir/lib/Dialect/Affine/IR/AffineOps.cpp:482: mlir::AffineMap promoteComposedSymbolsAsDims(mlir::AffineMap, llvm::ArrayRef<mlir::Value>): Assertion `isValidSymbol(sym) && "Expected only valid symbols"' failed.
```

This was because the return value of `krnl.getref` was invalid to be used in the pass.

According to AffineOps.cpp (https://github.com/llvm/llvm-project/blob/master/mlir/lib/Dialect/Affine/IR/AffineOps.cpp#L224), conditions for a valid value are:
>// A value can be used as a symbol (at all its use sites) iff it meets one of
// the following conditions:
// *) It is a constant.
// *) Its defining op or block arg appearance is immediately enclosed by an op
//    with `AffineScope` trait.
// *) It is the result of an affine.apply operation with symbol operands.
// *) It is a result of the dim op on a memref whose corresponding size is a
//    valid symbol.

This patch is to make the `krnl.getref`'s return value valid by adding `AffineScope` trait into `getref`'s definition.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@doru1004 do you want to look into this one? Tx

**Comment by doru1004** [comment]
Are there any changes to the output code so that we can write a test for this change?

**Comment by tungld** [comment]
Let me mark this as WIP to investigate further whether `getref` is really related to the error.

**Comment by tungld** [comment]
Close and create an issue for this #179

**Pull request closed without merging**
