### PR TITLE
Keep model zoo check history for the past 100 merges

### PR DESCRIPTION
**Pull request by gongsu832**
Signed-off-by: Gong Su <gong_su@hotmail.com>

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Comment by gongsu832** [comment]
@jenkins-droid test that please

**Review by tungld — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
