### PR TITLE
Add check for malloc to prevent NULL pointer dereference in docs example.

### PR DESCRIPTION
**Pull request by Sunny-Anand**
This PR updates the code to check the result of memory allocation for input data tensors in doc example.

### CODE REVIEW

**Comment by gongsu832** [comment]
`assert` is for catching bugs, something logically impossible to happen with your code's internal state. For example, you have a loop variable to control the termination of a loop. In the loop body you may change the variable according to various conditions. But by your design, you know that the variable should never exceed some value **no matter how other parts of the code work**. So you can use `assert(v <= maxval)` to catch potential bugs in your own code that changes the variable.

`malloc` returning null is not a bug. It's a perfectly normal condition that can happen when the system is running out of memory. In addition, `assert` goes away in release mode when NDEBUG is defined so your code will not check the returned pointer (when it still should).

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks

**Comment by AlexandreEichenberger** [comment]
@gongsu832 We recently enabled asserts in the release mode too, just like the LLVM release mode which keeps the asserts.

However, I do see your point. In this specific example, I agree that it would be better not to assert. Here is a better pattern:

```C++
OMTensorList *create_input_list() {
   var1 = malloc(...);
   if (!var1) return null;
  var2 = malloc(...);
   if (! var2) {
     free(var1)
     return null;
  }

int main() {

  OMTensorList *input_list = create_input_list(....)
  if (!input_list) 
    return "error code appropriate for running out of memory"

  ...
  return 0;
}
```   
 
I know it is only an example, but the pattern above is the better pattern to "instruct" users how to deal with our interface.

**Comment by gongsu832** [comment]
Keeping asserts for release mode and using asserts correctly for bugs are two separate issues. Bugs are coding errors in the internal logic of your code regardless of external references. malloc returning null or user inputting something you didn't expect, etc., which I see a lot of people like to use assert on, are NOT bugs.

**Comment by Sunny-Anand** [comment]
@jenkins-droid test this please

**Comment by Sunny-Anand** [comment]
@gongsu832 I have removed the assert for the said malloc. @AlexandreEichenberger followed your suggestion for the recommended pattern. I still can't test the PR's and also don't have write access to merge in the PR's.

**Comment by Sunny-Anand** [comment]
@jenkins-droid test this please

**Comment by Sunny-Anand** [comment]
@jenkins-droid test this please

**Review by mikeessen — APPROVED** [review]
LGTM!

**Pull request merged**
