### PR TITLE
Adding missing memref to ops where type is parsed from description

### PR DESCRIPTION
**Pull request by lszinv**
When the op types are generated from parsing the type description, the type list is missing memref.

### CODE REVIEW

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by doru1004** [comment]
@chentong319 can you have a look at this patch please? Any reason why MemRefs were not used before for these operations?

**Review by chentong319 — APPROVED** [review]
LGTM

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
