### PR TITLE
Gemm

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Generate optimized version for gemm, currently crashing in the KRNL to Affine.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@doru1004 When I disable mem pooling, the benchmarks stop crashing. This version has it disabled (search for aee in src/MainUtils.cpp).

But the precision is indicated as too high, e.g.
```
FAIL: test_shufflenet_cpu (__main__.OnnxBackendRealModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexe/.local/lib/python3.8/site-packages/onnx-1.7.0-py3.8-macosx-10.9-x86_64.egg/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/Users/alexe/.local/lib/python3.8/site-packages/onnx-1.7.0-py3.8-macosx-10.9-x86_64.egg/onnx/backend/test/runner/__init__.py", line 288, in run
    self.assert_similar_outputs(ref_outputs, outputs,
  File "/Users/alexe/.local/lib/python3.8/site-packages/onnx-1.7.0-py3.8-macosx-10.9-x86_64.egg/onnx/backend/test/runner/__init__.py", line 174, in assert_similar_outputs
    np.testing.assert_allclose(
  File "/opt/anaconda3/envs/onnx-mlir/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/opt/anaconda3/envs/onnx-mlir/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-07

Mismatched elements: 1000 / 1000 (100%)
Max absolute difference: 0.03612938
Max relative difference: 688.2956
 x: array([[1.568292e-03, 1.736246e-04, 6.534484e-04, 8.649001e-04,
        6.564543e-03, 1.615008e-03, 2.189418e-03, 4.402395e-04,
        5.358604e-04, 1.830248e-04, 6.533524e-04, 3.683726e-03,...
 y: array([[1.917347e-03, 2.122684e-04, 7.988885e-04, 1.057403e-03,
        8.025612e-03, 1.974464e-03, 2.676719e-03, 5.382242e-04,
        6.551274e-04, 2.237613e-04, 7.987704e-04, 4.503600e-03,...
```

Is that expected? Ok?

**Comment by AlexandreEichenberger** [comment]
Error was all mine. run clean now.

**Review by doru1004 — APPROVED** [review]
LGTM
(pending passing of tests)

**Comment by sstamenova** [comment]
This broke the build of onnx-mlir on Windows again :(. There are a couple of known failing tests (see #582) that only show up in the Windows CI because it is the only one to build Release, but now the actual build is broken too:

https://dev.azure.com/onnx-pipelines/onnx/_build/results?buildId=12070&view=logs&j=4060f429-1919-5440-1fce-77a91697330b&t=bd95a858-28bf-5685-35ca-c5870a8c2a33

```
D:\a\1\onnx-mlir\src\Conversion\ONNXToKrnl\Math\Gemm.cpp(168,31): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax [D:\a\1\onnx-mlir\build\src\Conversion\ONNXToKrnl\OMONNXToKrnl.vcxproj]
D:\a\1\onnx-mlir\src\Conversion\ONNXToKrnl\Math\Gemm.cpp(96): message : while compiling class template member function 'void ONNXGemmOpLowering<mlir::ONNXGemmOp>::tiledTransposedGemm(mlir::ONNXGemmOp &,mlir::ONNXGemmOpAdaptor &,mlir::Type,ONNXGemmOpShapeHelper &,mlir::Value,mlir::Value,mlir::Value,mlir::Value,mlir::ConversionPatternRewriter &,mlir::Location) const' [D:\a\1\onnx-mlir\build\src\Conversion\ONNXToKrnl\OMONNXToKrnl.vcxproj]
D:\a\1\onnx-mlir\src\Conversion\ONNXToKrnl\Math\Gemm.cpp(335): message : see reference to function template instantiation 'void ONNXGemmOpLowering<mlir::ONNXGemmOp>::tiledTransposedGemm(mlir::ONNXGemmOp &,mlir::ONNXGemmOpAdaptor &,mlir::Type,ONNXGemmOpShapeHelper &,mlir::Value,mlir::Value,mlir::Value,mlir::Value,mlir::ConversionPatternRewriter &,mlir::Location) const' being compiled [D:\a\1\onnx-mlir\build\src\Conversion\ONNXToKrnl\OMONNXToKrnl.vcxproj]
D:\a\1\llvm-project\mlir\include\mlir/IR/PatternMatch.h(639): message : see reference to class template instantiation 'ONNXGemmOpLowering<mlir::ONNXGemmOp>' being compiled [D:\a\1\onnx-mlir\build\src\Conversion\ONNXToKrnl\OMONNXToKrnl.vcxproj]
D:\a\1\onnx-mlir\src\Conversion\ONNXToKrnl\Math\Gemm.cpp(350): message : see reference to function template instantiation 'mlir::OwningRewritePatternList &mlir::OwningRewritePatternList::insert<ONNXGemmOpLowering<mlir::ONNXGemmOp>,mlir::MLIRContext*&,,void>(ConstructorArg)' being compiled [D:\a\1\onnx-mlir\build\src\Conversion\ONNXToKrnl\OMONNXToKrnl.vcxproj]
```

**Comment by AlexandreEichenberger** [comment]
@sstamenova Sorry, copied the pattern form somewhere else. I will remove it shortly in an update patch. Thanks for pointing out the line number.

**Comment by tungld** [comment]
@AlexandreEichenberger, with this patch, I see the inference result of mnist model is broken on BE machines, similar to the issue reported here #600. Could you please double check with the mnist example in #600? Thanks!

**Comment by gongsu832** [comment]
I can verify that both the current master branch and the llvm-12-release-branch branch now break the mnist model in #600 with commit 36e40878d5f519284126f9a2bb8d59bd6034f7bc. `opt -O2` produces the same bad rodata as `opt -O3` does.

Although I wouldn't necessarily call this a problem of the commit. It sounds like the opt optimization is fundamentally broken for this model for whatever reason. For example, with `opt -O1`, it still produces the bad rodata. But with `opt -O0`, it produces the good rodata.

**Pull request merged**
