### PR TITLE
Add sections to the PyRuntime documentation and break out the model a…

### PR DESCRIPTION
**Pull request by messerb5467**
…pi into its own section. The UsingPyRuntime.md documentation was sparse in terms of sectioning out the "Using PyRuntime" section. I've made that section into a "Configuring and using PyRuntime" section meanwhile promoting the model api into its own section. This code has been validated locally with a github markdown renderer as well as a full read-through of this documentation to ensure the changes coalesced nicely together.

Signed-off-by: Brad Messer <messerb5467@gmail.com>

### CODE REVIEW

**Comment by messerb5467** [comment]
@tungld If you could look this over and tell me your thoughts I'd greatly appreciate it.

**Comment by cjvolzka** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Review by tungld — APPROVED** [review]
LGTM! Thanks for making the doc better!

**Pull request merged**
