### PR TITLE
Fix namespace leak

### PR DESCRIPTION
**Pull request by bxing-groq**

### CODE REVIEW

**Comment by bxing-groq** [comment]
Moved from https://github.com/onnx/onnx-mlir/pull/1299

**Comment by bxing-groq** [comment]
@whitneywhtsang @tungld @etiotto @AlexandreEichenberger   🙏🏼

**Comment by whitneywhtsang** [comment]
> #1299

Just curious, why do you need a new PR?

**Comment by bxing-groq** [comment]
@whitneywhtsang - Maybe there was a lag, but the old PR wasn't updated when I push to the remote :(

**Comment by bxing-groq** [comment]
@jenkins-droid test this please

**Comment by bxing-groq** [comment]
@whitneywhtsang - mind helping me get this in? :)

**Comment by bxing-groq** [comment]
@AlexandreEichenberger - Im guessing your push triggered CI, and once they finish, I need an approval - what would happen afterwards - do I click a button to get this merged?

**Review by tungld — APPROVED** [review]
LGTM! Thank you for the patch!

**Pull request merged**
