### PR TITLE
Enable Build on Windows again and Update CI badge 

### PR DESCRIPTION
**Pull request by jacky82226**
- Use "&&" instead of "and" for Windows C++ Compiler
- Update Windows-CI badge from my account to onnx account
- Simulate fork() on Windows: redirect the stderr to files and then redirect back
My implementation makes stderr as: 
(before) A
temp.onnx.mlir -> B
temp.mlir -> C
(after) D
Final stderr -> A, D

Not sure whether this implementation breaks the original logic. Please carefully review it. Thank you.

### CODE REVIEW

**Comment by tjingrant** [comment]
@jacky82226 I'm not exactly sure why we used fork in the first place, but it looks like this is kinda troublesome for Windows? Maybe we should use the [print](https://llvm.org/doxygen/classllvm_1_1Module.html#a8ee5166cba8576e41617fc96aec1fb85) method of a Module and we can pass in a [llvm_os_stream](https://llvm.org/doxygen/classllvm_1_1raw__os__ostream.html) made from a [std::basic_fstream](https://en.cppreference.com/w/cpp/io/basic_fstream).

Hope this helps!

**Comment by jacky82226** [comment]
Modify the setup script for Windows-CI. (Use exisiting onnx-mlir instead of cloning from master)
Remove [WIP].

**Comment by jacky82226** [comment]
@tjingrant Thanks for the advice. Still, I did not modify the behavior of model->dump(). To simulate the fork on Linux, I redirect the stderr to separate files then redirect back to stderr. I think the behavior should be same as fork here.

**Comment by jacky82226** [comment]
Modify the setup script for Windows-CI. (Use existing onnx-mlir instead of cloning from master)
Remove [WIP] tag and it is ready for PR.

**Comment by jacky82226** [comment]
Modify the setup script for Windows-CI. (Use existing onnx-mlir instead of cloning from master)
Remove [WIP] tag and it is ready for PR review.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
