### PR TITLE
Use the auto-generated KrnlDialect definition

### PR DESCRIPTION
**Pull request by sstamenova**
This also removes some unneeded headers

Signed-off-by: Stella Stamenova <stilis@microsoft.com>

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for the streamlining.

**Comment by AlexandreEichenberger** [comment]
@sstamenova 

there seems to be warning generated, probably due to this pr. Do you mind just looking into it as we are trying to avoid spurious warnings during our build.

```
/workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp: In member function 'mlir::ParseResult onnx_mlir::krnl::KrnlDialectOperandParser::ParseOptionalOperand(const mlir::Type&, mlir::Value&)':
/workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:36:41: warning: ignoring returned value of type 'mlir::ParseResult', declared with attribute nodiscard [-Wunused-result]
   36 |     parser.parseOperandList(operand_refs);
      |                                         ^
In file included from /workdir/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/IR/AttributeSupport.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/IR/Attributes.h:12,
                 from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h:13,
                 from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinTypes.h:12,
                 from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineMemoryOpInterfaces.h:17,
                 from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineOps.h:17,
                 from /workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:15:
/workdir/llvm-project/mlir/include/mlir/Support/LogicalResult.h:113:22: note: 'mlir::ParseResult' declared here
  113 | class LLVM_NODISCARD ParseResult : public LogicalResult {
```

**Comment by sstamenova** [comment]
> @sstamenova
> 
> there seems to be warning generated, probably due to this pr. Do you mind just looking into it as we are trying to avoid spurious warnings during our build.
> 
> ```
> /workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp: In member function 'mlir::ParseResult onnx_mlir::krnl::KrnlDialectOperandParser::ParseOptionalOperand(const mlir::Type&, mlir::Value&)':
> /workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:36:41: warning: ignoring returned value of type 'mlir::ParseResult', declared with attribute nodiscard [-Wunused-result]
>    36 |     parser.parseOperandList(operand_refs);
>       |                                         ^
> In file included from /workdir/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:17,
>                  from /workdir/llvm-project/mlir/include/mlir/IR/AttributeSupport.h:17,
>                  from /workdir/llvm-project/mlir/include/mlir/IR/Attributes.h:12,
>                  from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinAttributeInterfaces.h:13,
>                  from /workdir/llvm-project/mlir/include/mlir/IR/BuiltinTypes.h:12,
>                  from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineMemoryOpInterfaces.h:17,
>                  from /workdir/llvm-project/mlir/include/mlir/Dialect/Affine/IR/AffineOps.h:17,
>                  from /workdir/onnx-mlir/src/Dialect/Krnl/KrnlHelper.cpp:15:
> /workdir/llvm-project/mlir/include/mlir/Support/LogicalResult.h:113:22: note: 'mlir::ParseResult' declared here
>   113 | class LLVM_NODISCARD ParseResult : public LogicalResult {
> ```

Can you point me to the build that has this warning? It should really not be related to this PR since it didn't change the usage of `parseOperandList` in `KrnlHelper.cpp` and the warning is about the return value not being checked.

**Comment by AlexandreEichenberger** [comment]
Saw it while compiling #1565

**Pull request merged**
