### PR TITLE
Add shape inference for Global Pooling ops

### PR DESCRIPTION
**Pull request by alberto-magni**
Factor out the implementation of shape inference for the three ops:
* GlobalAveragePool
* GlobalLpPool
* GlobalMaxPool

This is possible because these ops behave in the same way: they all shrink spatial dimensions to 1.

### CODE REVIEW

**Comment by alberto-magni** [comment]
Are there any comments on this ?
Thanks

**Comment by tungld** [comment]
@jenkins-droid test this please.

**Comment by alberto-magni** [comment]
Hi @tungld, is this PR ok to merge ? 
Thanks

**Review by doru1004 — APPROVED** [review]
LGTM

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by doru1004** [comment]
Can you update the description of the patch please by giving a few more details about your changes? Would be good to explain why the Global ops can share the same inference method.

**Comment by alberto-magni** [comment]
I have merged against master and updated the description

**Comment by alberto-magni** [comment]
The build is failing for a timeout, but the tests themselves are fine.

**Comment by alberto-magni** [comment]
Please go ahead and merge this PR, I don't have commit access.
Thanks.

**Comment by doru1004** [comment]
Just updated to latest master, once all tests pass I will merge.

**Comment by alberto-magni** [comment]
https://github.com/onnx/onnx-mlir/commit/22898b767ce419b865a3338ff15849c1dd77f7ea
This change is likely causing a conflict. I'll resolve it.

**Comment by alberto-magni** [comment]
Is this ok to merge now ?
Thanks.

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by doru1004** [comment]
@alberto-magni I have to wait for all the tests to pass. I started the Jenkins tests just now so let's see.

**Pull request merged**
