### PR TITLE
Update llvm commit ID to 1d01fc1

### PR DESCRIPTION
**Pull request by tjingrant**
Duplicate of #284, the difference is that this PR is created as a branch in the onnx-mlir repo; this allows this PR to access privileged environment variables such as docker hub token. Credit to @imaihal .

======================================

This PR includes fixes for LLVM revisions: [D85495](https://reviews.llvm.org/D85495), [D85622](https://reviews.llvm.org/D85622), and [D86121](https://reviews.llvm.org/D86121) to use newer LLVM commit.

- D85495
`TypeID` should be set to `mlir::Dialect` by LLVM revision [D85495](https://reviews.llvm.org/D85495) I updated as it is done at `ToyDialect` in the revision https://reviews.llvm.org/D85495#change-M9kXqI8sOFkn

- D85622
This revision includes change in how to register dialects. I updated as it is done in the revision. For example. https://reviews.llvm.org/D85622#change-2drP7BXp5CDr

- D86121
`type.getKind()` was removed by LLVM revision [D86121](https://reviews.llvm.org/D86121). So, I needed to modify it as described in https://llvm.discourse.group/t/removing-kinds-from-attributes-and-types/1547
I used `TypeSwitch<Type>(type)` instead of `switch (type.getKind())` 

I confirmed this works on [1d01fc1](https://github.com/llvm/llvm-project/commit/1d01fc100bb5bef5f5eaf92520b2e52f64ee1d6e) (Aug 31, 2020)

### CODE REVIEW

**Comment by tjingrant** [comment]
Appears that docker build on ppc64le travis container is known to have issues:
https://travis-ci.community/t/building-a-docker-image-in-ppc64le-fails-when-calling-apt-update-invalid-cross-device-link/9674

I will give up fixing this.

**Comment by AlexandreEichenberger** [comment]
@tjingrant let us know if its ready to go or you are still working on it. I merged the latest changes and started a new round of test. Would be helpful if you could list the tests that you expect not to work, if any. Thanks

**Comment by tjingrant** [comment]
> @tjingrant let us know if its ready to go or you are still working on it. I merged the latest changes and started a new round of test. Would be helpful if you could list the tests that you expect not to work, if any. Thanks

I'm watching the results closely, but the test run takes >2 hrs to finish (building prereq docker images). Will let you know once I'm more certain this whole process works!

**Comment by tjingrant** [comment]
@AlexandreEichenberger it's ready - Travis is expected to fail (specifically, Travis ppc64le build is expected to fail unless new docker ppc64le prereq images are pushed to docker hub).

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, I see updates to onnx-mlir to the newer llvm as well as changes to the automatic builds. Thanks.

**Comment by AlexandreEichenberger** [comment]
thanks @tjingrant

**Pull request merged**
