### PR TITLE
Relax dynamic restriction on `ScatterND` stablehlo conversion

### PR DESCRIPTION
**Pull request by srcarroll**
The previous implementation asserted that all dims of the `indices` operand were static. First of all, assertion isn't appropriate here as the definition of the op allows dynamic.  This is a condition for the pattern match and thus should fail the match with `notifyMatchFailure`. Second, the implementation only relies on the last dim being static, so we can relax the match condition and only fail if last dim is dynamic.

### CODE REVIEW

**Comment by srcarroll** [comment]
I'll be honest. I don't completely understand the lowering of `ScatterND` so I'm not sure if the result is correct. But I just noticed that the assertion was too restrictive based on the fact that only the last dim of `indices` needed to be static.  So I'm assuming everything else is correct when relaxing the restriction. Please confirm.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, feel free to get a second opinion from an HLO expert.

**Comment by AlexandreEichenberger** [comment]
@srcarroll let me know when you are ready for me to push the code.

**Comment by Connor-XY** [comment]
> I'll be honest. I don't completely understand the lowering of `ScatterND` so I'm not sure if the result is correct. But I just noticed that the assertion was too restrictive based on the fact that only the last dim of `indices` needed to be static. So I'm assuming everything else is correct when relaxing the restriction. Please confirm.

The assertion is restrictive since I would like to provide a basic implementation for static-shaped tensors first, and fail dynamic ones temporarily. I believe that you are now supporting dynamic cases and we could remove some restrictions gradually. As for the `ScatterND` op, it indeed only requires the last dim of `indices` to be static, and your test case should work as I don't see any problem with it.

**Comment by srcarroll** [comment]
> > I'll be honest. I don't completely understand the lowering of `ScatterND` so I'm not sure if the result is correct. But I just noticed that the assertion was too restrictive based on the fact that only the last dim of `indices` needed to be static. So I'm assuming everything else is correct when relaxing the restriction. Please confirm.
> 
> The assertion is restrictive since I would like to provide a basic implementation for static-shaped tensors first, and fail dynamic ones temporarily. I believe that you are now supporting dynamic cases and we could remove some restrictions gradually. As for the `ScatterND` op, it indeed only requires the last dim of `indices` to be static, and your test case should work as I don't see any problem with it.

@Connor-XY  Thanks for the confirmation! @AlexandreEichenberger you can merge. I'm rebasing now just in case

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Pull request merged**
