### PR TITLE
Update protobuf

### PR DESCRIPTION
**Pull request by cjvolzka**
Protobuf 3.16 is no longer being updated by that community. This upgrades to the closest protobuf version to 3.16 that is still supported which includes current security updates.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@cjvolzka think the ppc jenkins failed for other PRs, so it is probably good if it succeeds with s390

**Comment by sstamenova** [comment]
It would be nice to add a comment in the commit message or in the scripts about how/why this particular version was chosen, but looks good otherwise.

**Comment by cjvolzka** [comment]
Updated description.

**Review by sstamenova — APPROVED** [review]

**Review by chentong319 — APPROVED** [review]
LGTM!

**Pull request merged**
