### PR TITLE
Fix JNI memory leak for tensor data

### LINKED ISSUE #2171: Memory Leak with Java client
Applications using models compiled with --EmitJNI slowly leak memory after ever mainGraph() call.

## Reproduce:
 
1. Compile [mnist-12.onnx](https://github.com/onnx/models/blob/main/vision/classification/mnist/model/mnist-12.onnx) model using onnx-mlir using 
    * CPU: `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 --onnx-op-stats TXT`
    * NNPA: `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z16 --maccel=NNPA --onnx-op-stats TXT` 
2. Build the [Leaker.java.txt](https://github.com/onnx/onnx-mlir/files/11243310/Leaker.java.txt) Java application: `MODEL=mnist-12.jar; javac -cp mnist-12.jar Leaker.java`
    * Calls `mainGraph()` continuously for 5 min. Change `run_max_sec` to a different value if desired.
4. Run the Leaker Java application: `java -cp .:$MODEL Leaker`
5. Watch java RES memory usage: `top -d1 -u $USER

## Expected results:
Java does it's own memory management so usage may fluctuate, but it should remain about the same after 10-30 seconds.

## Actual Results
The program continues to slowly uses more and more memory, 

## Notes:
* Affects both CPU and NNPA. Leak is faster with NNPA but that is likely due to the model running faster.
* Issue is specific to Java clients. The same test on the same .so has no leak.
    * Extract the .so can from the .jar file. 
        * `unzip mnist-12.jar -d unzipped_jar`
    * Run with [leaker.cpp.txt](https://github.com/onnx/onnx-mlir/files/11243314/leaker.cpp.txt)
        * `MODEL=unzipped_jar/libmodel.so; g++ -g --std=c++11 -O3 leaker.cpp $MODEL -o leaker -I include && time ./leaker`
    *  C++ does not continuously use more memory
    * using `valgrind` says no leakers are possible

### PR DESCRIPTION
**Pull request by tehbone**
Fixes #2171. This is yet another approach that is compatible with Java 8+. It mirrors a Java 9 `Cleaner`-based approach, but utilizing `WeakReference`s to keep track of the lifetime of the object. A `ByteBuffer` is used to keep track of the underlying allocation, and when the reference to the data expires, the allocation will be freed. It is also tied to the lifetime of the `ByteBuffer` created by the JNI instead of the `OMTensor` to handle scenarios where the `OMTensor` is updated. In such scenarios, the GC will grab the original `ByteBuffer` well before the `OMTensor` is destroyed, allowing for the allocation to be more aggressively reclaimed.

This fix also removes the extra copy that would occur if the model did _not_ allocate storage for the returned `OMTensor` object.

### CODE REVIEW

**Comment by tehbone** [comment]
@gongsu832 I know I have PR #2176 out there, but I think this approach satisfies all of the concerns.

**Comment by gongsu832** [comment]
@tehbone As much as I hate copying, between this and copying, I'd just go for copying then switch to Cleaner when WMLz upgrades from Java 8 if we don't want to maintain two sources. I think this is just too complicated for what we want to do. Eventually Cleaner will be the way to go and it provides both auto close and explicit user close.

Moot point, I think you can just pass the jni_alloc as a jlong to the OMTensor constructor without using a DirectByteBuffer.

**Comment by cjvolzka** [comment]
Not that watching `top` RES is a perfect measure, but here's what I got on a 120min mnist-12 loop run on LoZ Java 11:

This "reaper" branch  version the first 30 sec RES fluctuates and stabilizes at 60.5m at 41 seconds. Goes to 60.7m at 1min. Slowly moves to 61.1m at 5min and is at 62.2 at 7 min and stays there until 47 min. Then it goes to 63.3m until 55min. Finally over min 55-57 it goes to 92.4 where it stays until the run ends at 120 minutes. In the end, mainGraph ran 1,926,597 times.

I did a similar test for the "bytebuffer" version and the results there appear slightly better. Although it's hard to say how much of the RES difference is the the code vs JVM doing it's thing.

**Comment by tehbone** [comment]
Closing, as it has been superseded by #2176

**Pull request closed without merging**
