### PR TITLE
MatMul 1-D x 1-D results in scalar

### LINKED ISSUE #1580: MatMul 1-D x 1-D should result in scalar
MatMul 1-D x 1-D shape inference results in 1-D shape.
See `@test_matmul_1` in `test/mlir/onnx/onnx_shape_inference.mlir`
This contradicts numpy and the onnx spec which infer a scalar.

numpy:
```python
print(numpy.matmul(numpy.random.rand(2), numpy.random.rand(2)).shape)
# prints the empty shape (), i.e. scalar
```

onnx:
```python
import onnx
from onnx import helper, shape_inference
from onnx import TensorProto

node = helper.make_node('MatMul', ['A', 'B'], ['Y'])
graph = helper.make_graph(
  [node],
  'matmul',
  [helper.make_tensor_value_info('A', TensorProto.FLOAT, (2,)),
   helper.make_tensor_value_info('B', TensorProto.FLOAT, (2,))],
  [helper.make_tensor_value_info('Y', TensorProto.FLOAT, None)],
)
original_model = helper.make_model(graph)
inferred_model = shape_inference.infer_shapes(original_model)
print(inferred_model.graph.output[0].type.tensor_type)
# prints type with empty shape, i.e. scalar:
#   elem_type: 1
#   shape {
#   }
```

### PR DESCRIPTION
**Pull request by sorenlassen**
closes #1580

Signed-off-by: Soren Lassen <sorenlassen@gmail.com>

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
@sorenlassen let me know if you want me to merge it

**Comment by sorenlassen** [comment]
> @sorenlassen let me know if you want me to merge it

please do, thanks

**Comment by AlexandreEichenberger** [comment]
@sorenlassen thanks for your contribution, much appreciated.

**Pull request merged**
