### PR TITLE
Support LLVM as of 7dcd0042

### PR DESCRIPTION
**Pull request by NathanielMcVicar**
Fixes for upstream changes to mlir as of 7dcd0042e8b8581751bd9b915207058d2ab88e1d.

- New pass registration method from https://reviews.llvm.org/D85622
- Integer attributes are now C types when possible https://reviews.llvm.org/D86739

### CODE REVIEW

**Comment by NathanielMcVicar** [comment]
@tjingrant Thanks for walking me through the steps. Please let me know if I missed any! I'll fix DCO, when it's ready. I haven't found a nice way to sign off in Visual Studio.

**Comment by NathanielMcVicar** [comment]
It looks like LLVM upstream increased the CMake requirement breaking the ppc64 docker image. @caoimhinuibrian (or whoever is appropriate) Is there a solution for this? Thanks!

`CMake 3.13.4 or higher is required.  You are running version 3.10.2`

**Comment by tjingrant** [comment]
@NathanielMcVicar do you know why Windows build is failing? I'm taking a look at ppc build failures now.

**Comment by NathanielMcVicar** [comment]
@tjingrant Updated hash for Windows CI build, should be fixed.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by NathanielMcVicar** [comment]
@tjingrant I think there's something slightly unsafe going on here, where fundamentally signed values are being stored as uint64_t when you use the new getValue(). I thought about taking all the autos that used getSExtValue() and making them int64_t to make this more clear, but instead I only changed the ones that were used in signed comparisons (like `axis < 0`). If you are running into problems with this on some platforms and not others, it might be good to make them all int64s to clear up the ambiguity. I can do this is the morning if you'd prefer, if not, and I can take a look at anything else, I'd be happy to! Thanks for looking into all this.

**Comment by tjingrant** [comment]
@NathanielMcVicar do you mean something like:
```
auto axis = concatOp.axis();
``
now returns uint64 always?

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
Looking at the relevant mlir patch: https://github.com/llvm/llvm-project/commit/431bb8b31825ca0e855a92f72a8a33cf7c6c30b6 , clearly SI64 better matches the semantics of ONNX int attribute, so I modified all use of I64 attribute to SI64.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Review by doru1004 — APPROVED** [review]
LGTM

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Review by tjingrant — APPROVED** [review]
LGTM.

**Comment by caoimhinuibrian** [comment]
> @tjingrant Thanks for walking me through the steps. Please let me know if I missed any! I'll fix DCO, when it's ready. I haven't found a nice way to sign off in Visual Studio.

@NathanielMcVicar When you write the commit message in vscode, append - Signed-off-by: Nathaniel.... <email>
to it.

**Comment by caoimhinuibrian** [comment]
@NathanielMcVicar Oh ... I just realized, it has to be on a new line

**Comment by NathanielMcVicar** [comment]
@caoimhinuibrian I never even thought of just doing it manually, but that's a good idea! VSCode supports signoff at commit time in the GUI, but regular old Visual Studio doesn't as far as I can tell. I've been staging my changes in VS and then committing them on the command line, but I like your way better :)

**Pull request merged**
