### PR TITLE
Add builders for ONNX operation definitions to allow to build them by Table-driven Declarative Rewrite Rules 

### PR DESCRIPTION
**Pull request by negiyas**
Add builders for ONNX operation definitions to allow to build them by Table-driven Declarative Rewrite Rules (DRR) directly without using "NativeCodeCall."
It is required because the current DRR implementation has some limitations with "NativeCodeCall," (e.g.  not allow to use "auxiliary ops", and number of arguments should be less than 9).

This PR updates "utils/gen_onnx_mlir.py"  and "src/Dialect/ONNX/ONNXOps.td.inc" generated by updated utils/gen_onnx_mlir.py.
Modifications on "utils/gen_onnx_mlir.py" are the following two.
(1) Add builders for "ONNX.Identify" and "ONNX.Split" operations
(2) Change the way to get Tensor's element type from `X.getType().cast<TensorType>().getElementType()` to `X.getType().cast<ShapedType>().getElementType()` to avoid errors to cast "X" to TensorType when the input is converted into another Type (e.g. MemRefType).

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@negiyas `ONNXOps.td.inc` was automatically generated by `gen_onnx_mlir.py`. Please follow the instruction here for adding custom builders to ONNX ops: http://onnx.ai/onnx-mlir//ImportONNXDefs.html

**Comment by negiyas** [comment]
@tungld Thank you. I am updating utils/gen_onnx_mlir.py without updating src/Dialect/ONNX/ONNXOps.td.inc directly.

**Comment by negiyas** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Review by chentong319 — APPROVED** [review]
LGTM!

**Pull request merged**
