### PR TITLE
Use MLIR_SYSTEM_LIBRARIES to link against the required system libraries

### PR DESCRIPTION
**Pull request by sstamenova**
Several system library dependencies that are needed are not included in a consistent manner. This change introduces an MLIR_SYSTEM_LIBRARIES variable (which could also be just SYSTEM_LIBRARIES) to collect the system libraries coming from mlir as dependencies and then add them as appropriate.

This also removes the requirement for the curses library on Windows - it is not actually needed since llvm does not use it on Windows.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@caoimhinuibrian or @gongsu832 do you mind looking into this PR? thanks

**Comment by gongsu832** [comment]
LGTM

**Comment by sstamenova** [comment]
Can someone commit this if it's approved? Thanks!

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
Thanks @sstamenova for the contribution, and @gongsu832 and @caoimhinuibrian for the review. Much appreciated

**Pull request merged**
