### PR TITLE
Leak namespace

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
there was a
```
using namespace mlir
```
in a header file. removed it, had to add more mlir:: that I wish I had to, but it works now.

### CODE REVIEW

**Review by caoimhinuibrian — COMMENTED** [review]
couldn't we just put the "using mlir" into the cpp files that needed it, rather than changing to explict mlir:: everywhere?

**Comment by AlexandreEichenberger** [comment]
> couldn't we just put the "using mlir" into the cpp files that needed it, rather than changing to explict mlir:: everywhere?

good point, I did this plus added the `using mlir` in the numerical tests that failed to compile.

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
Thanks @caoimhinuibrian for the suggestion, it was a good one.

**Pull request merged**
