### PR TITLE
Rt error reporting

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Use errno interface for failure encountered during inference evaluation. See Issue #1417 for discussions.
First version only generate an error when there is a mismatch of versions for the NNPA

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@tungld the change in the interface is that `uint64_t OMInitCompatibleAccelNNPA` now returns an int. If true, we are fine, if false, the run_main_graph needs to return NULL... I think this should be fairly straightforward.

**Comment by tungld** [comment]
> @tungld the change in the interface is that uint64_t OMInitCompatibleAccelNNPA now returns an int. If true, we are fine, if false, the run_main_graph needs to return NULL... I think this should be fairly straightforward.

Oh, I see. May I edit this patch directly to just change the return type of OMInitCompatibleAccelNNPA from `void` to `uint64_t`, it should be a few lines. Then this patch can go first. I will create another PR to follow this patch to handle how `run_main_graph` returns NULL.

**Comment by tungld** [comment]
Somehow I cannot push commit to your branch directly though It seems I have permission. So, I push the changes here that update the signature of `OMInitCompatibleAccelX` at LLVM level.
```diff
diff --git a/src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp b/src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
index 25d356c9..671b4e04 100644
--- a/src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
+++ b/src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
@@ -86,7 +86,7 @@ public:

     // Emit code to initialize accelerators by calling OMInitCompatibleAccelX
     // where X is the accelerator name.
-    // OMInitCompatibleAccelX's signature is `void (i64)`.
+    // OMInitCompatibleAccelX's signature is `i64 (i64)`.
     if (Attribute maccelAttr =
             module->getAttrOfType<::mlir::Attribute>("onnx-mlir.accels")) {
       assert(
@@ -103,7 +103,7 @@ public:
         LLVM::ConstantOp versionNumberVal = rewriter.create<LLVM::ConstantOp>(
             loc, int64Ty, rewriter.getI64IntegerAttr(versionNumberInHex));
         rewriter.create<LLVM::CallOp>(
-            loc, TypeRange(), funcRef, ArrayRef<Value>({versionNumberVal}));
+            loc, int64Ty, funcRef, ArrayRef<Value>({versionNumberVal}));
       }
     }

@@ -380,14 +380,14 @@ private:
   FlatSymbolRefAttr getOrInsertOMInitCompatibleAccel(
       PatternRewriter &rewriter, ModuleOp module, StringRef accelName) const {
     std::string funcName = "OMInitCompatibleAccel" + accelName.str();
-    // OMInitCompatibleAccelX's signature is `void (i64)`.
+    // OMInitCompatibleAccelX's signature is `i64 (i64)`.
     auto func = module.lookupSymbol<LLVM::LLVMFuncOp>(funcName);
     MLIRContext *ctx = rewriter.getContext();
     if (!func) {
       OpBuilder::InsertionGuard guard(rewriter);
       rewriter.setInsertionPointToStart(module.getBody());
       LLVM::LLVMFunctionType funcType =
-          LLVM::LLVMFunctionType::get(LLVM::LLVMVoidType::get(ctx),
+          LLVM::LLVMFunctionType::get(IntegerType::get(ctx, 64),
               ArrayRef<mlir::Type>({IntegerType::get(ctx, 64)}),
               /*isVarArg=*/false);
       func = rewriter.create<LLVM::LLVMFuncOp>(
```

and 
```diff
diff --git a/test/mlir/krnl/entry_point.mlir b/test/mlir/krnl/entry_point.mlir
index adf61936..697c64e3 100644
--- a/test/mlir/krnl/entry_point.mlir
+++ b/test/mlir/krnl/entry_point.mlir
@@ -242,7 +242,7 @@ module attributes {"onnx-mlir.accels" = ["Pseudo-0x10001", "NNPA-0x10000"]} {
 // CHECK: llvm.func @OMInitCompatibleAccelPseudo(i64)
 // CHECK-LABEL: llvm.func @run_main_graph({{.*}}: !llvm.ptr<i8>) -> !llvm.ptr<i8> {
 // CHECK-NEXT: [[VERSION_NUMBER_1:%.+]] = llvm.mlir.constant(65537 : i64) : i64
-// CHECK-NEXT: llvm.call @OMInitCompatibleAccelPseudo([[VERSION_NUMBER_1]]) : (i64) -> ()
+// CHECK-NEXT: llvm.call @OMInitCompatibleAccelPseudo([[VERSION_NUMBER_1]]) : (i64) -> i64
 // CHECK-NEXT: [[VERSION_NUMBER_2:%.+]] = llvm.mlir.constant(65536 : i64) : i64
-// CHECK-NEXT: llvm.call @OMInitCompatibleAccelNNPA([[VERSION_NUMBER_2]]) : (i64) -> ()
+// CHECK-NEXT: llvm.call @OMInitCompatibleAccelNNPA([[VERSION_NUMBER_2]]) : (i64) -> i64
 }
```

**Comment by AlexandreEichenberger** [comment]
migrated to https://github.com/onnx/onnx-mlir/pull/1428

**Pull request closed without merging**
