### PR TITLE
upgrade to ONNX 1.17.0 (opset 22)

### PR DESCRIPTION
**Pull request by gongsu832**

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks @gongsu832 

as a follow on, one will have to update what is actually supported (e.g. we don't support the bfloat16. @Sunny-Anand can someone on your team update the limitations in our docs?

**Comment by Sunny-Anand** [comment]
> LGTM, thanks @gongsu832
> 
> as a follow on, one will have to update what is actually supported (e.g. we don't support the bfloat16. @Sunny-Anand can someone on your team update the limitations in our docs?

Thanks @gongsu832 for the upgrade. @AlexandreEichenberger I will have someone update the limitation in the docs.

**Comment by AlexandreEichenberger** [comment]
@Sunny-Anand it feel that we should?

**Comment by hamptonm1** [comment]
> Should we also update `CURRENT_ONNX_OPSET` https://github.com/onnx/onnx-mlir/blob/main/src/Dialect/ONNX/ONNXOps.hpp#L29C22-L29C41 ?

@mgehre-amd Good point! It should be updated to 22 now :)

**Comment by Sunny-Anand** [comment]
I will open up a pr for this. Thanks @mgehre-amd for reporting this.

**Pull request merged**
