### PR TITLE
Improve LSTM performance by reduing matrix multiply

### PR DESCRIPTION
**Pull request by shizy818**

### CODE REVIEW

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@shizy818 Thank you for the patch!

TestLSTM on Jenkins Linux s390x failed. Could you please check what happened with it in your local environment? It can be reproduced by invoking `Debug/bin/TestLSTM`.

**Comment by shizy818** [comment]
@tungld Sorry reply it late. Yes, I can recreate it on my zlinux machine. I hope I can check more detail by this weekend.

**Comment by shizy818** [comment]
@gongsu832 Hi can you try test it again? Thanks!

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by shizy818** [comment]
Sign-off to pass DCO

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
