### PR TITLE
Fix architecture terminology

### PR DESCRIPTION
**Pull request by tehbone**
Changed the naming of P and Z which are IBM brands to the respective architectures to be consistent with listed x86 architecture example.

### CODE REVIEW

**Comment by hamptonm1** [comment]
@jenkins-droid Test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for switching to the proper naming.

FYI, grepping for Z in md files, I also found this, in case it also needs fixing.

```
Neural Network Processing Assist Facility (NNPA) is implemented on processor units of IBM z16. Onnx-mlir can use it via  [IBM Z Deep Neural Network Library (zDNN)](https://github.com/IBM/zDNN). Building and lit tests runs on other IBM Z systems(eg. z15), but numerical tests need to run on z16.
```

**Comment by tehbone** [comment]
There's no jenkinsfile in the `gh-pages` branch, presumably since there is nothing to build. @AlexandreEichenberger

**Comment by tehbone** [comment]
> LGTM, thanks for switching to the proper naming.
> 
> FYI, grepping for Z in md files, I also found this, in case it also needs fixing.
> 
> ```
> Neural Network Processing Assist Facility (NNPA) is implemented on processor units of IBM z16. Onnx-mlir can use it via  [IBM Z Deep Neural Network Library (zDNN)](https://github.com/IBM/zDNN). Building and lit tests runs on other IBM Z systems(eg. z15), but numerical tests need to run on z16.
> ```
The brand are correct there, but I leave it to you to determine if the capitalization of `Onnx-mlir` in that quote is correct.

**Comment by hamptonm1** [comment]
@AlexandreEichenberger I think it has to do with the branch that @tehbone is trying to merge into. He specified `onnx:gh-pages` instead of `onnx-mlir`. @tehbone Can you do me a favor and make the update in ` onnx-mlir/main/docs/ONNXAI.md` from the main branch in `onnx-mlir` instead of from `gh-pages`?

**Comment by tehbone** [comment]
@hamptonm1 The webpage (https://onnx.ai/onnx-mlir/) is served from `gh-pages`, not from the other branches. That branch is the 'main' for the web serving content.

**Comment by tehbone** [comment]
Ah! I see there is automation in place to push from main to here. I will update this PR accordingly.

**Comment by hamptonm1** [comment]
> Ah! I see there is automation in place to push from main to here. I will update this PR accordingly. Thank you @hamptonm1 !

You are welcome :)

**Pull request closed without merging**
