### PR TITLE
Bump cmake minimum required version to 3.20.0

### PR DESCRIPTION
**Pull request by sstamenova**
This matches the current minimum required version in llvm (see https://reviews.llvm.org/D144509)

See https://github.com/onnx/onnx-mlir/issues/2063 as well

### CODE REVIEW

**Comment by NathanielMcVicar** [comment]
LGTM, although somewhat painful as described in the linked issue.

**Comment by gongsu832** [comment]
Unfortunately Ubuntu Focal, which our dev docker image is based on, is only up to cmake 3.16.3.

**Comment by sstamenova** [comment]
> Unfortunately Ubuntu Focal, which our dev docker image is based on, is only up to cmake 3.16.3.

How are we going to address that once we try to update llvm to a commit that requires 3.20?

**Comment by gongsu832** [comment]
I will have to look into upgrading the base image to Jammy, which will have cmake 3.22.1.

**Comment by sstamenova** [comment]
> I will have to look into upgrading the base image to Jammy, which will have cmake 3.22.1.

@gongsu832 Ok, I will leave this PR up to be completed once the base image supports it. I am not sure when (though I suspect very soon) LLVM will re-commit the new version requirement and one of the next llvm updates will need this.

**Comment by NathanielMcVicar** [comment]
Another option is to add the apt.kitware repo to the docker image setup. That might be lower friction until you are ready to move to jammy.

**Comment by gongsu832** [comment]
I'll try Jammy and see how many things break and proceed with it if not too many. Otherwise I'll look into apt.kitware. Thanks for the suggestion.

**Comment by gongsu832** [comment]
@sstamenova I'm wondering, if we upgrade our base image to Jammy, we will have to also upgrade the LLVM no-warning buildbot to Jammy, right?

**Comment by sstamenova** [comment]
> @sstamenova I'm wondering, if we upgrade our base image to Jammy, we will have to also upgrade the LLVM no-warning buildbot to Jammy, right? Since the buildbot config is supposed to match our build env.

Yes, whichever way you use to upgrade cmake here will need to be applied to the buildbot since it will also require the newer version of cmake.

**Comment by gongsu832** [comment]
> Yes, whichever way you use to upgrade cmake here will need to be applied to the buildbot since it will also require the newer version of cmake.

I tried Jammy and it was eventless. Everything pretty much just worked. So I will put out a PR to upgrade to Jammy. Once that's done, can I just create another Jammy based docker container for the LLVM no-warning buildbot, replicating all the configurations from the Focal based buildbot, and then shutting down the Focal based buildbot?

**Comment by gongsu832** [comment]
> Assuming you connect with the same worker name and password, it should work.

Great. I'll give that a shot once we upgrade to Jammy. Thanks.

**Comment by MikeHolman** [comment]
@jenkins-droid test this please

**Comment by NathanielMcVicar** [comment]
@gongsu832 it looks like the CMake version on the Jenkins builds is still below 3.20. Is there an additional step we should take to update these? Thanks!

**Comment by gongsu832** [comment]
It's being addressed by https://github.com/onnx/onnx-mlir/pull/2234

**Comment by NathanielMcVicar** [comment]
> @NathanielMcVicar Windows CI appears to be stuck not reporting status. Is there any way to trigger it manually?

I see it reporting currently, can you point me to an example? Sorry, I missed this on Friday.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 are the conditions that were holding us to a lower cmake minimum version still holding us at this time?

**Comment by AlexandreEichenberger** [comment]
I will defer this question for @gongsu832

**Comment by gongsu832** [comment]
Dev image is based on Ubuntu Jammy which comes with cmake 3.22.1 and user image is based on Redhat ubi8 which comes with cmake 3.20.2. So bumping up to 3.20.0 shouldn't be a problem.

**Review by NathanielMcVicar — APPROVED** [review]

**Pull request merged**
