### PR TITLE
Add buildbot on Windows via Azure Pipeline

### PR DESCRIPTION
**Pull request by jacky82226**
Add buildbot script on Azure pipeline, build Script on Windows and test Script on Windows. 
Will need the repo access for setup the CI on Azure Pipeline.  
The current version cannot pass Windows build because there are some codes cannot pass the Microsoft Visual Studio C++ Compiler. For example, use "and" instead of "&&".
This buildbot can pass #86 (Enable Windows build by Byron) commit successfully on my forked repo.

### CODE REVIEW

**Comment by tjingrant** [comment]
@jacky82226 is there anything I could be of help to push this patch forward? Please let me know how I can help!

**Comment by jacky82226** [comment]
> @jacky82226 is there anything I could be of help to push this patch forward? Please let me know how I can help!

1. Enable the "Azure Pipelines" Github extension for onnx/onnx-mlir on Marketplace tab.
2. Give @jacky82226 the temporary maintainer access to the repo

Once my PR with the files has been merged to the original repo, I should be able to deploy the Windows buildbot on Azure Pipeline. 

Thank you.

**Comment by tjingrant** [comment]
@jacky82226 thanks for setting up the Windows buildbo! Looking at the work you've put in, I wonder whether you have chatted with @byronChanguion , who introduced several scripts to help folks build mlir and this project on Windows. 

It would be nice to use the same set of scripts for both providing instructions to users and setting things up on the buildbot. This way we ensure that we never mislead the users, which can easily happen when we update the buildbot scripts, but not the user instructions. So I wonder if there's any way to unify this current patch with the following scripts put together by @byronChanguion ?

I.e., the following scripts seem to be useful to be called within `utils/setup-onnx-mlir-windows.cmd`.

- https://github.com/onnx/onnx-mlir/blob/master/utils/install-mlir.cmd
- https://github.com/onnx/onnx-mlir/blob/master/utils/install-onnx-mlir.cmd

**Comment by jacky82226** [comment]
Good idea. I have unified his files and make `setup-onnx-mlir-windows` cleaner.
The whole build time takes averagely 1h 30m.

**Comment by s390xlinux** [comment]
Can one of the admins verify this patch?

**Comment by tjingrant** [comment]
Hi @jacky82226 thanks! I've given you the temporary maintainer access you've requested. However, I do not see an option to install Azure Pipeline for this project (I only see the option to install Azure Pipeline on projects I own). Do you know if I have the requisite permission to set up Azure pipeline or do I need to ask ONNX organization admins to enable it for this repo?

**Comment by jacky82226** [comment]
https://github.com/marketplace/azure-pipelines
Try this link and click "Install it for free". Then I would get this repo on my Azure Pipeline. Thank you!

**Comment by jacky82226** [comment]
> Hi @jacky82226 thanks! I've given you the temporary maintainer access you've requested. However, I do not see an option to install Azure Pipeline for this project (I only see the option to install Azure Pipeline on projects I own). Do you know if I have the requisite permission to set up Azure pipeline or do I need to ask ONNX organization admins to enable it for this repo?

https://github.com/marketplace/azure-pipelines
Try this link and click "Install it for free". Then I would get this repo on my Azure Pipeline. Thank you!

**Comment by tjingrant** [comment]
Hello @jacky82226 , Prasanth updated the Azure Pipeline setting, can you try it again?

**Comment by jacky82226** [comment]
> Hello @jacky82226 , Prasanth updated the Azure Pipeline setting, can you try it again?
It said I need at least one commit to access onnx/onnx-mlir. Could you help me to merged into the master first?

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by jacky82226** [comment]
Great. I can setup the Windows-CI for master now. Will update another patch for making the latest commit pass the Windows-CI. @tjingrant Thanks!

**Pull request merged**
