### PR TITLE
Add onnx.reshape op optimization patterns

### PR DESCRIPTION
**Pull request by negiyas**
Add the following two onnx.reshape op optimization patterns like "CreateCombinedTransposedPattern" and "RemoveIdentityTransposePattern".
(1) “CombinedReshapePattern”: If two reshape ops are connected directly, remove the first reshape op.
(2) “RemoveIdentityReshapePattern”: If shape in a reshape op is constant, and the shape of the input value and the specified shape are the same, remove the reshape op.

These optimization patterns do not contribute the performance improvement directly, but they enable to apply further optimization patterns.

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for implementing them in the canonicalization pass.

**Comment by AlexandreEichenberger** [comment]
@negiyas if the PR is complete, please add the "ready to merge" label.

**Comment by negiyas** [comment]
@AlexandreEichenberger Thank you for the quick approval.

> If the PR is complete, please add the "ready to merge" label.
I suppose that this PR is ready to merge, but I cannot push the "Labels" button. I may not have permission.

**Comment by tungld** [comment]
Jenkins failed because you edited `ONNXOps.td.inc` that was automatically generated. Instead, please update `gen_onnx_mlir.py` and call `make OMONNXOpsIncTranslation` as documented here: http://onnx.ai/onnx-mlir//ImportONNXDefs.html

**Comment by AlexandreEichenberger** [comment]
>Jenkins failed because you edited ONNXOps.td.inc that was automatically generated. Instead, please update gen_onnx_mlir.py and call make OMONNXOpsIncTranslation as documented here: http://onnx.ai/onnx-mlir//ImportONNXDefs.html

Correct, good catch. Happy to help if you need it to edit and rebuild the .td.inc file

**Comment by negiyas** [comment]
@tungld @AlexandreEichenberger Thank you for the comment. I am updating it.

**Comment by negiyas** [comment]
All tests except CircleCI are passed.
I suppose that this PR is "ready to merge," although I cannot push the "Labels" button, because I do not have the permission probably.
Please let me know if you have comments on this PR. Thank you.

**Pull request merged**
