### PR TITLE
Use output shape when lowering Unique to krnl

### PR DESCRIPTION
**Pull request by chentong319**
This issue is discovered by #2799 . It may not be considered a bug in lowering. The issue is triggered by two imperfect components: onnx backend test and buffer deallocation.

1.  onnx backend test
The output shape of Unique OP depends on the content of the input tensor. But the onnx backend test creates the onnx model based on the chosen input. Therefore, the output shape is static. I opened an [issue in onnx]( https://github.com/onnx/onnx/issues/6133).

2. Buffer deallocation
Due to  the mismatch of the generated and specified type of the outputs UniqueOp, the existing lowering of Unique created some unrealized_conversion_cast ops. The deallocation pass in the new llvm can not handle the conversion for returned tensors correctly. 

Anyway, I try to fix the problem from onnx-mlir with this PR. I use the type of the outputs for allocation if the type is static.

### CODE REVIEW

**Comment by negiyas** [comment]
@chentong319 Your fixes look good to me! Thank you so much for fixing lowering Unique to krnl.

**Comment by chentong319** [comment]
> @chentong319 Your fixes look good to me! Thank you so much for fixing lowering Unique to krnl.

Could you approve the PR?

**Comment by hamptonm1** [comment]
> > @chentong319 Your fixes look good to me! Thank you so much for fixing lowering Unique to krnl.
> 
> Could you approve the PR?

@chentong319 Since @negiyas said this looks good, I will make sure to merge this in for you :)

**Review by hamptonm1 — APPROVED** [review]
LGTM!

**Pull request merged**
