### PR TITLE
Allow to change tolerance in numerical tests

### PR DESCRIPTION
**Pull request by negiyas**
Allow to change tolerance in numerical tests by the "TEST_RTOL" and "TEST_ATOL" environments.
If they are not set, default values 1e-5 for rtol, and 1e-5 for atol, those are default values of omTensorAreTwoOmtsClose, are used.

### CODE REVIEW

**Review by tjingrant — APPROVED** [review]
LGTM.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by negiyas** [comment]
> @jenkins-droid test this please.

@tjingrant Thank you for testing. It seems that the testing environment for s390x is broken. The following same errors occur in all PRs. Can you check it?

+ docker run -itd --name onnx-mlir-test onnx-mlir-build:s390x
docker: Error response from daemon: Conflict. The container name "/onnx-mlir-test" is already in use by container "778d9c8dd9271c630b96cb509cfe1ca30a67fa7eafe9212e8831978240cf5575". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Build step 'Execute shell' marked build as failure

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@negiyas yes, the jenkins docker test is not configured to be a required test.

**Pull request merged**
