### PR TITLE
Enable CMAKE_EXPORT_COMPILE_COMMANDS to generate compile_commands.json.

### PR DESCRIPTION
**Pull request by nkreeger**
Ensures better auto-complete and IDE integration with CMake - NFC.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
@nkreeger please familiarize yourself with our DCO policy, its on our main readme towards the end. It is required to contribute code. Tx

**Comment by nkreeger** [comment]
> @nkreeger please familiarize yourself with our DCO policy, its on our main readme towards the end. It is required to contribute code. Tx

ACK - agreed to DCO.

Signed the commit as well.

**Comment by AlexandreEichenberger** [comment]
> ACK - agreed to DCO.

Thanks. No need to generate a new PR for this, we can override the DCO once you acknowledged it as you did above. But please sign all commit in the future, it makes everyone's life easier. Thanks

**Comment by nkreeger** [comment]
> > ACK - agreed to DCO.
> 
> Thanks. No need to generate a new PR for this, we can override the DCO once you acknowledged it as you did above. But please sign all commit in the future, it makes everyone's life easier. Thanks

Roger will do - thanks!

**Comment by AlexandreEichenberger** [comment]
@gongsu832 you probably have an opinion. It currently passes all the tests

**Review by gongsu832 — APPROVED** [review]
LGTM

**Pull request merged**
