### PR TITLE
Added compiler interface to python

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
Added python module to compile models as well as example and doc.

Mnist example is now able to compile as well.

``` python
import numpy as np
from PyRuntime import ExecutionSession
from PyOnnxMlirCompiler import OnnxMlirCompiler, OnnxMlirTarget, OnnxMlirOption

# Load onnx model and create Onnx Mlir Compiler object.
# Compiler needs to know where to find its runtime. Set ONNX_MLIR_RUNTIME_DIR
# to proper path.
# export ONNX_MLIR_RUNTIME_DIR=../../build/Debug/lib
file = './mnist.onnx'
compiler = OnnxMlirCompiler(file)
# Set optimization level to -O3.
compiler.set_option(OnnxMlirOption.opt_level, "3")
#compiler.set_option(OnnxMlirOption.verbose, "")
print("Compile", file, "with opt level", compiler.get_option(OnnxMlirOption.opt_level), "for arch", compiler.get_option(OnnxMlirOption.target_arch), "and CPU", compiler.get_option(OnnxMlirOption.target_cpu))
# Generate the library file. Success when rc == 0.
rc = compiler.compile('./mnist-O3', OnnxMlirTarget.emit_lib)
model = compiler.get_output_file_name()
if rc:
    print("Failed to compile with error code", rc)
    exit(1)
print("Compiled onnx file", file, "to", model, "with rc", rc)
# Load the model mnist.so compiled with onnx-mlir.
session = ExecutionSession(model)
# Print the models input/output signature, for display.
# Signature functions for info only, commented out if they cause problems.
print("input signature in json", session.input_signature())
print("output signature in json",session.output_signature())
...
```

Signed-off-by: Alexandre Eichenberger <alexe@us.ibm.com>

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
Request for help: in the CmakeList.txt for target `PyOnnxMlirCompiler`, which compile the new interface, I was not able to have the include set rights for the `onnx-mlir/include` paths. As a result, I had to manually add the `include` to the files that are found there.
I would appreciate input on how to fix that. Maybe @gongsu832 ?

**Comment by sstamenova** [comment]
> Request for help: in the CmakeList.txt for target `PyOnnxMlirCompiler`, which compile the new interface, I was not able to have the include set rights for the `onnx-mlir/include` paths. As a result, I had to manually add the `include` to the files that are found there. I would appreciate input on how to fix that. Maybe @gongsu832 ?

@AlexandreEichenberger : Can you put a comment on the lines you are referring to? As far as I can tell, you are setting the include directories based on properties from `onnx`, is that the place you mean? `pybind11_add_module` adds a library, so you should be able to add its dependencies as `target_link_libraries` and get the properties inherited (assuming you actually want to link against `onnx` or `onnx_proto`).

**Comment by tungld** [comment]
Would it be easier for users to use a single class, say ExecutionSession, instead of two classes? Inspired by TensorFlow Keras (https://www.tensorflow.org/guide/effective_tf2), I image something like this:
```python
sess = OMSession("model.onnx")
copt = OMCompilerOptions()
copt.opt_level = 3
copt.maccel = NNPA
sess.compile(copt)
sess.run(inputs)
```
In the future we may have `sess.fit` before `sess.run` like `fit` in Keras, to prepare data for inference.

**Comment by gongsu832** [comment]
Just so we don't duplicate efforts, we have an OMP (Open Mainframe Project) student who is looking into this. @AlexandreEichenberger if you want we can have the student work with you on this.

**Comment by AlexandreEichenberger** [comment]
@sstamenova 
``` 
pybind11_add_module(PyOnnxMlirCompiler PyOnnxMlirCompiler.cpp)
add_dependencies(PyOnnxMlirCompiler onnx_proto)
target_compile_definitions(PyOnnxMlirCompiler
  PRIVATE
  $<TARGET_PROPERTY:onnx,COMPILE_DEFINITIONS>
  )
target_include_directories(PyOnnxMlirCompiler
  PRIVATE
  $<TARGET_PROPERTY:onnx,INCLUDE_DIRECTORIES>
  )
target_link_libraries(PyOnnxMlirCompiler
  PRIVATE
  OnnxMlirCompiler
  )

install(TARGETS PyOnnxMlirCompiler
  DESTINATION lib
  )
```
 I literally copied this, the offending lines is probably where it say to include
```
  $<TARGET_PROPERTY:onnx,INCLUDE_DIRECTORIES>
```
but I really don't understand the syntax. What I need is that the regular `onnx-mlir/include` dir be included.

**Comment by AlexandreEichenberger** [comment]
@tungld 

>Would it be easier for users to use a single class, say ExecutionSession, instead of two classes? Inspired by TensorFlow Keras (https://www.tensorflow.org/guide/effective_tf2), I imagine something like this

I though about it, would we worry that now the execution session includes the entire compiler? Right now, execution session is very very lean (basically a minor extension to the runtime). If we pull the entire compiler, then every execution session becomes the entire onnx-mlir image.

Aside that issue, I would indeed prefer a single class as it is more elegant.

**Comment by AlexandreEichenberger** [comment]
> Just so we don't duplicate efforts, we have an OMP (Open Mainframe Project) student who is looking into this. @AlexandreEichenberger if you want we can have the student work with you on this.

You mentioned that the student was not likely going to do this. If he wants to take this one over, he is welcome to take this PR as a base to do it. Note that this PR also add a few unrelated things, like a new `verbose` option, that can be isolated easily.

**Comment by sstamenova** [comment]
```
target_include_directories(PyOnnxMlirCompiler
  PRIVATE
  $<TARGET_PROPERTY:onnx,INCLUDE_DIRECTORIES>
  )
```

means set the include directories of `PyOnnxMlirCompiler` to the `INCLUDE_DIRECTORIES` property of the `onnx` target. It sounds like that's not what you want since you just want the regular include directory (this is also probably true for the compile definitions).

I would expect when you add OnnxMlirCompiler as a link library for that to import the regular include directories. Does it not work if you only leave that command?
```
target_link_libraries(PyOnnxMlirCompiler
  PRIVATE
  OnnxMlirCompiler
  )
```

**Comment by gongsu832** [comment]
> > Just so we don't duplicate efforts, we have an OMP (Open Mainframe Project) student who is looking into this. @AlexandreEichenberger if you want we can have the student work with you on this.
> 
> You mentioned that the student was not likely going to do this. If he wants to take this one over, he is welcome to take this PR as a base to do it. Note that this PR also add a few unrelated things, like a new `verbose` option, that can be isolated easily.

I guess there was some misunderstanding. I said that the student was not likely going to do more complicated things such as developing python tool to analyze the model, etc. This PR is exactly what the student is trying to do. I will point him to this PR so efforts can be consolidated.

**Comment by AlexandreEichenberger** [comment]
@sstamenova got it to work with this
```
target_include_directories(PyOnnxMlirCompiler
  PRIVATE
  ${ONNX_MLIR_SRC_ROOT}/include
  )
```
so this issue is now resolved. Thanks for the nudge in the right direction.

**Comment by AlexandreEichenberger** [comment]
> This PR is exactly what the student is trying to do. I will point him to this PR so efforts can be consolidated.

yes, I fixed the include issue and the student can take over. I think it would be nice to resolve the high level issues with consensus from the community (e.g. merged into exec session or two different classes). Once that is done, this code base should be a good start toward achieving the goals.

**Comment by tungld** [comment]
>  how do we "clear" the options?

How about using `None` to reset an option, something like this:
```python
class OMCompilerOption(object):
    opt_level = None
    maccel = None

    # change attribute values.
    def __setattr__(self, name, value):
        self.__dict__[name] = value
        if value is None:
            # call the python wrapper of C++ clear_option
            print("clear option", name)
        else:
            # call the python wrapper of C++ set_option
            print("set option", name, value)

    def __getattribute__(self, name):
        # calling the super class to avoid recursion
        value = super(OMCompilerOption, self).__getattribute__(name)

        # just for testing: to mimic calling C++ get_option
        default_options = {"opt_level": 0, "maccel": None}
        if name not in default_options:
            return value
        if value is None:
            # call the python wrapper of C++ get_option, and return the value
            value = default_options[name]

        print("get option", name, value)
        return value

    # Reset all attribute values.
    def reset(self):
        self.opt_level = None
        self.maccel = None

copt = OMCompilerOption()
copt.opt_level
copt.maccel

print()
copt.opt_level = 3
copt.maccel = "NNPA"
copt.opt_level
copt.maccel

print()
copt.opt_level = None
copt.opt_level
copt.maccel

print()
copt.reset()
copt.opt_level
copt.maccel
```
which will output
```bash
get option opt_level 0
get option maccel None

set option opt_level 3
set option maccel NNPA
get option opt_level 3
get option maccel NNPA

clear option opt_level
get option opt_level 0
get option maccel NNPA

clear option opt_level
clear option maccel
get option opt_level 0
get option maccel None
```

**Comment by AlexandreEichenberger** [comment]
@tungld I like it. Since right now all of our interface is code written in C++ plus the exported interface through PyBind, we may have to write this in C++ and add the interface in PYBIND11 stuff.

Also, we are still having the "issue" that the interface we provide is confusing.

say we have (loosely written)

```python
copt1= OMCompilerOptions()
copt1.opt_level = 3
copt1.maccel = NNPA
sess1.compile(copt1)

# sometime later with a sess2

copt2= OMCompilerOptions()
sess2.compile(copt2)
```

The second compile is still working under the first set of optimizations, as the optimization flags in onnx-mlir are global. 

One approach to that is to "clear" all global options when creating a new `OMCompilerOptions`.

The final issue is that these are not thread safe.... for that we could simply use locks implicitly, or declare it thread unsafe and rely on the user to add locks, or make all global switches thread_local... which works relatively well (but I think zOS may have a different mechanism... which we would have to look into). Probably simplest to declare the compile/option thread unsafe.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 can you encourage your student to chime in, or would you like him to come at tonight's meeting and we can discuss it?

**Comment by AlexandreEichenberger** [comment]
no functionality changes, just merged with the latest and removed errand spaces.

**Comment by Jiaqing-ASU** [comment]
> @gongsu832 can you encourage your student to chime in, or would you like him to come at tonight's meeting and we can discuss it?

@AlexandreEichenberger Hello Alexandre, I am the student in the OMP (Open Mainframe Project) program which @gongsu832 mentioned before. Nice to meet you! I see the "include" issue has already been sovled. To "clear all global options", maybe for now, we can just have a function which sets all the options to None as @tungld mentioned and we have to declare the compile thread unsafe. And after this PR is merged, I will fork the repo and continue working on this. Is my understanding right?

**Comment by AlexandreEichenberger** [comment]
> @AlexandreEichenberger Hello Alexandre, I am the student in the OMP (Open Mainframe Project) program which @gongsu832 mentioned before. Nice to meet you! I see the "include" issue has already been sovled. To "clear all global options", maybe for now, we can just have a function which sets all the options to None as @tungld mentioned and we have to declare the compile thread unsafe. And after this PR is merged, I will fork the repo and continue working on this. Is my understanding right?

Nice to hear from you. Would you mind calling in our weekly meeting tonight at 8pm est so that you can express also your views as we discuss this interface? 

I can push this one and then you take from there, if that is your preference. It looks like the final solution will be a bit different.

**Comment by Jiaqing-ASU** [comment]
> Nice to hear from you. Would you mind calling in our weekly meeting tonight at 8pm est so that you can express also your views as we discuss this interface?

Actually I do not have many views to share but I am glad to join the meeting to learn. Could you please add me to the meeting? My email is: jchen501@asu.edu

**Comment by Jiaqing-ASU** [comment]
> I can push this one and then you take from there, if that is your preference. It looks like the final solution will be a bit different.

@AlexandreEichenberger Hello Alexandre, I am thinking to prepare my own PR which incorporates changes in this PR so you do not need to merge this PR and this could be closed eventually once you have my new PR merged. How do you think about this plan?

**Comment by AlexandreEichenberger** [comment]
> I like it better. You can simply download the patch, and the commit it under a different one that you own.

**Comment by AlexandreEichenberger** [comment]
Closed as @Jiaqing-ASU is taking this task over

**Pull request closed without merging**
