### PR TITLE
set CMAKE_CXX_STANDARD=17 in llvm build instructions

### LINKED ISSUE #1619: llvm build fails on Mac after llvm commit update
UPDATE: the originally reported issue is no longer reproducible but there's a new build issue reported in the comments below

after updating the llvm commit in PR #1599 and follow the instructions in [BuildOnLinuxOSX.md](https://github.com/onnx/onnx-mlir/blob/main/docs/BuildOnLinuxOSX.md):
```
mkdir llvm-project/build
cd llvm-project/build
cmake -G Ninja ../llvm \
   -DLLVM_ENABLE_PROJECTS=mlir \
   -DLLVM_TARGETS_TO_BUILD="host" \
   -DCMAKE_BUILD_TYPE=Release \
   -DLLVM_ENABLE_ASSERTIONS=ON \
   -DLLVM_ENABLE_RTTI=ON

cmake --build . -- ${MAKEFLAGS}
```
I experience the following compile error on Mac:
```
/Users/sorenlassen/git/llvm-project/mlir/include/mlir/IR/OpDefinition.h:1497:5: error: no template named 'disjunction' in namespace 'std'; did you mean 'llvm::disjunction'?
    std::disjunction<detect_has_fold_trait<T>,
    ^~~~~~~~~~~~~~~~
    llvm::disjunction
/Users/sorenlassen/git/llvm-project/llvm/include/llvm/ADT/STLForwardCompat.h:41:8: note: 'llvm::disjunction' declared here
struct disjunction // NOLINT(readability-identifier-naming)
```
plus a bunch of "... is a C++17 extension" warnings

### PR DESCRIPTION
**Pull request by sorenlassen**
closes #1619

Signed-off-by: Soren Lassen <sorenlassen@gmail.com>

### CODE REVIEW

**Comment by sstamenova** [comment]
This change should not be necessary. The default version in llvm (at that commit) is:

```set(CMAKE_CXX_STANDARD 17 CACHE STRING "C++ standard to conform to")```

Were you perhaps building a different llvm commit or the build wasn't clean?

**Review by sstamenova — CHANGES_REQUESTED** [review]
This should not be needed, let's figure out why it was.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by sorenlassen** [comment]
I don't see this anymore, maybe it went away with the further llvm update in PR #1628

**Pull request closed without merging**
