### PR TITLE
introduce cmake option ONNX_MLIR_DECOMP_ONNX_CONVTRANSPOSE

### PR DESCRIPTION
**Pull request by sorenlassen**
This is needed for Groq to disable this.

### CODE REVIEW

**Comment by imaihal** [comment]
@sorenlassen Does the Groq have own implementation or rewriting for ConvTranspose op?

**Comment by sorenlassen** [comment]
> @sorenlassen Does the Groq have own implementation or rewriting for ConvTranspose op?

yes, we lower it to Groq's internal dialect

we don't support ONNXReverseSequenceOp at the moment so we can't compare the performance of your decomposition with Groq's lowering

**Review by philass — APPROVED** [review]
Thanks for unblocking.

I think this is a relatively concise hack for opting in and out of this decomposition for different downstream users.

We can leave this in while we investigate torch-mlir style opt in and out decompositions that the AMD folks mentioned in the weekly meeting.

**Comment by tungld** [comment]
It's unfortunate to have this PR merged in hurry. It's quite weird to deal with a specific operation using this way, saying using CMake. We should discuss a better solution that uses MLIR infrastructure.

**Comment by philass** [comment]
Hey @tungld,

Sorry for rushing this into the codebase. The AMD folk have kindly opened an issue where we can discuss a robust way of solving the decomposition issue https://github.com/onnx/onnx-mlir/issues/2105.

We were hoping to be able to use a short term fix while we figured out the best way to solve the problem in the long run. Sorry for not giving you enough time to review the PR. 

I sent you a slack message as well if you want to discuss this with me further.

**Comment by tungld** [comment]
@philass thanks for the information! Got it.

**Pull request merged**
