### PR TITLE
Make OptLevel option sharable

### PR DESCRIPTION
**Pull request by tungld**
This patch allows other drivers to use the OptLevel option.

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Review by etiotto — APPROVED** [review]
LGTM

**Review by AlexandreEichenberger — CHANGES_REQUESTED** [review]
I like it, I also think that I may have used the variable directly here and there. Do you mind searching for these usages and replacing with the interface you are suggesting? Thanks

**Comment by tungld** [comment]
> Do you mind searching for these usages and replacing with the interface you are suggesting? 

Yes, sure. I found two direct usages and changed them.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for the changes

**Pull request merged**
