### PR TITLE
Add tosa builder

### PR DESCRIPTION
**Pull request by maxbartel**
As discussed in https://github.com/onnx/onnx-mlir/pull/1949#discussion_r1081693837 I wanted to bring in a `DialectBuilder` for the TOSA Dialect. We will gradually add more functionality.

Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by maxbartel** [comment]
@AlexandreEichenberger thank you for the review! I have addressed all comments

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
Let me know if you want it merged once it passes all of the CIs

**Comment by maxbartel** [comment]
In general, you can always merge my PRs if they pass all pipelines. Thank you!

**Comment by philass** [comment]
@maxbartel,

I rebased your branch and was going to merge it once it passed the pipeline.

Unfortunately the pipelines failed. It looks like some issue pulling the sources for the test. Most likely something unrelated to this PR.

**Comment by maxbartel** [comment]
@AlexandreEichenberger Could you please restart the CI? I think @philass is right and the failures is unrelated to this PR

**Comment by philass** [comment]
@maxbartel it looks like its because of this https://github.com/onnx/onnx/issues/4857

**Comment by maxbartel** [comment]
@philass I see, thank you!

**Pull request merged**
