### PR TITLE
add the pattern support for scatterND op in constant folding pass

### PR DESCRIPTION
**Pull request by DavidChan0519**

### CODE REVIEW

**Review by chentong319 — COMMENTED** [review]
1. Be aware of that ONNX constants may be in buffer format in constant folding pass. No document for that yet. But you can find relevant code, such as getArrayFromAttributeOrBuffer, in ConstProp.cpp. Those utility functions could help you.
2. Is there a particular reason that table gen (ConstProp.td) is not used for this pattern? Or just personal preference?

**Comment by tungld** [comment]
I agree with @chentong319's comments. I am sorry that there is no document about the infrastructure for constant propagation at this time. Please look at the comment at the beginning of ConstProp.cpp and follow one of the examples.

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by DavidChan0519** [comment]
> propagation

Got it!. I will follow the style of the example at the beginning.

**Comment by DavidChan0519** [comment]
> 1. Be aware of that ONNX constants may be in buffer format in constant folding pass. No document for that yet. But you can find relevant code, such as getArrayFromAttributeOrBuffer, in ConstProp.cpp. Those utility functions could help you.
> 2. Is there a particular reason that table gen (ConstProp.td) is not used for this pattern? Or just personal preference?

thanks for your comment, I will refactor this part and submit it once again.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@DavidChan0519 I wrote a document about constant propagation in this PR #1004. Hope it help.

**Comment by DavidChan0519** [comment]
> @DavidChan0519 I wrote a document about constant propagation in this PR #1004. Hope it helps.

thanks!

**Pull request closed without merging**
