### PR TITLE
Added CI configuration for x86 macOS

### PR DESCRIPTION
**Pull request by mshr-h**
Added macOS CI configuration.
#252

### CODE REVIEW

**Review by tjingrant — APPROVED** [review]
LGTM, thanks!

**Comment by tjingrant** [comment]
@mshr-h I invoked the mac os build twice, it seems like it's not making use of the MLIR cache?

**Comment by mshr-h** [comment]
@tjingrant You means [this one](https://github.com/onnx/onnx-mlir/actions/runs/240408199) and [this one](https://github.com/onnx/onnx-mlir/actions/runs/240492662)?
My understanding is that if build was failed, `actions/cache` doesn't cache anything.
So, once build succeeded, caching will work.
I found [stackoverflow](https://stackoverflow.com/questions/60491837/saving-cache-on-job-failure-in-github-actions) post which mentions similar behavior of `actions/cache`.

It looks like testing is failed but I'm not sure why it happens.

**Comment by tjingrant** [comment]
@mshr-h it seems like caching isn't fully working yet?
c.f. log here: https://github.com/onnx/onnx-mlir/pull/287/checks?check_run_id=1092414205

Seems like the cached files are not restored.

**Comment by mshr-h** [comment]
@tjingrant I checked the below log and it looks like cache key collision was occured. I'll try to find the way to solve it ASAP.

[Merge branch 'master' into pr-add-macos-ci · onnx/onnx-mlir@472b531](https://github.com/onnx/onnx-mlir/runs/1092073891?check_suite_focus=true)
```
 Post cache MLIR directory
[warning]reserveCache failed: Cache already exists. Scope: refs/pull/287/merge, Key: macOS-build-cache-mlir-directory-9530df47a7667c57417ee817992e9114e00b1c649326d0aa871eae059a503898, Version: 40e68259f83fefa397b9a495fd46a09d779d54f12e7acec4bdc3dda75418c01b
```

**Comment by tjingrant** [comment]
@mshr-h my guess is that when two jobs run concurrently building cached directories for the first time, they interfere with one another. If this is the cases, we can either ask folks to be aware of this pitfall, or have some mechanisms to cancel redundant jobs.

**Comment by mshr-h** [comment]
@tjingrant I think you're right. I found the similar issue [here](https://github.com/actions/cache/issues/144).
I read through the discussion and there's no way to avoid this issue. 
But there are workarounds here:
- Change the cache key.
- Wait 7 days, and don't use that cache entry.

I think we have 2 choices:
- Every time we hit this issue, manually change the cache key.
- Not use cache mechanism.

Even though it takes much longer build time (15 min vs 1 hour), I suggest not to use the cache mechanism.
What do you think? @tjingrant

**Comment by caoimhinuibrian** [comment]
@gongsu832 Is there a reason the s390x builds are not reporting?

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please.

**Comment by mshr-h** [comment]
It looks like caching is working but restoring the cache is failing.
I'll try to find out the cause of the problem.

- First CI run.
  - https://github.com/onnx/onnx-mlir/runs/1216548809?check_suite_focus=true
- Second CI run.
  - https://github.com/onnx/onnx-mlir/runs/1218038641?check_suite_focus=true

**Comment by mshr-h** [comment]
@tjingrant 
The CI error was fixed. I think this should be good.
Could you review it when you have a time?

The error was occurred because '$HOME' was in the path.
After replacing '$HOME/' with '~/', the error was fixed.

Below are CI log: 
- First CI run
  - https://github.com/onnx/onnx-mlir/runs/1251430352?check_suite_focus=true
- Second CI run
  - https://github.com/onnx/onnx-mlir/runs/1252212966?check_suite_focus=true

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
