### PR TITLE
Ignore splat in krnl constant packing (--pack-krnl-constants)

### PR DESCRIPTION
**Pull request by imaihal**
Krnl constant packing (`--pack-krnl-constants`) didn't work correctly when dense attribute is a splat as shown below.

- Example
   - `value = dense<0.000000e+00> : tensor<1x4xf32>` is a splat, and all elements of the tensor is the same
```
func @test_krnl_const_packing_file_splat() -> memref<1x4xf32> {
  %0 = "krnl.global"() {name = "constant_0", shape = [1, 4], value = dense<0.000000e+00> : tensor<1x4xf32>} : () -> memref<1x4xf32>
  %1 = "krnl.global"() {name = "constant_1", shape = [1, 4], value = dense<0.000000e+00> : tensor<1x4xf32>} : () -> memref<1x4xf32>
  return %1 : memref<1x4xf32>
```

- Output of current master (Command: `onnx-mlir-opt --pack-krnl-constants='elision-threshold=3 move-to-file=true filename=test-pack-consts-to-file-splat.bin' `)
   - `size_in_bytes = 8` means only 2 elements are included in the file. 
   - Since offset of second `krnl.global` is 4, the number of element in dense attribute is considered to be one.
```
module  {
  %0 = "krnl.packed_const"() {file_name = "test-pack-consts-to-file-splat.bin", is_le = false, size_in_bytes = 8 : i64} : () -> i64
  func @test_krnl_const_packing_file_splat() -> memref<1x4xf32> {
    %1 = "krnl.global"() {name = "constant_0", offset = 0 : i64, shape = [1, 4]} : () -> memref<1x4xf32>
    %2 = "krnl.global"() {name = "constant_1", offset = 4 : i64, shape = [1, 4]} : () -> memref<1x4xf32>
    return %2 : memref<1x4xf32>
  }
}
```
- Output by this PR
   - Ignores the packing when the attribute is a splat.
```
module  {
  %0 = "krnl.packed_const"() {file_name = "test-pack-consts-to-file-splat.bin", is_le = false, size_in_bytes = 0 : i64} : () -> i64
  func @test_krnl_const_packing_file_splat() -> memref<1x4xf32> {
    %1 = "krnl.global"() {name = "constant_0", offset = 0 : i64, shape = [1, 4], value = dense<0.000000e+00> : tensor<1x4xf32>} : () -> memref<1x4xf32>
    %2 = "krnl.global"() {name = "constant_1", offset = 0 : i64, shape = [1, 4], value = dense<0.000000e+00> : tensor<1x4xf32>} : () -> memref<1x4xf32>
    return %2 : memref<1x4xf32>
  }
}
```

### CODE REVIEW

**Comment by tjingrant** [comment]
@imaihal why is the offset of the second krnl.global op 0 as well?

```
    %2 = "krnl.global"() {name = "constant_1", offset = 0 : i64, shape = [1, 4], value = dense<0.000000e+00> : tensor<1x4xf32>} : () -> memref<1x4xf32>
```

Did they get merged somehow?

**Comment by imaihal** [comment]
@tjingrant Thanks for your review.
This PR only changes the conditions under which constant packing is done. When dense attribute has splat, it is not done. The results when it is not done is the same as original code.
  
The output of [test/mlir/krnl/pack_krnl_consts_to_file.mlir](https://github.com/onnx/onnx-mlir/blob/master/test/mlir/krnl/pack_krnl_consts_to_file.mlir) is as follows. Constant packing is done and 4 bytes are included in the file. So, the offset of second krnl.global is 16. 

```
module  {
  %0 = "krnl.packed_const"() {file_name = "test-pack-consts-to-file-splat.bin", is_le = false, size_in_bytes = 32 : i64} : () -> i64
  func @test_krnl_const_packing_file() -> memref<1x4xf32> {
    %1 = "krnl.global"() {name = "constant_0", offset = 0 : i64, shape = [1, 4]} : () -> memref<1x4xf32>
    %2 = "krnl.global"() {name = "constant_1", offset = 16 : i64, shape = [1, 4]} : () -> memref<1x4xf32>
    return %1 : memref<1x4xf32>
  }
}
```
However, when I changed `elision-threshold` to `5`, the constant packing is not done as follows. In this case, the offset of second krnl.global is 0. I thought this means the value is not included in the file. The value in the attribute (` dense<[[0.000000e+00, 1.000000e+00, 2.000000e+00, 3.000000e+00]]`) is used instead.
```
module  {
  %0 = "krnl.packed_const"() {file_name = "test-pack-consts-to-file-splat.bin", is_le = false, size_in_bytes = 0 : i64} : () -> i64
  func @test_krnl_const_packing_file() -> memref<1x4xf32> {
    %1 = "krnl.global"() {name = "constant_0", offset = 0 : i64, shape = [1, 4], value = dense<[[0.000000e+00, 1.000000e+00, 2.000000e+00, 3.000000e+00]]> : tensor<1x4xf32>} : () -> memref<1x4xf32>
    %2 = "krnl.global"() {name = "constant_1", offset = 0 : i64, shape = [1, 4], value = dense<[[0.000000e+00, 1.000000e+00, 2.000000e+00, 3.000000e+00]]> : tensor<1x4xf32>} : () -> memref<1x4xf32>
    return %1 : memref<1x4xf32>
  }
}
```

**Comment by tjingrant** [comment]
@imaihal Thanks for the explanation! The printing of `krnl.global` operations can certainly be improved.

**Comment by tjingrant** [comment]
On the other hand, CI seems to be failing, it looks like you need to start the test with a CHECK-LABEL as in here:
https://github.com/onnx/onnx-mlir/blob/bced3a22df7bc6401be4ea3d4d0ffe486c69990c/test/mlir/onnx/onnx_shape_inference.mlir#L14

**Comment by imaihal** [comment]
@tjingrant Thanks for your comment.
I found I used `is_le = false` in `krnl.packed_const` because I used s390x for development. It took time to find it... 
I hope all tests pass now.

**Review by tjingrant — APPROVED** [review]
LGTM, thanks for answering my questions!

**Pull request merged**
