### PR TITLE
Add ViewLikeOpInterface to krnl.vector_type_cast

### PR DESCRIPTION
**Pull request by tungld**
`krnl.vector_type_cast` op is a view of the source memref, so this patch adds ViewLikeOpInterface to it. 

Though the current onnx-mlir has no problem since `krnl.vector_type_cast` is only used inside MatMul, this change helps buffer-related passes correctly analyze buffer's lifetime when `krnl.vector_type_cast` is used more often.

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Review by etiotto — APPROVED** [review]
LGTM - thanks!

**Comment by etiotto** [comment]
@tungld  I saw that the `Krnl` dialect also has another op that is cast like `KrnlDummyCastOp`.  At first glance that op should also implement the `ViewLikeOpInterface`, what do you think?

**Comment by tungld** [comment]
> @tungld I saw that the Krnl dialect also has another op that is cast like KrnlDummyCastOp. At first glance that op should also implement the ViewLikeOpInterface, what do you think?

Thanks for pointing it out! I just looked at KrnlDummyCastOp. It is used internally as a supporting op in lowering ONNX Loop and Scan, then it disappears by canonicalization. I think we have no problem with it.

**Comment by AlexandreEichenberger** [comment]
@tungld Thanks. Out of curiosity, what does adding this interface buy us?

**Pull request merged**
