### PR TITLE
LLVM Update to green commit for the week of 7/24/2023

### PR DESCRIPTION
**Pull request by mikeessen**
LVM Update to green commit for the week of 7/24/2023

This is using the green commits that match torch-mlir and that are published in the Torch-MLIR github project: https://github.com/llvm/torch-mlir/issues/1178

Green LLVM commit: 438fc2c83b73e66f6dbae4f34e9a19f41302f825
Green MHLO commit: 2240bd4c1ed420e91613d5d623414b65ddbba7bf (branch greencommit/2023-07-24-438fc2c8)

### CODE REVIEW

**Comment by mikeessen** [comment]
@jenkins-droid test this please

**Comment by mikeessen** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — COMMENTED** [review]
LGTM, thanks

**Comment by mikeessen** [comment]
> LGTM, thanks

@AlexandreEichenberger Thank you!  Please also mark approved.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Pull request merged**
