### PR TITLE
Create zDNN Status Message Environment variable

### PR DESCRIPTION
**Pull request by hamptonm1**
Creating a zDNN status message environment variable and setting the default to `0` or `OFF` which means no zDNN status messages will get printed but when the value is changed to `1` or `ON` we will print out the status of the zDNN APIs if there is a failure (so when there is no ZDNN_OK status).

### CODE REVIEW

**Comment by hamptonm1** [comment]
@tungld @chentong319 Do you guys have any ideas as to how to test this new env variable? I wanted to add a little test in here for verification purposes, let me know your thoughts :)

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks

**Comment by chentong319** [comment]
In zDNN, the check the status is defined with a #define. You may use the similar approach to simplify your code.
Code are in zdnn_private.h:
```
#define ZDNN_STATUS(status, format, ...)                                       \
  set_zdnn_status(status, __func__, __FILE__, __LINE__, format, __VA_ARGS__)
```

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@chentong319 @tungld Okay I tested my changes and everything works as expected (for the test below I change `status!= ZDNN_OK` to `status == ZDNN_OK` to see the results until I can trigger a proper error messages  :

```
root@bf3259c9b6e0:/workdir/original/onnx-mlir/build# OM_STATUS_MESSAGES_ENABLED=1 ONNX_M
LIR_HOME=/workdir/original/onnx-mlir/build/Debug python3 ../utils/RunONNXModel.py -m=tes
t_softmax_example.onnx -c="-O3 --mcpu=z17 --maccel=NNPA"
Temporary directory has been created at /tmp/tmpt3nehhxl
Compiling the model ...
  took  0.19100154202897102  seconds.

Loading the compiled model ...
  took  0.00012370594777166843  seconds.

Generating random inputs using seed 42 ...
  - 1st input's shape (1, 3), element type float32. Value ranges [-0.1, 0.1]
  done.

Running inference ...
OM_STATUS_MESSAGES_ENABLED: 1
[zdnnx] zdnn_softmax : ZDNN_OK: Success.
  1st iteration, 0.00010546704288572073, seconds
```

**Review by tungld — APPROVED** [review]
LGTM. Thanks!

**Review by chentong319 — COMMENTED** [review]
LGTM!

**Pull request merged**
