### PR TITLE
Fix folder structure difference between installed LLVM and built-from-source LLVM

### PR DESCRIPTION
**Pull request by KeDengMS**
* make mlir-tblgen import conditional to avoid potential conflict with other MLIR-based repos
* remove unnecessary link to onnx in OMSupport

### CODE REVIEW

**Comment by gongsu832** [comment]
test this please

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by KeDengMS** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Review by tjingrant — APPROVED** [review]
LGTM!

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
