### PR TITLE
Fix security vulenrabilities

### PR DESCRIPTION
**Pull request by Sunny-Anand**
Fix security vulnerabilities in requirements.txt for mnist example 

- https://github.com/advisories/GHSA-44wm-f244-xhp3 for pillow
- https://github.com/advisories/GHSA-9v5x-r4g7-gqw3 torch package
- https://github.com/advisories/GHSA-vmg3-jxcp-7rqw  for torch package
- https://github.com/advisories/GHSA-pg7h-5qx3-wjr3  for torch package
- https://github.com/advisories/GHSA-5pcm-hx3q-hm94 for torch package
- Update torchvision package to match torch version.

### CODE REVIEW

**Comment by Sunny-Anand** [comment]
FYI @christopherlmunoz

**Review by mikeessen — APPROVED** [review]
LGTM!

**Comment by Sunny-Anand** [comment]
@jenkins-droid Test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks

**Comment by Sunny-Anand** [comment]
@jenkins-droid Test this please

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Comment by Sunny-Anand** [comment]
@jenkins-droid test this please

**Pull request merged**
