### PR TITLE
Support LLVM as of 7dcd0042

### PR DESCRIPTION
**Pull request by NathanielMcVicar**
Fixes for upstream changes to mlir as of 7dcd0042e8b8581751bd9b915207058d2ab88e1d.

- New pass registration method from https://reviews.llvm.org/D85622
- Integer attributes are now C types when possible https://reviews.llvm.org/D86739

### CODE REVIEW

**Comment by NathanielMcVicar** [comment]
@caoimhinuibrian Created as per discussion in #304.

**Comment by NathanielMcVicar** [comment]
Nightly on Travis is passing now.

**Comment by tjingrant** [comment]
@NathanielMcVicar we use Travis to refresh prerequisite docker containers on DockerHub; to do that I can give you a temporary push access, and you will need to:

-  Push your branch to under the **main** onnx-mlir repo (as opposed to a forked repo). This will allow your branch build to access our DockerHub access token on Travis. 
- Then, just push an empty commit with magic word "Rebuild prereq docker." as your commit message. Upon receiving the magic words, Travis should start rebuilding all the prereq containers and after it's done, it will push the new containers to DockerHub.

Alternatively, I can do all of that for you, but the new pull request (not the commits, which would still bear your name) will be attributed to me. Let me know what you prefer!

**Comment by NathanielMcVicar** [comment]
@tjingrant I can do it if you think it would be helpful to have another person helping keep these up to date. I don't care who's name is on the PR.

**Comment by tjingrant** [comment]
@NathanielMcVicar sounds good! Sent you an invite so that you can push your branch under the main repo.
You may have to open another pull request from that branch, as opposed to the branch in your forked repo. This change will allow your build to access onnx-mlir's DockerHub token on Travis. Let me know if you have any other questions!

**Pull request closed without merging**
