### PR TITLE
Add regex to accept version appendix for compilers

### PR DESCRIPTION
**Pull request by maxbartel**
Depending on the installation method, compilers get a version appendix. This adds support for that to the lit tests.

Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>

### CODE REVIEW

**Comment by maxbartel** [comment]
@tungld At which point is the Jenkins pipeline automatically started? Is there a specific number of contributions one must have?

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
> @tungld At which point is the Jenkins pipeline automatically started? Is there a specific number of contributions one must have?

@AlexandreEichenberger any comment on this? thanks!

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
> @tungld At which point is the Jenkins pipeline automatically started? Is there a specific number of contributions one must have?

There is no specific number of contributions, jenkins are protected because of where they run. We typically grant access to contributors that have a long term involvement with ONNX-MLIR repo and are part of a team that make significant contributions.

 @maxbartel, since we have not had a chance to meet at our weekly meetings (see wiki), maybe you can send me an email detailing your involvement with ONNX and ONNX-MLIR and we can take it from there, tx.

**Pull request merged**
