### PR TITLE
Move to more recent LLVM commit ID

### PR DESCRIPTION
**Pull request by tungld**
The new LLVM commit ID contains some important changes:
- The use of `Builder` is changed to `OpBuilder` in op build methods.
- AffineScope trait which is to define a new scope for polyhedral optimization purposes. I will enable this feature in onnx-mlir for loop-fusion once this patch is landed.

### CODE REVIEW

**Comment by gongsu832** [comment]
@tungld I submitted the pull request for zLinux Jenkins build bot to detect llvm-project commit change. However, the zLinux Jenkins will still fail. Because the new llvm-project commit f58e78f9920531f85d98e8041f6967eeb1bd0d3a fails shared library build on both x86 and z. It's missing a linkage dependency for libMLIRLinalgToStandard:
```
diff --git a/mlir/lib/Conversion/LinalgToStandard/CMakeLists.txt b/mlir/lib/Conversion/LinalgToStandard/CMakeLists.txt
index 84f19499bf7..6b060907322 100644
--- a/mlir/lib/Conversion/LinalgToStandard/CMakeLists.txt
+++ b/mlir/lib/Conversion/LinalgToStandard/CMakeLists.txt
@@ -14,6 +14,7 @@ target_link_libraries(MLIRLinalgToStandard
   MLIRIR
   MLIRLinalgOps
   MLIRSCF
+  MLIRTransforms
   LLVMCore
   LLVMSupport
   )
```
@tjingrant Maybe we should add shared library build check for CircleCI as well?

**Comment by tungld** [comment]
Thanks @gongsu832 for creating a patch! 

I found a new commit in LLVM, which looks related to LinalgToStandard: https://github.com/llvm/llvm-project/commit/1cff8e8de79f0308536fd78c81055c4452eb5c28#diff-6635fa1a5b0b10edf6e511585c7c986d

Do you think it helps fix our problem? If so, we can move to that commit.

**Comment by gongsu832** [comment]
@tungld Yes that commit fixes the problem and shared library build works again on both x86 and z.

**Comment by tungld** [comment]
Great. Let me update this patch to that commit.

**Comment by tungld** [comment]
@gongsu832 I saw a test failed in my environment when running `cmake --build . --target check-mlir`. The test was related to `ptrmask`, so I have to move to a bit newer commit id to fix the test: https://github.com/llvm/llvm-project/commit/0dc91bfd11e6cced0c46c1a25cc96edea0d8fc22#diff-6635fa1a5b0b10edf6e511585c7c986d

**Pull request merged**
