### PR TITLE
Fix typo in Workflow.md

### PR DESCRIPTION
**Pull request by weimingzha0**

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for improving the docs

When possible, please group several spelling fixes at once so as to reduce the total number of PR that goes through our CIs.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by hamptonm1** [comment]
@weimingzha0 Thanks for your help!

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@jenkins-droid test this please

**Pull request merged**
