### PR TITLE
build: update llvm tag to 21f4b84c

### PR DESCRIPTION
**Pull request by ashay**
Summary of changes (see commit messages for details):

 - mhlo: update mlir-hlo submodule to commit `b1ac0403`
 - onnx-mlir: [nfc] remove unused variables
 - onnx-mlir: [nfc] drop non-existent `useFoldAPI` attribute (https://reviews.llvm.org/D144391)
 - onnx-mlir: [nfc] update path to Host.h header file (https://reviews.llvm.org/D137838)
 - onnx-mlir: [nfc] flip boolean for implicit/explicit containing module (https://reviews.llvm.org/rG01cfdf1f8d44)

### CODE REVIEW

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Review by sstamenova — APPROVED** [review]
LGTM, assuming tests pass

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
@ashay thanks for a job well done and very speedily. 

@sstamenova added "tips and trick" observations on our wiki page (https://github.com/onnx/onnx-mlir/wiki/LLVM-Update-Schedule). Feel free to add more if you can think of something that will be helpful for others.

**Pull request merged**
