### PR TITLE
Use macos-13 for Github Action MacOS

### PR DESCRIPTION
**Pull request by tungld**
The macos-latest version is macos 14 that removed python 3.10, so it failed to install protobuf 4.21.12 using python 3.11 or 3.12 in macos 14. So, specifically use macos-13 to avoid unexpected failures, and we would update the macos version at a good timing in the future.

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@gongsu832 do you have any advice on this macos issue? I think macos-latest is now Sonoma 14, and python 3.10 is not available in the image (https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md) so it failed to install protobuf 4.21.12.

**Comment by gongsu832** [comment]
@tungld Debugging github action is very cumbersome and painful. If we don't require anything particular from macos-14, the simplest workaround for now is to just force macos-13, like you just did.

**Comment by tungld** [comment]
@gongsu832 thanks! I am ok to go with macos-13. By the way, do you know what happened to Jenkins Linux s390x, it does not run.

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
> By the way, do you know what happened to Jenkins Linux s390x, it does not run.

It's running now.

**Comment by gongsu832** [comment]
It ran out of disk space and was fixed.

**Pull request merged**
