### PR TITLE
Upgrade benchmark to v1.18.0

### PR DESCRIPTION
**Pull request by hamptonm1**
We have upgraded benchmark to v1.18.0 to include a fix I made with regards to "words that matter"

### CODE REVIEW

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, please run the benchmark (which I believe is not run automatically by our CIs). I believe it's the `make perf` target. It should it runs one s390 before merging. Thanks

**Review by cjvolzka — APPROVED** [review]

**Comment by hamptonm1** [comment]
> LGTM, please run the benchmark (which I believe is not run automatically by our CIs). I believe it's the `make perf` target. It should it runs one s390 before merging. Thanks

Thanks @AlexandreEichenberger. Okay let me do that now

**Comment by hamptonm1** [comment]
@AlexandreEichenberger 
```
root@07990fc19449:~/onnx-mlir/build# cmake --build . --target perf
[  3%] Built target benchmark
Consolidate compiler generated dependencies of target PerfLib
[  3%] Built target PerfLib
[  3%] Built target gen_onnx_proto
[  3%] Built target gen_onnx_data_proto
[  3%] Built target gen_onnx_operators_proto
[  4%] Built target onnx_proto
[ 11%] Built target onnx
[ 12%] Built target MLIRhlo_opsIncGen
[ 14%] Built target MLIRMhloRewriterIncGen
[ 16%] Built target MLIRMhloCanonicalizeIncGen
[ 16%] Built target MLIRlhlo_structured_interfaceIncGen
[ 16%] Built target mlir-generic-headers
[ 16%] Built target obj.HloOpsCommon
[ 16%] Built target HloOpsCommon
[ 16%] Built target StablehloBaseIncGen
[ 17%] Built target ChloOpsIncGen
[ 19%] Built target MLIRthlo_opsIncGen
[ 20%] Built target MLIRdeallocation_opsIncGen
[ 20%] Built target MLIRgml_st_opsIncGen
[ 20%] Built target MLIRlhlo_opsIncGen
[ 22%] Built target MLIRlhlo_gpu_opsIncGen
[ 24%] Built target StablehloOpsIncGen
[ 27%] Built target VhloOpsIncGen
[ 27%] Built target StablehloTestUtilsIncGen
[ 27%] Built target CheckOpsIncGen
[ 27%] Built target mlir-headers
[ 27%] Built target obj.StablehloBase
[ 27%] Built target StablehloBase
[ 27%] Built target obj.StablehloAssemblyFormat
[ 27%] Built target StablehloAssemblyFormat
[ 27%] Built target obj.StablehloTypeInference
[ 27%] Built target StablehloTypeInference
[ 27%] Built target obj.StablehloBroadcastUtils
[ 27%] Built target StablehloBroadcastUtils
[ 27%] Built target obj.ChloOps
[ 27%] Built target ChloOps
[ 27%] Built target obj.MLIRMhloUtils
[ 27%] Built target MLIRMhloUtils
[ 27%] Built target obj.MhloDialect
[ 27%] Built target MhloDialect
[ 27%] Built target obj.MhloRegisterDialects
[ 27%] Built target MhloRegisterDialects
[ 29%] Built target obj.Version
[ 29%] Built target Version
[ 29%] Built target obj.VhloTypes
[ 29%] Built target VhloTypes
[ 29%] Built target obj.VhloOps
[ 29%] Built target VhloOps
[ 29%] Built target obj.StablehloOps
[ 29%] Built target StablehloOps
[ 29%] Built target obj.StablehloRegister
[ 29%] Built target StablehloRegister
[ 29%] Built target ExternalUtil
[ 29%] Built target AcceleratorsInc
[ 29%] Built target OMAccelerator
Consolidate compiler generated dependencies of target OMCompilerOptions
[ 29%] Built target OMCompilerOptions
[ 29%] Built target OMSmallFPConversion
[ 29%] Performing update step for 'zdnn'
[ 29%] No patch step for 'zdnn'
[ 29%] No configure step for 'zdnn'
[ 29%] No build step for 'zdnn'
[ 29%] No install step for 'zdnn'
[ 30%] Completed 'zdnn'
[ 30%] Built target zdnn
[ 30%] Built target libzdnn
[ 32%] Built target OMZHighIncGen
[ 32%] Built target OMONNXZHighStickIncGen
[ 32%] Built target OMONNXZHighUnstickIncGen
[ 32%] Built target OMLayoutHelper
[ 32%] Built target OMShapeInferenceOpInterfaceIncGen
[ 32%] Built target OMKrnlIncGen
[ 32%] Built target OMSpecializedKernelOpInterfaceIncGen
[ 32%] Built target OMSpecializedKernelOpInterface
[ 32%] Built target OMMlirDialects
[ 32%] Built target OMShapeHelperOpInterfaceIncGen
[ 32%] Built target OMShapeHelperOpInterface
[ 33%] Built target OMResultTypeInferenceOpInterfaceIncGen
[ 33%] Built target OMHasOnnxSubgraphOpInterfaceIncGen
[ 35%] Built target OMONNXIncGen
[ 35%] Built target OMONNXRewriteIncGen
[ 35%] Built target OMMlirUtilities
[ 37%] Built target OMONNXElementsAttr
[ 37%] Built target OMDiagnostic
[ 48%] Built target OMONNXOps
[ 51%] Built target OMZHighOps
[ 51%] Built target OMONNXZLowCombineIncGen
[ 53%] Built target OMZLowIncGen
[ 53%] Built target OMZLowOps
[ 53%] Built target OMONNXONNXToZHighIncGen
[ 54%] Built target OMKrnlOps
[ 54%] Built target OMSupport
Consolidate compiler generated dependencies of target OMONNXToKrnl
[ 66%] Built target OMONNXToKrnl
[ 66%] Built target OMONNXToZHigh
[ 66%] Built target OMONNXRewriteONNXForZHighIncGen
[ 66%] Built target OMRewriteONNXForZHigh
[ 66%] Built target OMZHighToZLow
[ 67%] Built target OMKrnlToLLVM
[ 67%] Built target OMZLowToLLVM
[ 69%] Built target OMFoldStdAlloc
[ 69%] Built target OMONNXZHighConstPropagationIncGen
[ 70%] Built target OMStickify
[ 70%] Built target OMZHighConstPropagation
[ 72%] Built target OMONNXZHighLayoutPropagationIncGen
[ 72%] Built target OMZHighLayoutPropagation
[ 72%] Built target OMZLowRewrite
[ 72%] Built target OMZLowDummyOpForMultiDeref
[ 74%] Built target OMShapeInferenceOpInterface
[ 74%] Built target OMResultTypeInferenceOpInterface
[ 74%] Built target OMHasOnnxSubgraphOpInterface
[ 74%] Building CXX object src/Conversion/KrnlToAffine/CMakeFiles/OMKrnlToAffine.dir/ConvertKrnlToAffine.cpp.o
[ 75%] Linking CXX static library ../../../Debug/lib/libOMKrnlToAffine.a
[ 75%] Built target OMKrnlToAffine
[ 77%] Built target OMSeqToMemref
[ 79%] Built target OMONNXToTOSA
[ 79%] Built target OMONNXConvOptIncGen
[ 79%] Built target OMONNXDecomposeIncGen
[ 79%] Built target OMONNXConstPropIncGen
[ 80%] Built target OMONNXRewrite
[ 83%] Built target OMONNXToMhlo
[ 83%] Built target OMElideKrnlGlobalConstants
[ 83%] Built target OMEnableMemoryPool
[ 83%] Built target OMOptimizeMemoryPools
[ 83%] Built target OMBundleMemoryPools
[ 83%] Built target OMDisconnectKrnlDimFromAlloc
[ 85%] Built target OMLowerKrnlShape
[ 85%] Built target OMLowerKrnlRegion
[ 85%] Built target OMShapeInference
[ 85%] Building CXX object src/Transform/ONNX/CMakeFiles/OMShapeInferencePass.dir/ShapeInferencePass.cpp.o
[ 85%] Linking CXX static library ../../../Debug/lib/libOMShapeInferencePass.a
[ 85%] Built target OMShapeInferencePass
[ 85%] Building CXX object src/Transform/ONNX/CMakeFiles/OMInstrumentONNX.dir/InstrumentPass.cpp.o
[ 87%] Linking CXX static library ../../../Debug/lib/libOMInstrumentONNX.a
[ 87%] Built target OMInstrumentONNX
[ 87%] Built target OMOpTransform
[ 87%] Built target OMHybridTransform
[ 87%] Built target OMONNXPreKrnlVerifyONNX
[ 87%] Built target OMONNXSimplifyShapeRelatedOps
[ 87%] Built target OMONNXStandardFuncReturnPass
[ 87%] Building CXX object src/Builder/CMakeFiles/OMBuilder.dir/FrontendDialectTransformer.cpp.o
[ 88%] Linking CXX static library ../../Debug/lib/libOMBuilder.a
[ 88%] Built target OMBuilder
[ 88%] Generating ../../VCSVersion.inc
[ 88%] Building CXX object src/Version/CMakeFiles/OMVersion.dir/Version.cpp.o
[ 88%] Linking CXX static library ../../Debug/lib/libOMVersion.a
[ 88%] Built target OMVersion
[ 88%] Building CXX object src/Compiler/CMakeFiles/OMCompilerPasses.dir/CompilerPasses.cpp.o
[ 88%] Linking CXX static library ../../Debug/lib/libOMCompilerPasses.a
[ 88%] Built target OMCompilerPasses
[ 88%] Built target OMNNPACompilerOptions
[ 88%] Building CXX object src/Accelerators/NNPA/Compiler/CMakeFiles/OMNNPACompilerUtils.dir/NNPACompilerUtils.cpp.o
[ 88%] Linking CXX static library ../../../../Debug/lib/libOMNNPACompilerUtils.a
[ 88%] Built target OMNNPACompilerUtils
[ 88%] Built target RuntimeNNPA
[ 88%] Building CXX object src/Accelerators/NNPA/CMakeFiles/OMNNPAAccel.dir/NNPAAccelerator.cpp.o
[ 90%] Linking CXX static library ../../../Debug/lib/libOMNNPAAccel.a
[ 90%] Built target OMNNPAAccel
[ 90%] Built target OMInitAccelerators
[ 91%] Built target OMTensorUtils
[ 91%] Built target OMExecutionSession
[ 93%] Built target cruntime
[ 95%] Built target javaruntime
[ 95%] Built target jniruntime
[ 95%] Building CXX object src/Compiler/CMakeFiles/OMCompilerUtils.dir/CompilerUtils.cpp.o
[ 96%] Linking CXX static library ../../Debug/lib/libOMCompilerUtils.a
[ 96%] Built target OMCompilerUtils
[ 96%] Building CXX object src/Compiler/CMakeFiles/OMCompiler.dir/OnnxMlirCompiler.cpp.o
[ 96%] Linking CXX static library ../../Debug/lib/libOMCompiler.a
[ 96%] Built target OMCompiler
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/CategoryMapperModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/ConvModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/ElementwiseModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/GRUModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/GemmModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/LSTMModel.cpp.o
[ 96%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/LeakyReluModel.cpp.o
[ 98%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/MatMulModel.cpp.o
[ 98%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/ModelLib.cpp.o
[ 98%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/RNNModel.cpp.o
[ 98%] Building CXX object test/modellib/CMakeFiles/ModelLib.dir/ScanModel.cpp.o
[ 98%] Linking CXX static library ../../Debug/lib/libModelLib.a
[ 98%] Built target ModelLib
Consolidate compiler generated dependencies of target PerfElementwise
[ 98%] Building CXX object test/perf/CMakeFiles/PerfElementwise.dir/PerfElementwise.cpp.o
[ 98%] Linking CXX executable ../../Debug/bin/PerfElementwise
[ 98%] Built target PerfElementwise
Consolidate compiler generated dependencies of target PerfGemm
[ 98%] Building CXX object test/perf/CMakeFiles/PerfGemm.dir/PerfGemm.cpp.o
[ 98%] Linking CXX executable ../../Debug/bin/PerfGemm
[ 98%] Built target PerfGemm
Consolidate compiler generated dependencies of target PerfConv
[100%] Building CXX object test/perf/CMakeFiles/PerfConv.dir/PerfConv.cpp.o
[100%] Linking CXX executable ../../Debug/bin/PerfConv
[100%] Built target PerfConv
Consolidate compiler generated dependencies of target PerfRNN
[100%] Building CXX object test/perf/CMakeFiles/PerfRNN.dir/PerfRNN.cpp.o
[100%] Linking CXX executable ../../Debug/bin/PerfRNN
[100%] Built target PerfRNN
[100%] Built target perf
```

**Comment by hamptonm1** [comment]
@jenkins-droid test this please

**Pull request merged**
