### PR TITLE
Move to onnx 1.8.1

### PR DESCRIPTION
**Pull request by chentong319**
Update submodule onnx to 1.8.1.
The version of operations does not change yet.
Due to the interface change, ReduceSum, Unsqueezed, Squeez and split are removed from backend test temporarily. Also some softmax and logsoftmax are removed due to unmatched result.
Upgrading operation to this version will be put in separate patches later.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@chentong319 It would be good to have little to no regressions in the operations we support. If the patch are ready to go right away, then its ok

**Comment by chentong319** [comment]
@AlexandreEichenberger Lots of work is needed to fix the regression. Plan to use several small patches. Currently, there is a problem in check-doc even though I updated onnx.md.  Need to fix that issue before the patch can be merged.

**Comment by chentong319** [comment]
@gongsu832 I checked the Jenkins log, it seems to me that onnx 1.7 is used in cmake output. This may explain why the check doc failed for some build. Could you verify it?

**Comment by gongsu832** [comment]
@chentong319 ONNX-MLIR build uses whatever version of onnx in `third_party/onnx` so you need to actually update it to 1.8. I don't see the patch doing that.

**Comment by chentong319** [comment]
@gongsu832 I think I did not do git submodule --merge. The change is only in my branch.

**Comment by chentong319** [comment]
@gongsu832 @tjingrant In onnx, I did merge and commit. The status is
```
# HEAD detached from b2a20a9
nothing to commit, working directory clean
```
But outside of onnx directory, the status is 
```
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   third_party/onnx (new commits)
```
What git command should be used to stage this change?

**Comment by gongsu832** [comment]
It's actually telling you what to do:
```
#   (use "git add <file>..." to update what will be committed)
```
 So try `git add third_party/onnx`

**Comment by tjingrant** [comment]
@chentong319 you probably checked in more files than you should.

The commit you've checked in does not correspond to a commit that exists in upstream onnx.
https://github.com/onnx/onnx/tree/384cf36b13e43b0b2f5349f3dd602d9c08b0415d

Whereas if you look at the previous commit @gongsu832 checked in:
https://github.com/onnx/onnx/tree/b2a20a9d07678e89ae9346243035e194b63e0e8a

It corresponds to a commit that exists in upstream onnx.

You might want to delete the onnx subdirectory, re-clone it, check out the right version/branch, and re-commit without doing anything superfluous in between these steps.

**Comment by chentong319** [comment]
@tjingrant after I delete onnx and `git submodule update --recursive --init`, my submodule status is:
```
 1302d2ce094a9753b0f81a81ea74c0fa71fae582 third_party/benchmark (v1.5.1-13-g1302d2c)
 3af06fe1664d30f98de1e78c53a7087e842a2547 third_party/googletest (release-1.8.0-2454-g3af06fe)
 384cf36b13e43b0b2f5349f3dd602d9c08b0415d third_party/onnx (v1.8.1-1-g384cf36)
 8de7772cc72daca8e947b79b83fea46214931604 third_party/pybind11 (v2.6.2)
 7bc7d302191a4f3d0bf005692677126136e02f60 third_party/rapidcheck (remotes/origin/dev-127-g7bc7d30)
 3c7fc8266bb46046b42c2dc2663f9f505f0cec28 third_party/variant (v1.4.0-15-g3c7fc82)
```
Do I need to go further back?
What I did is in onnx, I did a fetch and merge, and then add/commit. If I can do the process from a clean branch, what should I do?

**Comment by seroyer** [comment]
> 
> 
> @tjingrant after I delete onnx and `git submodule update --recursive --init`, my submodule status is:
> 
> ```
>  1302d2ce094a9753b0f81a81ea74c0fa71fae582 third_party/benchmark (v1.5.1-13-g1302d2c)
>  3af06fe1664d30f98de1e78c53a7087e842a2547 third_party/googletest (release-1.8.0-2454-g3af06fe)
>  384cf36b13e43b0b2f5349f3dd602d9c08b0415d third_party/onnx (v1.8.1-1-g384cf36)
>  8de7772cc72daca8e947b79b83fea46214931604 third_party/pybind11 (v2.6.2)
>  7bc7d302191a4f3d0bf005692677126136e02f60 third_party/rapidcheck (remotes/origin/dev-127-g7bc7d30)
>  3c7fc8266bb46046b42c2dc2663f9f505f0cec28 third_party/variant (v1.4.0-15-g3c7fc82)
> ```
> 
> Do I need to go further back?
> What I did is in onnx, I did a fetch and merge, and then add/commit. If I can do the process from a clean branch, what should I do?

@chentong319 
You don't want to fetch and merge, you want to directly check out the tagged commit.  In this case:
`git checkout 685898bc6f3fd6eb16ba129ea990f96330537e38` from inside the onnx submodule.  It will put you in detached head state, and that's fine.

**Comment by chentong319** [comment]
@seroyer Thanks. That works.

**Comment by chentong319** [comment]
Replaced with #579

**Pull request closed without merging**
