### PR TITLE
Create initial scope when translating functions

### PR DESCRIPTION
**Pull request by gramalingam**
Fix issue relating to the introduction of nested-name-scopes that affects translation of ONNX functions. (Need to call pushScope/popScope for the initial scope in a function context).

### CODE REVIEW

**Comment by chentong319** [comment]
@jenkins-droid test this please.

**Comment by chentong319** [comment]
Can you explain why a new scope is needed for function call?

**Comment by gramalingam** [comment]
ONNX functions are used to help translate ONNX ops (e.g., custom ops) which can be expanded into an ONNX sub-graph. The translation of this expanded sub-graph, however, should NOT have access to the outer-scope names. Hence, a fresh new scope is used for the translation of this sub-graph.

**Review by chentong319 — APPROVED** [review]
LGTM!

**Pull request merged**
