### PR TITLE
Warning and instructions that --onnx-op-stats needs more than EmitONNXIR

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
sample warning:
```
root@1250b049ac2b:~/onnx-mlir/docs/mnist_example# onnx-mlir mnist.onnx  --onnx-op-stats=TXT --EmitONNXIR
Warning: --onnx-op-stats requires a target that goes further along than --EmitONNXIR
```

Stats are now piped to stdout

Signed-off-by: Alexandre Eichenberger <alexe@us.ibm.com>

### CODE REVIEW

**Comment by gongsu832** [comment]
It's a bit unclear what "further along than --EmitONNXIR" means exactly. You mean a target that is lower than ONNXIR?

**Comment by imaihal** [comment]
> It's a bit unclear what "further along than --EmitONNXIR" means exactly. You mean a target that is lower than ONNXIR?

I think so, too.  Is it better to add `Use --EmitMLIR or --EmitLLVMIR` or something?

```
$ ./build/Release/bin/onnx-mlir docs/mnist_example/mnist.onnx  --onnx-op-stats=TXT --EmitMLIR
Operations encountered:
-----------------------
  func.func             , 1
  func.return           , 1
  onnx.Constant         , 5
  onnx.Gemm             , 2
  onnx.MaxPoolSingleOut , 1
  onnx.Relu             , 1
  onnx.Reshape          , 1
  onnx.Softmax          , 1
```

```
$ ./build/Release/bin/onnx-mlir docs/mnist_example/mnist.onnx  --onnx-op-stats=TXT --EmitMLIR --maccel=NNPA
Operations encountered:
-----------------------
   func.func               , 1
   func.return             , 1
   onnx.Constant           , 1
   onnx.Reshape            , 1
   onnx.SqueezeV11         , 1
   onnx.UnsqueezeV11       , 1
  zhigh.MatMul             , 2
  zhigh.MaxPool2D          , 1
  zhigh.Relu               , 1
  zhigh.Softmax            , 1
  zhigh.Stick              , 3
  zhigh.StickifiedConstant , 4
  zhigh.Unstick            , 3
```

**Comment by AlexandreEichenberger** [comment]
Addressed comments with respect to messages. Thanks for the good suggestions.

**Comment by AlexandreEichenberger** [comment]
@gongsu832 I addressed your concern, you can review it again.

**Review by gongsu832 — APPROVED** [review]
LGTM

**Pull request merged**
