### PR TITLE
Make ExecutionSession work cross-platform

### PR DESCRIPTION
**Pull request by sstamenova**
ExecutionSession currently relies on dlfcn.h for its functionality, however, that solution does not work on all platforms (for example, it does not work on Windows). Instead use llvm's DynamicLibrary. This allows us to build and run ExecutionSession on all platforms supported by llvm including Windows.

This change depends on https://github.com/onnx/onnx-mlir/pull/718

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
@sstamenova it seems to break all of our build. Hopefully you can work in at least one environment to check the cause (probably linux amd64). Thanks

**Comment by caoimhinuibrian** [comment]
> @sstamenova it seems to break all of our builds. Hopefully you can work in at least one environment to check the cause (probably linux amd64). Thanks

@alexe .... it depends on #718 , which I just merged

**Comment by caoimhinuibrian** [comment]
@sstamenova currently has a conflict

**Comment by sstamenova** [comment]
> > @sstamenova it seems to break all of our builds. Hopefully you can work in at least one environment to check the cause (probably linux amd64). Thanks
> 
> @Alexe .... it depends on #718 , which I just merged

@AlexandreEichenberger @caoimhinuibrian : I merged the changes, so this should be all good now. Same for the flags change.

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Pull request merged**
