### PR TITLE
Use find_package(Python3) and bump min cmake version

### PR DESCRIPTION
**Pull request by sstamenova**
LLVM uses cmake version 3.13.4 and has dropped support for python2. This change brings onnx-mlir to the same versions of cmake and python as LLVM since onnx-mlir is including cmake files directly from LLVM and using the lit infrastructure
Without this change, the version of python used across the project is not consistent causing random build failures on (mostly Windows) machines that have both python2 and python3

This addresses part of #247 and #559

### CODE REVIEW

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@sstamenova based on your description of this patch, it looks like we should probably merge this patch despite Windows-CI failure? Given that the failures were not due to this patch, and enabling this patch will help us catch future Windows-specific problems.

**Comment by sstamenova** [comment]
> @sstamenova based on your description of this patch, it looks like we should probably merge this patch despite Windows-CI failure? Given that the failures were not due to this patch, and enabling this patch will help us catch future Windows-specific problems.

I think that's accurate. It does mean that the Windows-CI will stay red until #582 is resolved (to fix two of the tests) and the dependency issue for the third test is figured out as well (which I am looking at right now).

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
