### PR TITLE
Update LLVM and MHLO

### PR DESCRIPTION
**Pull request by hamptonm1**
I updated LLVM and MHLO with the latest commits:

Green LLVM commit: 3abae1c88416858cf2e9a7ed9417bc52033933b4
Green MHLO commit: 70ebc73a28767b772e09e0dd03cf3e47457435a2 (branch greencommit/2023-04-17-3abae1c8)

### CODE REVIEW

**Comment by hamptonm1** [comment]
@ashay The fix for the issue I was having with `MHLO` was just merged today around 10am. Am I still good to use the green commit from last week (4/17/23)... although I am pretty sure there is a new commit for this upcoming week for LLVM/MHLO, I wanted to double check before merging.

**Comment by hamptonm1** [comment]
@sorenlassen I checked to see if there were any new warnings introduced but I did not spot any. You are the wizard at spotting llvm warnings. Can you please let me know if I missed anything? Thanks!

**Comment by sorenlassen** [comment]
> @sorenlassen I checked to see if there were any new warnings introduced but I did not spot any. You are the wizard at spotting llvm warnings. Can you please let me know if I missed anything? Thanks!

I did a quick scan of the CI logs and didn't see any new warnings

**Comment by ashay** [comment]
> @ashay The fix for the issue I was having with `MHLO` was just merged today around 10am. Am I still good to use the green commit from last week (4/17/23)... although I am pretty sure there is a new commit for this upcoming week for LLVM/MHLO, I wanted to double check before merging.

(I realized I posted in the related issue instead of posting my comment here)

@hamptonm1 sorry I'm on PTO at the moment, so my apologies for the delayed response. There will be a new MHLO green commit this week, but I haven't yet had to chance to create a patch to make MHLO work with this week's LLVM green commit.

However, this week's MHLO green commit will only work with this week's (as opposed to last week's) LLVM green commit, so unless you want to re-do another LLVM update, it might be best to wait until next week's LLVM update to get the MHLO fixes.

**Comment by hamptonm1** [comment]
> > @ashay The fix for the issue I was having with `MHLO` was just merged today around 10am. Am I still good to use the green commit from last week (4/17/23)... although I am pretty sure there is a new commit for this upcoming week for LLVM/MHLO, I wanted to double check before merging.
> 
> (I realized I posted in the related issue instead of posting my comment here)
> 
> @hamptonm1 sorry I'm on PTO at the moment, so my apologies for the delayed response. There will be a new MHLO green commit this week, but I haven't yet had to chance to create a patch to make MHLO work with this week's LLVM green commit.
> 
> However, this week's MHLO green commit will only work with this week's (as opposed to last week's) LLVM green commit, so unless you want to re-do another LLVM update, it might be best to wait until next week's LLVM update to get the MHLO fixes.

@ashay Oh no the MHLO fix was from our end (internally to match what the MHLO community has)....so I pulled in last week MHLO and LLVM green commit.  I used the same green commits you gave me. 
Green LLVM commit: 3abae1c88416858cf2e9a7ed9417bc52033933b4
Green MHLO commit: 70ebc73a28767b772e09e0dd03cf3e47457435a2 (branch greencommit/2023-04-17-3abae1c8)

**Pull request merged**
