### PR TITLE
Add Option to Enable Warnings as Errors

### PR DESCRIPTION
**Pull request by manbearian**
This adds an option `ONNX_MLIR_ENABLE_WERROR` to enable warnings as errors in onnx-mlir. Its implementation is built on `LLVM_ENABLE_WERROR` and is constructed in such a way as it stops `LLVM_ENABLE_WERROR` from working (developers must set `ONNX_MLIR_ENABLE_WERROR`)

The new option `ONNX_MLIR_ENABLE_WERROR` defaults to `OFF`

### CODE REVIEW

**Comment by sstamenova** [comment]
@etiotto I know you are working hard to get the warnings enabled for onnx-mlir. There are a couple of options here: 
- add a new option like Ian's doing and use it to control LLVM_ENABLE_WERROR
- add a new option and implement the same logic as LLVM_ENABLE_WERROR
- force LLVM_ENABLE_WERROR to have the same value as the mlir build
- use LLVM_ENABLE_WERROR to control the warnings behavior of onnx-mlir as a cmake variable

I think Ian's solution is the best choice here, but please let us know.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this pleaase

**Comment by AlexandreEichenberger** [comment]
@manbearian Please sign the DCO and also do not forget to sign each of the `git commit` with the `-s` option, thanks.

**Comment by etiotto** [comment]
> @etiotto I know you are working hard to get the warnings enabled for onnx-mlir. There are a couple of options here:
> 
> * add a new option like Ian's doing and use it to control LLVM_ENABLE_WERROR
> * add a new option and implement the same logic as LLVM_ENABLE_WERROR
> * force LLVM_ENABLE_WERROR to have the same value as the mlir build
> * use LLVM_ENABLE_WERROR to control the warnings behavior of onnx-mlir as a cmake variable
> 
> I think Ian's solution is the best choice here, but please let us know.

I agree. I think having our own option is a good solution. 
@manbearian just curious, if you enable the option do we currently have still a lot of warnings. We have been cleaning up the code quite a bit in the last few months, so we should be getting close to the point where we can enable this option by default.

**Comment by etiotto** [comment]
@AlexandreEichenberger @gongsu832 you might need to give @manbearian permission, I see one of the CI bot failing with:
```
"ERROR: Exception: java.lang.Exception: admin authentication failed
Finished: FAILURE
```

**Comment by sstamenova** [comment]
@jenkins-droid please test this

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Review by etiotto — APPROVED** [review]
LGTM thanks.

**Comment by sstamenova** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
@manbearian You now pass all the tests but the DCO say "Waiting for status to be reported". I have never seen this. Do you mind maybe doing a small edit, and pushing the new version after doing signing the DCO statement. Or if you have not done the DCO statement, start with that, see if it unlocks. Thanks

**Comment by manbearian** [comment]
> @manbearian You now pass all the tests but the DCO say "Waiting for status to be reported". I have never seen this. Do you mind maybe doing a small edit, and pushing the new version after doing signing the DCO statement. Or if you have not done the DCO statement, start with that, see if it unlocks. Thanks

i believe its because i forgot to squash my last commits and they weren't signed. i'm pushing a new branch now.

**Comment by manbearian** [comment]
> @manbearian You now pass all the tests but the DCO say "Waiting for status to be reported". I have never seen this. Do you mind maybe doing a small edit, and pushing the new version after doing signing the DCO statement. Or if you have not done the DCO statement, start with that, see if it unlocks. Thanks

no clue what happened: i rebased onto latest main, force pushed, and now DCO looks green.

**Pull request merged**
