### PR TITLE
Fix for Issue #619

### PR DESCRIPTION
**Pull request by amanwithfruit**
When converting Slice op attrs to constant inputs, we need to use the size of the attribute as the shape of the constant.

Signed-off-by: aman <alachapelle@apple.com>

### CODE REVIEW

**Review by chentong319 — COMMENTED** [review]
Should we check the name of the attribute to be safe?

**Comment by amanwithfruit** [comment]
I'm not sure I understand what you mean, exactly? Why would this change depend on the name of the attribute?

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by chentong319** [comment]
I updated your branch with the master and will merge after tests are passed.

**Pull request merged**
