### PR TITLE
Fix OMInstrument.inc include on z/OS

### PR DESCRIPTION
**Pull request by seroyer**
Signed-off-by: Steven Royer <seroyer@us.ibm.com>

### CODE REVIEW

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Review by chentong319 — APPROVED** [review]
We do not have a test for instrument functionality on z/OS. Did you try to run a model with instrument? I should add some test cases.

**Comment by seroyer** [comment]
> 
> 
> We do not have a test for instrument functionality on z/OS. Did you try to run a model with instrument? I should add some test cases.

I have not tried instrumenting on z/OS.  This is just needed to be able to compile the runtimes.  I'm still working on testing and validating basic operation.

**Pull request merged**
