### PR TITLE
Document workflow as agreed in issue #1031

### PR DESCRIPTION
**Pull request by etiotto**
In the discussion in #1031 we agreed that the workflow for submitting pull requests for review should be:

1. create new PRs as drafts, allow rebasing commits until the PR is ready for code review
2. once the PR is ready for code review, change it to a regular PR. Reviewers are free to add comments at this point
3. when the PR is in review refrain from squashing commits, this should preserve history while reviews are in progress
4. when the PR has been approved, allow authors to again squash commits and edit the commit msgs
5. in its final approved form the PR should contain a single commit, with a single meaningful message

### CODE REVIEW

**Comment by gongsu832** [comment]
I'm not sure discussion in https://github.com/onnx/onnx-mlir/issues/1031 warrants such a "restrictive" PR policy. Everyone has different style of writing code and submitting PRs. As long as the process don't create undue management overhead, I don't think we should mandate a particular way of creating PRs. For example, I never create draft PRs because all my PRs are already tested locally and they are ready for review when submitted (with occasional need for additional commits to fix format, etc.), whereas other people like to start with a draft PR and push every single change to the PR (which IMO is actually the source of polluting the commit history).

So I think the root problem is more of a matter of people need to be more disciplined with the commits in the PRs. Mandating all PRs starting from a draft isn't going to fix that.

**Comment by AlexandreEichenberger** [comment]
Maybe we can add a few "encouraged" instead of should.

In general, would it be acceptable to not bother about `git commit -i` until the end? 

Personally, I find that clicking the "Update Branch" on the website is important. Sometimes there are many PRs waiting to be squashed to main, and it is a sequential process, so I like clicking on that. 

Other question: say a PR is finally ready to go, up to date with current main, reviews, but history needs updating. So the recommendation is that the author of the PR does a final `git commit -i` followed by a push. Will that re-trigger the CIs?

**Comment by etiotto** [comment]
> I'm not sure discussion in #1031 warrants such a "restrictive" PR policy...
I lifted the exact agreed steps from that discussion (https://github.com/onnx/onnx-mlir/issues/1031#issuecomment-996093889). Nevertheless, I agree we need to support different styles. The ultimate goals of that discussion was to end up with:
  - committed PRs that contain a clean log message
  - allow for incremental code reviews where comments from reviewers are addressed in specific commits
  
 I can attempt to modify the document changes to "relax" the requirements of starting from a draft PR.
 
 > In general, would it be acceptable to not bother about git commit -i until the end?
 IMO yes, as long as in the end the log has a clear concise message explaining what the patch does.
 
 > Personally, I find that clicking the "Update Branch" on the website is important. Sometimes there are many PRs waiting to be squashed to main, and it is a sequential process, so I like clicking on that.
 I think that is fine, as long as the commit msg is edited to avoid having the individual commits mgs that are being squashed as the final commit msg. 
 
> Other question: say a PR is finally ready to go, up to date with current main, reviews, but history needs updating. So the recommendation is that the author of the PR does a final git commit -i followed by a push. Will that re-trigger the CIs?

Yup. Any push action will trigger CI again.

**Comment by etiotto** [comment]
@gongsu832 @AlexandreEichenberger I attempted to address the concerns expressed above. Please take another look.

**Comment by AlexandreEichenberger** [comment]
By the way, I found an incredible easy way to achieve the stated goals from the GitHub interface.

Only do git merge during development and review... full history is preserved.
Hit "merge" button from interface as many times as needed.

When you are ready to squash and merge, the interface actually list in a text box the actual text that will be put in the log. By default, it is the current list of commit, but one can edit it to whatever one wants. So remove all but the first author/date and last signed-off by... and write your harts content in the  middle.

```
Author: Alexandre Eichenberger <alexe@us.ibm.com>
Date:   Wed Jan 19 15:33:14 2022 +0000

<< edit here whatever you want>>
    
    Signed-off-by: Alexandre Eichenberger <alexe@us.ibm.com>
```

Thus, we have the nice text, and the "squash" of the "squash and merge" button already present the changes as only one "event" in the history.

So no need to do any git commit, merge, rebase, if one is content to use the GitHub interface to finalize the text on Github.

**Comment by AlexandreEichenberger** [comment]
@etiotto if that approach above works, I would suggest to split the new approach into two: one though the git commands and one through the GitHub website. Folks can choose what they feel more comfortable with.

**Comment by doru1004** [comment]
> When you are ready to squash and merge, the interface actually list in a text box the actual text that will be put in the log. By default, it is the current list of commit, but one can edit it to whatever one wants. So remove all but the first author/date and last signed-off by... and write your harts content in the middle.

This is what I meant by being able to adjust the message when you do the actual merge.

**Comment by doru1004** [comment]
Rebasing is important for projects that do not do squashed commits and attempt to capture the full commit history. For our case, squashed commits go to the top of the main branch and the commit blurb is editable prior to merging but after the squashing has occurred. By default the message contains the commit messages of all squashed commits but all that can be edited out before clicking the merge button. So actually the only thing we need to be careful to do is to edit out the part containing the squashed commits prior to the final merge.

**Comment by AlexandreEichenberger** [comment]
> So actually the only thing we need to be careful to do is to edit out the part containing the squashed commits prior to the final merge.

exactly. We can still provide the `git` commands for folks that prefer them. I find that using merge all the way through, relying on the squash that is fool-proof, and simply editing the text in the browser works best for me. So I am requesting that we add this in our doc

**Comment by doru1004** [comment]
> So I am requesting that we add this in our doc

Something like: "The commit history will be replaced by the patch name before the merge is final."

**Comment by sstamenova** [comment]
I think the github options are more straightforward also, I think documenting the expectation to use them and provide a meaningful commit message is the best approach - instead of having a second option through git commands. The flow with the git commands is not as straightforward and likely to confuse people.

**Comment by AlexandreEichenberger** [comment]
@etiotto do you want to update the PR?

**Comment by etiotto** [comment]
Agreed with @AlexandreEichenberger that this PR is no longer necessary. We can start a new one and document the workflow in a simpler way, specifically how to use the GUI to create a clean final commit message upon merging a PR.

**Pull request closed without merging**
