### PR TITLE
Fix an issue about inserting instrument before op

### PR DESCRIPTION
**Pull request by imaihal**
This PR fixes https://github.com/onnx/onnx-mlir/issues/1600 about instrumentation

- `krnl.runtime_instrument` was not inserted before target op for instrumentation. This PR fixes it and it is inserted before and after the op correctly.
- Add lit tests to avoid these bugs in the future.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
assigning @chentong319 as he wrote this pass, if I recall correctly

**Comment by gongsu832** [comment]
@jenkins-droid test this please

**Review by chentong319 — APPROVED** [review]
LGTM!

**Review by manbearian — APPROVED** [review]

**Comment by imaihal** [comment]
@jenkins-droid test this please

**Pull request merged**
