### PR TITLE
Rewrite BatchNormTestMode into x*a+b

### PR DESCRIPTION
**Pull request by tungld**
This patch is to rewrite BatchNormTestMode into `x * a + b` where `a` and `b` are computed from the constant inputs (scale, bias, mean, var).

Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@tung: looks good, why "Test Mode"?

**Comment by tungld** [comment]
> why "Test Mode"?

It refers to "inference mode". It's a bit confusing, so if you are agree, we can change the op name to BatchNormInferenceMode in this patch also.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, approved pending change to "Inference" mode. Test means something else :-) Let me know when the change is done. Saw at least a test in the lit-tests

**Comment by tungld** [comment]
@AlexandreEichenberger I changed TestMode to InferenceMode. It is ready for merging.

**Pull request merged**
