### PR TITLE
Update llvm version

### LINKED ISSUE #185: Not able to build ONNX
This happens when I run the "cmake .." command, I have already built the llvm project (For this I have used the instructions on the MLIR getting started page : [)](https://mlir.llvm.org/getting_started/)) and set the environment variable to the right path.

error

and this is the ouput of the CMakeError.log
`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c1976/fast && /usr/bin/make -f CMakeFiles/cmTC_c1976.dir/build.make CMakeFiles/cmTC_c1976.dir/build
make[1]: Entering directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c1976.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_c1976.dir/src.c.o   -c /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_c1976
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c1976.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_c1976.dir/src.c.o  -o cmTC_c1976 
/usr/bin/ld: CMakeFiles/cmTC_c1976.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_c1976.dir/build.make:87: cmTC_c1976] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_c1976/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_a5dee/fast && /usr/bin/make -f CMakeFiles/cmTC_a5dee.dir/build.make CMakeFiles/cmTC_a5dee.dir/build
make[1]: Entering directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_a5dee
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a5dee.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_a5dee.dir/CheckFunctionExists.c.o  -o cmTC_a5dee  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_a5dee.dir/build.make:87: cmTC_a5dee] Error 1
make[1]: Leaving directory '/home/akhil/Downloads/onnx-mlir/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_a5dee/fast] Error 2
`

### PR DESCRIPTION
**Pull request by aaronsm**
Fixes #185

### CODE REVIEW

**Comment by tungld** [comment]
Thank you for this PR! Could you please postpone for a while to include this patch in MLIR: https://reviews.llvm.org/D82158? The patch was approved and will be landed in one or two days I hope.

**Comment by aaronsm** [comment]
I'll leave that up to you. These changes fix the onnx-mlir build which has been broken for about two weeks now. These changes work with the latest llvm-project as of June 25, 2020.

**Comment by tungld** [comment]
Hi @aaronsm,

https://reviews.llvm.org/D82158 was landed. Could you please update to the last LLVM commit ID?

About CI failures, it was because we still use the cached LLVM version. To trigger a new LLVM version installation, please increase the cache key here: https://github.com/onnx/onnx-mlir/blob/master/.circleci/config.yml#L21. 

Thank you!

**Comment by AlexandreEichenberger** [comment]
While some scripts are still running, it looks like a much higher success rate than before. Looks on the right track.

Please fix the formatting, probably a white space in ./src/Transform/LowerToLLVM.cpp

**Comment by aaronsm** [comment]
What is the your plan to stay in synch with llvm-project? Daily or weekly merges would be a reasonable frequency.

**Comment by tjingrant** [comment]
Hi @aaronsm , thanks for the update!

> What is your plan to stay in synch with llvm-project? Daily or weekly merges would be a reasonable frequency.

We don't have a fixed schedule for syncing with upstream llvm-project, but weekly merges sound about reasonable. I will keep an eye on it from now on.

> Why two README.mds? One in the root directory and one in the docs directory and the CI checks that the one in docs is updated.

One is for Github users, the other for our doc website onnx.ai/onnx-mlir. It would be nice if we can emphasize different aspects of our projects in distinct contexts, and by doing so, de-duplicate these two documentation pages. Thanks for your comments & I will think about it!

**Comment by aaronsm** [comment]
> Hi @aaronsm , thanks for the update!
> 
> > What is your plan to stay in synch with llvm-project? Daily or weekly merges would be a reasonable frequency.
> 
> We don't have a fixed schedule for syncing with upstream llvm-project, but weekly merges sound about reasonable. I will keep an eye on it from now on.
> 
> > Why two README.mds? One in the root directory and one in the docs directory and the CI checks that the one in docs is updated.
> 
> One is for Github users, the other for our doc website onnx.ai/onnx-mlir. It would be nice if we can emphasize different aspects of our projects in distinct contexts, and by doing so, de-duplicate these two documentation pages. Thanks for your comments & I will think about it!

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
