### PR TITLE
Move passes options to their own thing

### PR DESCRIPTION
**Pull request by manbearian**
Potential solution to #1346

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by manbearian** [comment]
looks like another shared object build failure; this one though looks addressable. i'll investigate locally and push an update soon.

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Review by tungld — APPROVED** [review]
LGTM.

**Comment by manbearian** [comment]
merge conflicts resolved

**Comment by manbearian** [comment]
See also PR #1363

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, like the better separation between options provided by this PR, thanks

**Comment by manbearian** [comment]
Going to go with #1363 so closing this PR without committing.

**Pull request closed without merging**
