### PR TITLE
Change the default value for the "--onnx-op-transform-threshold" from 3 to 10

### PR DESCRIPTION
**Pull request by negiyas**
Change the default value for the "--onnx-op-transform-threshold" option from 3 to 10 to fix the issue 1584 ( https://github.com/onnx/onnx-mlir/issues/1584 )

It should not be an big issue to change the default value from 3 to 10, because of the following reasons.

(1) At least 4 times repeat of the corresponding passes are necessary to fix this issue.
(2) If the target code is not changed by an iteration, further iterations are stopped at the iteration. 

Confirmed that this issue is solved by the PR.

Signed-off-by: Yasushi Negishi <negishi@jp.ibm.com>

### CODE REVIEW

**Comment by negiyas** [comment]
Confirmed that the issue 1584 is solved by theis PR.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM. Could you just run the resnet50 from the check-onnx-backend and record the time with 4 and 10 in this PR, so that we have a reference of if it slows down at all? That would be great.

Thanks for finding the issue and a quick fix to it, much appreciated

**Comment by negiyas** [comment]
I measured  time to execute "TEST_CASE_BY_USER=test_resnet50_cpu cmake --build . --target check-onnx-backend" by changing the default value from 4 to 10.
We cannot see any slowdown  according to the measurement results.

4: Ran 2026 tests in 156.981s
6: Ran 2026 tests in 157.096s
8: Ran 2026 tests in 156.717s
10: Ran 2026 tests in 157.068s

**Comment by AlexandreEichenberger** [comment]
Fantastic, big thanks

**Pull request merged**
