### PR TITLE
Bundle individual memory pools into a single memory pool

### PR DESCRIPTION
**Pull request by doru1004**
This patch bundles individual memory pools into a single memory pool.

### CODE REVIEW

**Comment by doru1004** [comment]
> LGTM, thanks for all the comments, very helpful.
> 
> I could not find the check "is shape dynamic", but I assume that your match returns failure if a dyn shape is detected. If not yet, please add it, there is an MLIR call that check for precisely that.

The shape is checked when the getref operations are emitted. So for now, the only get refs we will have are ones with constant sizes.

**Comment by tjingrant** [comment]
It would be nice if we can include a LIT test that specifically targets the pass introduced here, instead of testing memory pool optimization pipelines end-to-end.

I may be missing some context here, but what is the motivation for this rewrite pattern like this? Looking at the left-hand-side of this pattern rewrite rule alone, the optimal code transformation to perform is to eliminate `%mem1` because it is not used, so it leaves me wondering what gives. It would be nice if we can have a self-contained example where the pattern rewrite rule introduced in this patch is unequivocally the optimal move to make.
```
 *  RewritePattern that replaces:
 *    %mem1 = alloc() : memref<<dims1>x<type>>
 *    %mem2 = alloc() : memref<<dims2>x<type>>
 *    %1 = krnl.getref %mem2 0 : memref<<dims2>x<type>>
 *  =>
 *    %mem1 = alloc() : memref<<dims1 + dims2>x<type>>
 *    %1 = krnl.getref %mem1 <dims1> : memref<<dims2>x<type>>
```

**Comment by doru1004** [comment]
> It would be nice if we can include a LIT test that specifically targets the pass introduced here, instead of testing memory pool optimization pipelines end-to-end.
> 
> I may be missing some context here, but what is the motivation for this rewrite pattern like this? Looking at the left-hand-side of this pattern rewrite rule alone, the optimal code transformation to perform is to eliminate `%mem1` because it is not used, so it leaves me wondering what gives. It would be nice if we can have a self-contained example where the pattern rewrite rule introduced in this patch is unequivocally the optimal move to make.
> 
> ```
>  *  RewritePattern that replaces:
>  *    %mem1 = alloc() : memref<<dims1>x<type>>
>  *    %mem2 = alloc() : memref<<dims2>x<type>>
>  *    %1 = krnl.getref %mem2 0 : memref<<dims2>x<type>>
>  *  =>
>  *    %mem1 = alloc() : memref<<dims1 + dims2>x<type>>
>  *    %1 = krnl.getref %mem1 <dims1> : memref<<dims2>x<type>>
> ```

I only show the lines relevant to the transformation so the use of mem1 is not included.

**Comment by doru1004** [comment]
> It would be nice if we can include a LIT test that specifically targets the pass introduced here, instead of testing memory pool optimization pipelines end-to-end.

I think that makes sense, I can add such a test no problem. The current test doesn't show the state before the application of the pass, which I think is what you're looking for.

**Pull request merged**
