### PR TITLE
Bump to llvm commit 8b76aea8d8b1b71f6220bc2845abc749f18a19b7

### PR DESCRIPTION
**Pull request by flemairen6**
Green LLVM commit: 8b76aea8d8b1b71f6220bc2845abc749f18a19b7
Green MHLO commit: cae5349f85b3b2f58d80ca788e9a8695d896c3a8

### CODE REVIEW

**Comment by maxbartel** [comment]
@jenkins-droid test this please

**Comment by maxbartel** [comment]
@jenkins-droid test this please

**Comment by ttjost** [comment]
@AlexandreEichenberger I am seeing an issue with the `powerpc` pipeline that relates to a recent change in `llvm-exegesis`. Therefore, we don't even build LLVM for it. =(
LLVM buildbots for `ppc` pass the test.  Do you have any idea how to solve this?
The error says that `__builtin_thread_pointer' is not supported on this target`, but I don't have a way to reproduce this.
Thank you!

**Comment by philass** [comment]
Ahh that looks really frustrating.

I wonder if we can play with CMake flags to not build with `llvm-exegesis`

**Comment by ttjost** [comment]
> Ahh that looks really frustrating.
> 
> I wonder if we can play with CMake flags to not build with `llvm-exegesis`

I tried doing that. This led to disabling `llvm-mca`, `obj2yaml`, and `yaml2obj`, but `lit tests` all seem to depend on them, and I get a bunch of CMake dependency errors between these tools and tests.
 
In any case, it turns out `__builtin_thread_pointer` is not supported by `gcc` (https://godbolt.org/z/chEnh7Ton), but works with `clang` (https://godbolt.org/z/c9bdTqv5f), that is why LLVM buildbots for PPC work and onnx-mlir pipelines don't.

I am somewhat blocked now, since this only happens on PPC + GCC (it seems), and everything else is green.
Should we try building an in-tree `clang` for it?
Could you anyone check this, please?

**Comment by sorenlassen** [comment]
maybe the problem has to do with this llvm code change:
https://github.com/llvm/llvm-project/commit/46b5b855489f87aac2487d099175807880486041

but I can't think of any workaround

**Comment by AlexandreEichenberger** [comment]
@flemairen6 @ttjost What about the s390 error, is it unrelated?

**Comment by sorenlassen** [comment]
@jenkins-droid test this please

**Comment by sorenlassen** [comment]
@ttjost please sign-off on the last commit to fix the DCO failure

I'm not 100% sure why the jenkins pipelines fail with `ERROR: Exception: java.lang.Exception: admin authentication failed`, maybe it's blocked by the DCO failure?

**Comment by sorenlassen** [comment]
@jenkins-droid test this please

**Comment by sorenlassen** [comment]
@AlexandreEichenberger can you tell why the jenkins pipelines are failing with `ERROR: Exception: java.lang.Exception: admin authentication failed`?

**Comment by gongsu832** [comment]
```
/workdir/llvm-project/llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp: In member function 'llvm::Error llvm::exegesis::{anonymous}::SubProcessFunctionExecutorImpl::createSubProcessAndRunBenchmark(llvm::StringRef, llvm::SmallVectorImpl<long int>&) const':
/workdir/llvm-project/llvm/tools/llvm-exegesis/lib/BenchmarkRunner.cpp:336:61: error: '__builtin_thread_pointer' is not supported on this target
  336 |         syscall(SYS_rseq, (intptr_t)__builtin_thread_pointer() + __rseq_offset,
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~^~
```
Apparently ppc64le does not support `__builtin_thread_pointer`

**Review by maxbartel — APPROVED** [review]
LGTM, the clang PR is also already up https://github.com/onnx/onnx-mlir/pull/2379

**Comment by maxbartel** [comment]
@AlexandreEichenberger @philass I will merge this if the pipelines are green, the clang fix landed

**Pull request merged**
