### PR TITLE
ingest float16

### PR DESCRIPTION
**Pull request by sorenlassen**
addresses #1703

based on an earlier implementation by @rdicecco

Co-authored-by: Roberto DiCecco dicecco.rob@gmail.com
Signed-off-by: Soren Lassen <sorenlassen@gmail.com>

### CODE REVIEW

**Comment by sorenlassen** [comment]
this PR is now ready for review

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, let's have @chentong319 have a second look, tx

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by AlexandreEichenberger** [comment]
@sorenlassen let me know if you want to merge it

**Comment by sorenlassen** [comment]
@chentong319 @AlexandreEichenberger thanks for the review, please merge it for me

**Pull request merged**
