### PR TITLE
Script to run onnx-mlir from docker container

### PR DESCRIPTION
**Pull request by gongsu832**
- Convenient python script to run onnx-mlir from docker container
- Check freopen failure in MainUtils.cpp:outputCode
- Ignore invalid -o option values in main.cpp
- Update README.md about the convenient python script

Signed-off-by: Gong Su <gong_su@hotmail.com>

### CODE REVIEW

**Review by caoimhinuibrian — APPROVED** [review]
LGTM

**Comment by caoimhinuibrian** [comment]
@sstamenova there were some Windows changes and the Windows CI is failing, could you take a look please?

**Comment by gongsu832** [comment]
I'm guessing the problem is that `stderr` is a constant on Windows. Not sure how to reopen `stderr` on Windows in this case.

**Comment by sstamenova** [comment]
> I'm guessing the problem is that `stderr` is a constant on Windows. Not sure how to reopen `stderr` on Windows in this case.

That is indeed the case: https://docs.microsoft.com/en-us/cpp/c-runtime-library/stdin-stdout-stderr?view=msvc-160

```
D:\a\1\onnx-mlir\src\MainUtils.cpp(562,39): error C2106: '=': left operand must be l-value [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
D:\a\1\onnx-mlir\src\MainUtils.cpp(573,37): error C2106: '=': left operand must be l-value [D:\a\1\onnx-mlir\build\src\MainUtils.vcxproj]
```

I am not sure if it is possible to re-open stderr or stdout on Windows, but I was wondering - why do we need to do any redirection for stderr at all? As far as I know, the ```print()``` function can take any ```raw_ostream```, so to print the output to a file, we just need to pass it to print instead of ```llvm::errs```. Am I missing a use case?

**Comment by gongsu832** [comment]
I didn't write that code originally but did feel it's a bit strange with the redirection. Perhaps @tjingrant can offer some insights?

**Comment by sstamenova** [comment]
> I didn't write that code originally but did feel it's a bit strange with the redirection. Perhaps @tjingrant can offer some insights?

@tjingrant @gongsu832 : I'd like to clean this bit of code (using stderr for file output) unless there's a reason to keep it as is. If you have any objections, please let me know, otherwise I'll follow up with a PR some time next week.

**Comment by AlexandreEichenberger** [comment]
> @tjingrant @gongsu832 : I'd like to clean this bit of code (using stderr for file output) unless there's a reason to keep it as is. If you have any objections, please let me know, otherwise I'll follow up with a PR some time next week.

@sstamenova  What is the status of this. Should we go with this PR as is, and you propose your cleanup in a different PR? That would appear the easiest way to go about it. Let me know, thanks

**Comment by sstamenova** [comment]
> > @tjingrant @gongsu832 : I'd like to clean this bit of code (using stderr for file output) unless there's a reason to keep it as is. If you have any objections, please let me know, otherwise I'll follow up with a PR some time next week.
> 
> @sstamenova What is the status of this. Should we go with this PR as is, and you propose your cleanup in a different PR? That would appear the easiest way to go about it. Let me know, thanks

This can't be checked in as is because it will fail the Windows build.

**Comment by sstamenova** [comment]
https://github.com/onnx/onnx-mlir/pull/784 makes the necessary changes to write directly to the output file

**Comment by AlexandreEichenberger** [comment]
@gongsu832 I pushed #784 to the master branch, there are now conflict with this one as you forecasted. I let you fix them, thanks

**Comment by gongsu832** [comment]
@AlexandreEichenberger The conflict has been resolved and it's ready to go.

**Pull request merged**
