### PR TITLE
grew windows CI timeout

### PR DESCRIPTION
**Pull request by sorenlassen**
see @jcwchen advice in issue #2481

### CODE REVIEW

**Comment by sorenlassen** [comment]
with windows-2022 I encountered this error in step "Install onnx-mlir" in Windows-CI.yml
```
-- Build files have been written to: D:/a/1/onnx-mlir/build
ninja: error: 'C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/DIA SDK/lib/amd64/diaguids.lib', needed by 'Release/bin/onnx-mlir.exe', missing and no known rule to make it
```

any suggestions how to overcome this are welcome

**Review by jcwchen — COMMENTED** [review]
I guess the reason is the CI directly used cached llvm with windows-2022? However, that cached llvm was built with windows-2019. Building llvm from scratch with windows-2022 in this PR might help.

**Comment by sorenlassen** [comment]
> Building llvm from scratch with windows-2022 in this PR might help.

ok, I changed `$mlir_tag` to not use the windows-2019 artifacts but then it fails building llvm-project:
```
[183/4217] Building IntrinsicsLoongArch.h...
FAILED: include/llvm/IR/IntrinsicsLoongArch.h D:/a/1/llvm-project/build/include/llvm/IR/IntrinsicsLoongArch.h 
cmd.exe /C "cd /D D:\a\1\llvm-project\build && D:\a\1\llvm-project\build\bin\llvm-min-tblgen.exe -gen-intrinsic-enums -intrinsic-prefix=loongarch -I D:/a/1/llvm-project/llvm/include/llvm/IR -ID:/a/1/llvm-project/build/include -ID:/a/1/llvm-project/llvm/include D:/a/1/llvm-project/llvm/include/llvm/IR/Intrinsics.td --write-if-changed -o include/llvm/IR/IntrinsicsLoongArch.h -d include/llvm/IR/IntrinsicsLoongArch.h.d"
```
it looks like llvm-min-tblgen.exe fails but I don't know what goes wrong or how to overcome that

**Review by jcwchen — COMMENTED** [review]
Just found the latest llvm is still using windows-2019 in its CI: https://github.com/llvm/llvm-project/blob/bce6c53464c115f5f83a57284e409b1db8c2b03f/.github/workflows/llvm-project-tests.yml#L40-L42 and so it might not be compatible with newer windows-2022. Sorry I should confirm it earlier and thank you for trying it out. I guess the least thing we can do right now is simply increasing the timeout a bit?

**Comment by sorenlassen** [comment]
> Sorry I should confirm it earlier and thank you for trying it out.

no problem

> I guess the least thing we can do right now is simply increasing the timeout a bit?

ok, I reverted the vmImage upgrade from this PR - please approve if you agree with the change

I would love if you can find another solution to make the Windows CI run faster - it is typically the slowest of the CI pipelines and therefore slows down onnx-mlir development

**Review by jcwchen — APPROVED** [review]

**Pull request merged**
