### PR TITLE
Use IndexExpr to compute divisor for ReduceMean

### PR DESCRIPTION
**Pull request by tungld**
Signed-off-by: Tung D. Le <tung@jp.ibm.com>

### CODE REVIEW

**Review by AlexandreEichenberger — COMMENTED** [review]
@tungld I wonder if you would not want to use IndexExpr on this one. This is precisely why I wrote it, not to have lengthy special code for testing for constants.

**Comment by tungld** [comment]
> @tungld I wonder if you would not want to use IndexExpr on this one. This is precisely why I wrote it, not to have lengthy special code for testing for constants.

Oh, right. We can use IndexExpr whenever we have index-related calculation. Will update this patch now.

**Comment by tungld** [comment]
@AlexandreEichenberger I changed the patch to use IndexExpr. Thanks for your comments!

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks

**Pull request merged**
