### PR TITLE
feat(bump): Bump 'onnx-mlir' to llvm '2dde4ba63974'

### PR DESCRIPTION
**Pull request by BraunPhilipp**
Minor version bump for `onnx-mlir` to ensure compatibility with `torch-mlir`. Mostly passing still needs some work.

TODO:
* fix remaining `getValue` warnings
* some segfaults in the mlir tests

### CODE REVIEW

**Comment by sstamenova** [comment]
@BraunPhilipp : If you haven't seen this, we are trying to track the coordination here: https://github.com/llvm/torch-mlir/issues/1178. There's a pending merge into onnx-mlir to bump the llvm version (https://github.com/onnx/onnx-mlir/pull/1599), but because some of the changes impact the accelerators, we need to wait until it can be tested by the folks that have access to the special machines. Hopefully, the next bump doesn't require special testing and can happen faster.

**Comment by BraunPhilipp** [comment]
Thanks for the overview @sstamenova! Internally, we currently need a working version bump for `onnx-mlir`. The draft PR was opened accidentally. I expect the changes to be fairly minor once your PR lands.

**Comment by sstamenova** [comment]
> @sstamenova would it make sense to have a pinned issue that list what the next llvm update should go to? Or a link to where the next coordinated update should go to?

@AlexandreEichenberger: I think that would make sense. Right now we're tracking in the torch-mlir issue here (https://github.com/llvm/torch-mlir/issues/1178), but we could have a pinned issue in onnx-mlir which at least points to the torch-mlir issue and people can comment on that and indicate if/when they are doing merges.

**Comment by AlexandreEichenberger** [comment]
My bad, saw you just did one. Thanks for reading my mind :-)

**Comment by sstamenova** [comment]
@BraunPhilipp : Now that my merge has been committed, can you update yours to be on top of main? There should be just a few small changes and it will bring onnx-mlir another week forward.

**Comment by BraunPhilipp** [comment]
I will ask @ljfitz tomorrow. AMD has not yet cleared me to contribute to the repo; that's why the other PR is also stale.

**Comment by AlexandreEichenberger** [comment]
Hopefully they will clear you, love to have more outstanding contributors. Let us know if we can help.

**Pull request closed without merging**
