### PR TITLE
[NNPA] Call ScrubDisposablePass before ZHighConstPropagation

### PR DESCRIPTION
**Pull request by tungld**
Since `ZHighConstPropagation` currently works with `DenseElementAttr` only, call `ScrubDisposablePass` to replace any `DisposableElementsAttr` with `DenseElementsAttr` before calling `ZHighConstPropagation`.

### CODE REVIEW

**Comment by sorenlassen** [comment]
it should be easy to make ZHighConstPropagation read DisposableElementsAttr, are you interested in help with that?

**Comment by tungld** [comment]
> it should be easy to make ZHighConstPropagation read DisposableElementsAttr, are you interested in help with that?

@sorenlassen it's a good idea. I am a bit busy this week so will create a new PR for it later. If possible I would like to have this landed since it fixes a performance regression in one of our benchmarks.

**Review by hamptonm1 — APPROVED** [review]
@tungld Adding the `ScrubDisposablePass` looks good to me as a mitigation for now.

**Comment by hamptonm1** [comment]
> > it should be easy to make ZHighConstPropagation read DisposableElementsAttr, are you interested in help with that?
> 
> @sorenlassen it's a good idea. I am a bit busy this week so will create a new PR for it later. If possible I would like to have this landed since it fixes a performance regression in one of our benchmarks.

Maybe create an issue so you do not forget to remove the ScrubDisposablePass and allow zHighConstPropagation to read DisposableElementsAttr.

**Comment by sorenlassen** [comment]
> If possible I would like to have this landed since it fixes a performance regression in one of our benchmarks.

ok

**Comment by tungld** [comment]
Thanks @sorenlassen and @hamptonm1! I created an issue as a memo: https://github.com/onnx/onnx-mlir/issues/2587

**Pull request merged**
