### PR TITLE
support i64 for run_onnx_lib

### PR DESCRIPTION
**Pull request by sjkbar-furiosa**
To run NMS by run_onnx_lib binary, i64 type need to be supported
This patch is regarding, https://github.com/onnx/onnx-mlir/issues/1005

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@sjkbar-furiosa thanks for the patch! 

Could you sign your commit to let DCO pass? Please click the Details button by DCO for more information. For new commits, you can use `git commit -s` to sign. Thanks!

**Comment by tungld** [comment]
@jenkins-droid test this please

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM, thanks for contributing this.

**Comment by AlexandreEichenberger** [comment]
@sjkbar-furiosa we will need you to accept the DCO before being able to merge it. It should be a formality, and you may then have to click on the "details" next to the DCO to do further processing of your new status.

**Pull request merged**
