### PR TITLE
Enable build with installed LLVM

### PR DESCRIPTION
**Pull request by KeDengMS**
There are build systems that use installed LLVM. As long as LLVM is built with LLVM_INSTALL_UTILS=ON, FileCheck will be included and could run lit test out of tree.

This change allows build onnx-mlir and run lit test with installed LLVM with following commands:
```
pip install lit
export LLVM_PROJ_SRC=/path/to/llvm-install
export LLVM_PROJ_BUILD=/path/to/llvm-install
cmake -DUSE_INSTALLED_LLVM=ON -DLLVM_EXTERNAL_LIT=$(which lit) -DBUILD_SHARED_LIBS=ON ../..
cmake --build .
LIT_OPTS=-v cmake --build . --target check-onnx-lit
```

### CODE REVIEW

**Comment by tjingrant** [comment]
Hi @KeDengMS , I wonder what's wrong with `-DLLVM_EXTERNAL_LIT=$(which lit)`? 
I'm not seeing why an extra level of indirection through `util/lit.py` isn't redundant?

**Comment by KeDengMS** [comment]
> Hi @KeDengMS , I wonder what's wrong with `-DLLVM_EXTERNAL_LIT=$(which lit)`?
> I'm not seeing why an extra level of indirection through `util/lit.py` isn't redundant?

Yes $(which lit) works too, removing utils/llvm-lit.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Review by tjingrant — APPROVED** [review]
LGTM!

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by gongsu832** [comment]
@tjingrant The Jenkins build machine went through updates which update python from 3.8 to 3.9. That apparently has broken the builds since llvm-project needs to be rebuilt and onnx needs to be reinstalled. I see that you already rebuilt llvm-project so I rebuilt llvm-project-shared and reinstalled onnx. Builds should work now. If not let me know. Sorry for the trouble.

**Comment by tjingrant** [comment]
@gongsu832 just to double check, I couldn't figure out which version of onnx to install on s390x. I ended up using my own modified onnx 1.7 pkg with big endian support pulled from onnx 1.8. Which seems to work as of my latest attempt. 

Could you clarify which onnx version you're using? (FYI, pure onnx 1.7 doesn't support big endian numpy arrays, pure onnx 1.8 has different onnx spec, causing backend tests to fail). I ended up creating my modified onnx version for 390x at `/tmp/onnx-z`.

**Comment by gongsu832** [comment]
@tjingrant Installed version is 1.8. OK then I will install 1.7 with big endian fix.

**Comment by gongsu832** [comment]
@tjingrant The official 1.7.0 doesn't have big endian fix. I need to find the patch. Do you have the patch?

**Comment by tjingrant** [comment]
@gongsu832 sorry for the late reply, I put it under `/tmp/onnx-z`.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Comment by tjingrant** [comment]
@jenkins-droid test this please.

**Pull request merged**
