### PR TITLE
regenerated docs

### PR DESCRIPTION
**Pull request by sorenlassen**
with the command `cmake --build . --target onnx-mlir-docs`

### CODE REVIEW

**Comment by sorenlassen** [comment]
The instructions in the comments in ONNX.td
https://github.com/onnx/onnx-mlir/blob/main/src/Dialect/ONNX/ONNX.td#L15
say to run `make onnx-mlir-docs` but that doesn't work for me and instead I ran `cmake --build . --target onnx-mlir-docs`

Is that correct? Should I edit the instructions?

The same goes for `make OMONNXOpsIncTranslation`: should we change that to `cmake --build . --target OMONNXOpsIncTranslation`?

**Comment by sorenlassen** [comment]
@tungld can I ask you to review this PR? among other things it includes the documentation for ONNXShapeTransformOp

**Review by tungld — APPROVED** [review]
LGTM.

**Comment by tungld** [comment]
I always use `make onnx-mlir-docs` and `make OMONNXOpsIncTranslation`, and haven't seen any issue. I call them inside `build` folder.

**Comment by sorenlassen** [comment]
> I always use `make onnx-mlir-docs` and `make OMONNXOpsIncTranslation`, and haven't seen any issue. I call them inside `build` folder.

I figured out that it's because I build with ninja instead of make on OSX, following the instructions here:
https://github.com/onnx/onnx-mlir/blob/main/docs/BuildOnLinuxOSX.md
I can use `ninja onnx-mlir-docs`

I can use make if I build with `-G"Unix Makefiles"` instead of `-G Ninja`

we might consider changing the instructions to use `cmake --build . --target onnx-mlir-docs` which should work across ninja and make

**Comment by sorenlassen** [comment]
Now also regenerated krnl.md, zhigh.md, zlow.md

**Pull request merged**
