### PR TITLE
ShapeInference ONNXIsNaNOp

### PR DESCRIPTION
**Pull request by mmoldawsky**

### CODE REVIEW

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Review by doru1004 — APPROVED** [review]
LGTM pending passing tests

**Comment by doru1004** [comment]
@jenkins-droid test this please

**Comment by caoimhinuibrian** [comment]
@jenkins-droid test this please

**Comment by mmoldawsky** [comment]
Why is the Jenkins test failing immediately?

**Comment by AlexandreEichenberger** [comment]
@mmoldawsky did you mean to close this PR?

**Comment by mmoldawsky** [comment]
Yes, there was an issue with some of the files. Doru told me to close this one and make a new branch and a new PR. The new PR is here : https://github.com/onnx/onnx-mlir/pull/1412

**Pull request closed without merging**
