### PR TITLE
FIX compile error with latest LLVM

### PR DESCRIPTION
**Pull request by willzhang4a58**

### CODE REVIEW

**Comment by willzhang4a58** [comment]
image

**Comment by willzhang4a58** [comment]
image

**Comment by AlexandreEichenberger** [comment]
@jenkins-droid test this please

**Comment by AlexandreEichenberger** [comment]
You will need to approve the DCO license. See step 7 https://github.com/onnx/onnx-mlir/blob/main/docs/Workflow.md#step-7-commit--push

**Comment by willzhang4a58** [comment]
@AlexandreEichenberger  I have fixed the DCO

**Comment by AlexandreEichenberger** [comment]
@chentong319 do you mind checking this one, its in the frontend, parameters given to `makeArrayRef`, Thanks

**Comment by willzhang4a58** [comment]
type of attrs.float() is protobuf::RepeatField
type of attrs.float().begin() is protobuf::RepeatField::Iterator
maybe in older version, protobuf::RepeatField::Iterator was implemented as pointer
however, I build with protobuf v3.20.1, which is the latest version

**Review by chentong319 — APPROVED** [review]
LGTM!

**Comment by willzhang4a58** [comment]
@AlexandreEichenberger

**Comment by willzhang4a58** [comment]
hi @AlexandreEichenberger , could it be merged.

**Review by AlexandreEichenberger — APPROVED** [review]
LGTM

**Comment by AlexandreEichenberger** [comment]
@willzhang4a58 Thanks for the help on this one, much appreciated.

**Pull request merged**
