### PR TITLE
feat: split softmax into softmaxV11 and softmax

### PR DESCRIPTION
**Pull request by maxbartel**
@tungld As discussed in https://github.com/onnx/onnx-mlir/issues/1876 this patch splits the `SoftmaxOp` into `SoftmaxOp `and `SoftmaxV11Op`. Doing this also has the benefit that the special handling in the `FrontendDialectTransformer` could be deleted. I also adapted the ONNXToKrnl conversion and the lit test to work with the new implementation. Since this is my first solo contribution:

> I hereby confirm that I abided by the DCO requirements.

Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>

### CODE REVIEW

**Comment by tungld** [comment]
@jenkins-droid test this please

**Review by tungld — APPROVED** [review]
LGTM! Congrats on your first contribution and looking forward to next ones. Thanks!

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by tungld** [comment]
@maxbartel it's ready to merge, but the patch is out-of-date with the base branch. Usually, we can merge for you, but somehow I cannot do it with PRs from `Xilinx` github account, perhaps your local repos has some settings that prevent us to do that. So if the situation does not change, we always need to wait for you updating with the base branch, which slows down the merging.

Anyway, please update the patch with the base branch. Then I will merge it if there is no other PR comes in in advance. Otherwise, we need to update again.

**Comment by tungld** [comment]
@jenkins-droid test this please

**Comment by maxbartel** [comment]
@tungld thank you! I will see if it is a setting on our side and if we can change it.

**Pull request merged**
